-- =============================================================
-- Curso: O Blueprint de Parach (Dr. Richard William)
-- Capítulo 2 — O Ecossistema do Jardim  (aula ordem = 4)
--
-- Continua a montagem (095 = Prefácio/Introdução, 096 = Capítulo 1).
-- Localiza o curso pelo slug e insere a aula no ordem 4, sem mexer
-- no que já existe.
--
-- Texto transcrito palavra por palavra do PDF do Capítulo 2.
-- Cabeçalhos de seção em CAIXA ALTA para renderizarem como títulos
-- (ver ehTitulo() em components/AulaConteudo.tsx). As quebras "• • •"
-- do livro viram linhas em branco entre os blocos.
--
-- Numeração exibida: o badge/cabeçalho deriva do título via
-- rotuloNumeroAula() — "Capítulo 2" → "02"; Prefácio/Introdução → "00".
--
-- Atividades = reflexão (tipo='reflexao'). Idempotente.
-- =============================================================

do $migration$
declare
  v_curso_id uuid;
  v_aula_id uuid;
begin
  select id into v_curso_id from public.cursos
  where slug = 'blueprint-parach';

  if v_curso_id is null then
    raise exception 'Curso blueprint-parach não encontrado — rode a migration 095 antes.';
  end if;

  -- ---------------------------------------------------------------
  -- Capítulo 2 — O Ecossistema do Jardim  (aula ordem = 4)
  -- ---------------------------------------------------------------
  select id into v_aula_id from public.aulas
  where curso_id = v_curso_id and ordem = 4;

  if v_aula_id is null then
    insert into public.aulas (curso_id, titulo, ordem, conteudo)
    values (
      v_curso_id,
      'Capítulo 2 — O Ecossistema do Jardim',
      4,
$conteudo$Cinco Dons, Uma Videira, e o Ecossistema de Deus

Se o Capítulo 1 foi o diagnóstico, este capítulo é o primeiro vislumbre da cura. Porque uma vez que você enxerga a epidemia do esforço pelo que ela é — uma vez que nomeia a fábrica, a ilusão da celebridade, a escada errada — a pergunta inevitável é: como deveria ser? Se o modelo corporativo não é o design de Deus, qual é? Se estivemos seguindo o blueprint errado, onde está o certo?

A resposta é mais antiga do que qualquer livro de negócios. É tão antiga quanto o Éden.

Alguns anos atrás, visitei um pastor aposentado que se dedicara à jardinagem. Observei-o se mover pelo quintal com uma espécie de alegria paciente que eu não via em anos de ministério. Ele se ajoelhava ao lado de um pé de tomate e falava dele como se estivesse descrevendo uma pessoa — seu temperamento, o tipo de solo que preferia, quanta luz do sol precisava, quando podá-lo e quando deixá-lo em paz. "Sabe o que eu nunca faço?", disse ele, olhando para mim com terra nas mãos e um sorriso no rosto. "Eu nunca grito com o tomate para crescer mais rápido."

Eu ri, mas as palavras me atingiram como um trem de carga. Porque era exatamente isso que eu vinha fazendo no ministério por anos. Estava dirigindo minha igreja como uma fábrica — medindo produção, aumentando eficiência, pressionando mais quando os números não subiam. Tinha gritado com o tomate. Tinha gritado comigo mesmo. E tinha esquecido a verdade mais básica de todas: a igreja nunca foi projetada para ser uma linha de montagem. Foi projetada para ser um jardim. Mas para entender por que o jardim é muito mais do que uma metáfora, precisamos voltar ao começo — porque a história bíblica começa e termina em um jardim, e isso não é coincidência. É uma revelação.

O Jardim do Éden nunca foi pensado para ser um lugar de lazer estático — um paraíso onde Adão se reclinava numa rede enquanto anjos lhe traziam frutas. Era um sistema altamente calibrado e preexistente onde Deus funcionava como o Mestre Agricultor e a humanidade funcionava como o operador. Era uma parceria. E entender como essa parceria foi projetada para funcionar é a chave para entender tudo o que deu errado com nossa liderança — e tudo o que pode dar certo.

Antes de Adão dar sua primeira respiração, Deus já havia estabelecido toda a infraestrutura da vida. O sistema já estava funcionando. Os minerais, os quatro rios e o potencial biológico de cada semente já estavam em movimento. O jardim era um hardware acabado — um modelo de ordem divina representando um oásis do cosmos de Deus, destinado a ser o blueprint que eventualmente seria expandido para cobrir toda a terra. O milagre da vida — o DNA do fruto, a mudança das estações, a centelha biológica do crescimento — estava inteiramente sob a soberania de Deus. Adão não inventou o nascer do sol. Não engendrou a colheita. Ele entrou em um ritmo que já fora posto em movimento pelo Criador.

Esta é a primeira verdade do ecossistema de Deus, e todo pastor que já ficou acordado à noite preocupado se a igreja vai sobreviver precisa ouvi-la: o sistema funciona porque Deus o construiu, não porque nós o operamos. O Reino de Deus estava funcionando antes de você chegar. Vai funcionar depois que você partir. Você está entrando em algo que já está vivo, já está se movendo, já está sendo sustentado por um poder que nada tem a ver com seu esforço. Seu trabalho não é fazer o sistema funcionar. Seu trabalho é funcionar dentro do sistema.

Embora o sistema fosse perfeito, estava incompleto sem o elemento humano. Adão foi colocado no Jardim para ser o software que executava o programa da criação. Sua responsabilidade era definida por dois conceitos hebraicos que deveriam redefinir o entendimento de todo pastor sobre seu chamado. O primeiro é Avad — servir, lavrar, cultivar. Adão era um servo do solo, encarregado de extrair o potencial inerente que Deus havia escondido na terra. Ele não criou o potencial. Cultivou o que já estava lá. O segundo é Shamar — guardar, manter, proteger. O ecossistema era um santuário sagrado que requeria um mordomo vigilante para manter seus limites e protegê-lo de ameaças externas. Você vê a descrição do cargo? Não era CEO. Não era visionário. Não era construtor de plataformas. Era cultivador e guardião. A tarefa de Adão era extrair o que Deus havia plantado e proteger o ambiente para que o plantio pudesse florescer. Esse é o modelo original de liderança — e ele nunca foi revogado.

Há algo mais que vale notar. Quando Adão nomeou os animais, não estava impondo sua própria ordem sobre a criação. Estava usando seu intelecto para discernir a essência de cada criatura, reconhecendo a ordem que Deus já havia incorporado nela. Isso é o que um líder Parach faz: não impõe sua visão sobre a igreja. Discerne o que Deus já plantou nas pessoas e ajuda isso a vir à superfície.

Uma parte crítica do ecossistema original era a distinção entre esforço e resultado — e é aqui que a liderança moderna errou terrivelmente. Adão tinha que operar dentro de realidades que estavam além de seu controle. Podia plantar e regar, mas somente Deus podia dar o crescimento. Tinha que sincronizar seu trabalho com um relógio celestial que não construiu, aprendendo a virtude da paciência. Não podia acelerar as estações ou forçar a colheita. E a presença da serpente no Jardim prova que o sistema não era um vácuo — havia ameaças genuínas. Mas o trabalho de Adão não era impedir que o inimigo existisse. Seu trabalho era guardar os portões do sistema e seu próprio coração. O líder que se esforça obliterou esse limite. Tentamos controlar o que somente Deus pode controlar — os resultados, as estações, o crescimento, o timing — enquanto negligenciávamos o que nos foi realmente dito para fazer: cuidar do solo e guardar os portões. Estamos exaustos porque estamos tentando fazer o trabalho de Deus enquanto negligenciamos o nosso.

Quando lemos a Queda em Gênesis 3, tipicamente pensamos nela como uma regra quebrada — Adão e Eva comeram o fruto proibido. Mas foi muito mais do que isso. Foi um colapso de todo o ritmo humano-divino. Foi uma dessincronização do ecossistema. Houve uma mudança de dependência para independência: em um ecossistema, um ramo que tenta ser sua própria fonte morre, e ao buscar definir o bem e o mal à parte de Deus, a humanidade se desconectou do Agricultor. Houve uma mudança de serviço para domínio: a humanidade passou de servir o jardim para explorá-lo, e quando o mordomo para de cuidar, o sistema experimenta atrito — simbolizado em Gênesis pelos espinhos e abrolhos que agora infestavam o solo. E houve uma inversão de controle que é dolorosamente relevante para todo líder que lê isto: a humanidade começou a tentar controlar o que somente Deus pode — os resultados, o timing, o crescimento — enquanto negligenciava o que lhes fora realmente atribuído para fazer.

Este é o sistema operacional do pastor que se esforça. Tentamos controlar o crescimento da igreja, que é domínio de Deus. Tentamos eliminar toda ameaça e gerenciar todo resultado, que é domínio de Deus. Tentamos produzir fruto pela força da vontade, que é domínio de Deus. E enquanto isso, negligenciamos o solo das nossas próprias almas. Negligenciamos os portões dos nossos próprios corações. Negligenciamos o cultivo das pessoas que Deus realmente colocou sob nossos cuidados. Estamos fazendo o trabalho de Deus e negligenciando o nosso — e os espinhos e abrolhos do esgotamento são o resultado inevitável.

Na verdade, quando você dá um passo atrás e olha para todo o arco das Escrituras, percebe que a Bíblia é essencialmente um estudo de caso em alinhamento sistêmico. Quando indivíduos ou nações sincronizavam suas vidas com o design do Agricultor, o ecossistema florescia. Quando tentavam re-engendrar o sistema segundo suas próprias especificações, os resultados eram consistentemente desastrosos. O padrão se repete de Gênesis a Apocalipse, e tem tudo a ver com a maneira como lideramos hoje.

Considere Noé. Ele viveu em uma era em que o ecossistema humano se corrompera completamente — total dessincronização. Deus lhe deu dimensões e materiais específicos para a Arca, um blueprint preciso para uma estrutura que não fazia sentido para o mundo ao seu redor. Noé não discutiu com o design. Não tentou melhorá-lo nem construir um tipo diferente de embarcação. Gênesis 6:22 diz simplesmente: "Noé fez tudo exatamente como Deus lhe ordenou." Porque se sincronizou com o plano de Deus, a semente da humanidade e do reino animal foram preservadas através de um colapso sistêmico global. Mas olhe o que aconteceu depois. Após o dilúvio, a humanidade se reuniu em Babel e tentou construir outra estrutura — desta vez em seus próprios termos. Em vez de seguir o mandamento de Deus de encher a terra e expandir o ecossistema, decidiram centralizar e "fazer um nome para si mesmos." O sistema entrou em colapso. Sua língua foi confundida, o projeto foi abandonado, e o que deveria ser um monumento à realização humana se tornou um monumento à arrogância humana. Um homem seguiu o blueprint e o mundo foi salvo. Uma geração inteira o rejeitou e tudo desmoronou.

Considere Abraão. Deus o chamou para deixar um sistema funcional feito pelo homem — a sofisticada cidade de Ur — para entrar em um ecossistema divino de promessa. Quando Abraão se moveu pela Palavra de Deus, prosperou. Mesmo quando estava cultivando terras desconhecidas, o Agricultor forneceu riqueza e proteção além de qualquer coisa que Abraão pudesse ter engendrado. Mas quando Abraão e Sara se cansaram de esperar pelo herdeiro prometido, decidiram ajudar o sistema. Tentaram forçar o fruto em vez de esperar pela estação, e Ismael nasceu através de Hagar. Foi um atalho — uma tentativa de produzir pelo esforço humano o que somente Deus podia produzir no Seu timing. O resultado foi atrito sistêmico e conflito familiar que dura por gerações. Todo líder que já tentou forçar um resultado que Deus não havia autorizado sabe exatamente como isso se sente. O atalho sempre acaba levando mais tempo do que a espera.

Considere a nação de Israel entrando na Terra Prometida. Aquela terra foi descrita como uma que "bebe água da chuva do céu" — um sistema completamente dependente do Agricultor. Sob Josué, o povo seguiu instruções específicas e muitas vezes ilógicas. Marchar ao redor de Jericó sete vezes? Enviar trezentos homens contra um exército de milhares? Essas não eram estratégias militares. Eram exercícios de alinhamento — testes para saber se o povo sincronizaria com o design de Deus ou insistiria no seu próprio. Quando se alinharam, herdaram um ecossistema funcional que não precisaram construir. A terra já fluía leite e mel. As vinhas já estavam plantadas. As casas já estavam de pé. Tudo o que tinham que fazer era entrar e ser mordomos do que Deus havia preparado. Mas durante o período dos Juízes, a Bíblia diz "cada um fazia o que parecia certo aos seus próprios olhos." Pararam de seguir as leis do jardim. Abandonaram o ritmo. E o resultado foi devastador: a cerca de proteção foi abaixada, eram constantemente invadidos, suas colheitas eram roubadas, e a terra que um dia fluía com abundância perdeu sua paz.

E depois há a comparação suprema de dois operadores no mesmo sistema: o Rei Saul e o Rei Davi. Saul foi instruído a esperar pelo profeta Samuel para oferecer o sacrifício, mas ficou impaciente — tentou controlar as estações — e o fez ele mesmo. Mais tarde, foi comandado a destruir tudo em batalha, mas guardou o melhor das ovelhas contra as instruções explícitas de Deus — tentou controlar os recursos. Em ambos os casos, Saul tentou re-engendrar o sistema segundo seu próprio julgamento, e o resultado foi o mesmo: foi desconectado do reinado. A unção se levantou. A presença partiu. O jardim morreu. Davi, em contraste, esteve longe de ser perfeito. Pecou gravemente. Mas as Escrituras o chamam de "um homem segundo o coração de Deus", e o que isso significa é que a intenção de Davi era sempre re-sincronizar-se com a vontade de Deus. Quando caía, se arrependia. Quando se desviava, retornava. Quando foi tentado a tomar o trono matando Saul, recusou — porque entendia que o sistema pertence a Deus, não a ele. E o resultado foi um reino que se tornou a era de ouro de Israel.

O padrão é inconfundível. Siga o blueprint e o ecossistema prospera. Re-engendre o sistema segundo suas próprias especificações e ele desmorona. Isto não é história antiga. É um diagnóstico para todo pastor, todo plantador de igrejas, todo líder ministerial que está lendo este livro. A pergunta não é se você está trabalhando duro o suficiente. A pergunta é se você está alinhado com o design. Você está seguindo o blueprint do Agricultor — ou está construindo sua própria Torre de Babel? Você está esperando no timing de Deus — ou está produzindo um Ismael? Você está sendo mordomo do que Deus já preparou — ou está fazendo o que é certo aos seus próprios olhos?

Mas o Agricultor nunca mudou Seu modelo. Ele vem trabalhando para restaurar o ecossistema original desde o momento em que foi quebrado. O Tabernáculo era um Éden portátil — um espaço sagrado onde a presença de Deus habitava entre Seu povo, com um motivo de jardim entrelaçado em seu próprio design. O Templo expandiu essa visão. Os profetas apontaram para um dia em que o deserto floresceria e os montes gotejariam vinho. Jesus ensinou sobre videiras e ramos, sementes e solo, jardineiros e vinhas — porque Ele não estava introduzindo um conceito novo. Estava restaurando o original. E a Bíblia termina exatamente onde começa: em um jardim. A Nova Jerusalém em Apocalipse 22 é uma Cidade-Jardim, com o rio da vida fluindo por ela e a árvore da vida dando fruto em cada estação — doze tipos de fruto, um para cada mês. O modelo original finalmente expandido para cobrir toda a terra.

Não precisamos inventar uma nova maneira de liderar. Precisamos re-aprender como funcionar dentro daquela que foi estabelecida no começo. O sistema foi projetado antes de chegarmos. Funciona porque Deus o sustenta. Nosso papel é o mesmo que sempre foi: cultivar o solo, guardar os portões, permanecer conectados à Fonte, e confiar ao Agricultor a colheita. Quando entendemos isso — verdadeiramente entendemos, não como teologia mas como estilo de vida — o esforço para. Porque você percebe que nunca esteve carregando o peso. Você sempre esteve de pé em um jardim que já estava vivo.

Por décadas, a Igreja Global inconscientemente terceirizou sua filosofia de liderança para o mundo corporativo. Importamos linguagem de negócios — lançamento de visão, planejamento estratégico, estrutura organizacional, indicadores-chave de desempenho — e a colocamos sobre algo que nunca foi feito para funcionar como uma corporação. No modelo da fábrica, o pastor é o CEO, o sucesso é medido pela produção, as pessoas se tornam recursos, e o líder carrega o peso esmagador de ser pessoalmente responsável por cada avanço do Reino. Mas Deus nunca projetou Sua Igreja como uma fábrica. Ele a projetou como um jardim — um ecossistema vivo e pulsante onde cada planta é única, cada estação tem um propósito, e o crescimento vem não do esforço do jardineiro mas da vida fluindo pelo solo.

É aqui que a palavra hebraica no coração deste livro se torna essencial. Parach significa florescer, brotar, desabrochar. Não é uma palavra sobre esforço. É uma palavra sobre vida — sobre o que acontece quando algo é plantado no solo certo, conectado à fonte certa, e dado as condições certas para crescer. Ela está em contraste com outro conceito hebraico de liderança: Manhigut, derivado de uma raiz que significa "conduzir". No hebraico moderno, a mesma raiz é usada para dirigir um carro. Manhigut pinta o retrato de um líder atrás do volante, agarrando firmemente, conduzindo pela força de vontade pessoal. Trata fundamentalmente do que o líder faz. Parach é fundamentalmente diferente. Enquanto Manhigut trata da condução, Parach trata do desabrochar. Enquanto um se concentra na performance do líder, o outro se concentra na vida fluindo através do líder. Manhigut pergunta o que você está produzindo. Parach pergunta se você está conectado à Fonte.

Passei a primeira década do meu ministério em modo Manhigut sem nem saber. Estava atrás do volante a cada momento de cada dia — conduzindo, corrigindo, acelerando, freando. E estava exausto, porque pensava que o veículo cairia se eu soltasse por um momento sequer. Foi preciso um quase colapso para perceber que a igreja não é um veículo que estou dirigindo. É um jardim que Deus está cultivando. E meu trabalho nunca foi conduzi-lo. Meu trabalho era cuidar dele — e deixar Ele trazer o florescer.

A palavra parach aparece em algumas das passagens mais poderosas das Escrituras sobre liderança e vida. Em Números 17, após um grande desafio à autoridade de Moisés e Arão, Deus não pediu a Arão que se defendesse ou provasse seu valor. Simplesmente disse: coloque sua vara na Minha presença. Durante a noite, o pedaço de madeira seco e morto de Arão fez o que nenhum esforço humano poderia produzir — brotou, produziu flores e deu amêndoas maduras. Três estágios de vida apareceram em uma vara morta. Arão não fez nada além de se posicionar na presença de Deus, e Deus fez o resto. A verdadeira autoridade espiritual não é tomada ou defendida. É confirmada por fruto que somente Deus pode produzir.

No Salmo 92, o salmista usa parach para descrever o líder justo: "O justo florescerá como a palmeira." As palmeiras prosperam no deserto porque suas raízes alcançam fontes de água profundas e ocultas. Elas balançam nas tempestades sem quebrar e dão fruto até na velhice. Em Isaías 35, o profeta usa parach para descrever a vinda da restauração de Deus: "O deserto se alegrará e florescerá como a rosa." Uma terra devastada e seca é repentinamente revivida em beleza e abundância — e é isso que acontece quando um líder Parach entra em uma comunidade seca, não com esforço pessoal, mas com graça divina. E em João 15, embora o hebraico dê lugar ao grego, Jesus encarna a essência de parach em Sua metáfora da videira e dos ramos. O trabalho principal do líder não é produzir fruto. É permanecer conectado à Fonte. O fruto é responsabilidade do Agricultor.

Passar da fábrica para o jardim requer cinco mudanças fundamentais em como pensamos sobre liderança. A primeira é de produção para presença — medir o sucesso não pela produção, mas pela saúde da videira e pela maturidade do fruto. A segunda é de adrenalina para unção — não mais funcionando pelo carisma pessoal e força de vontade do líder, mas aprendendo a pegar a corrente ascendente do Espírito Santo, o que chamo de a Teologia da Corrente Térmica. A terceira é de hierarquia para família — ver a igreja não como uma corporação liderada por um CEO onde as pessoas servem a visão do líder, mas como uma família liderada pelo Pai onde o líder cultiva um ambiente para que todos floresçam. A quarta é de escassez para abundância — substituir a ansiedade de nunca ter o suficiente pela paz que vem de servir um Rei que possui tudo e não está em pânico com o estado do Seu Reino. E a quinta é de crescimento forçado para ritmo sazonal — honrar a realidade de que Deus projetou a liderança para incluir períodos sagrados de recolhimento, descanso e restauração, e que o inverno não é fracasso, mas preparação.

Quando adotamos o modelo da fábrica, construímos monumentos ao nosso próprio esforço que eventualmente nos esmagam sob seu peso. Mas quando retornamos ao jardim, participamos de algo sobrenatural, sustentável e gerador de vida. A mudança começa no momento em que paramos de tentar ser o motor da igreja e começamos a ser um ramo da Videira.

Há um diagnóstico simples mas devastador que revela se estamos operando como uma fábrica ou como um jardim. Ele vem de Gálatas 5: "O fruto do Espírito é amor, alegria, paz, paciência, benignidade, bondade, fidelidade, mansidão, domínio próprio." Paulo usa a palavra singular "fruto", não "frutos" — essas nove qualidades não são um buffet para escolher, mas um retrato unificado da vida de Cristo, desenvolvendo-se simultaneamente à medida que permanecemos na Videira. E o fruto é produzido, não fabricado. Você não pode grampear uvas em um ramo morto e chamá-lo de videira. Um líder não pode anexar bondade ou paz pela pura força de vontade. O fruto é o resultado orgânico de uma vida interior — não é algo que você faz, mas algo que acontece a você por causa de onde você está plantado.

Paulo chama esse ritmo de "andar pelo Espírito" — o que chamo de disciplina dependente. É nossa responsabilidade continuar andando, continuar nos posicionando na presença de Deus. Mas é o poder de Deus que fornece o passo. Não nos esforçamos para produzir o fruto. Nos esforçamos para permanecer na presença do Espírito que o faz crescer. E a pergunta honesta que todo líder deve responder é esta: quando as pessoas passam tempo ao meu redor, elas encontram o fruto do Espírito — amor, alegria, paz, paciência, mansidão? Ou encontram os sintomas do esforço — ansiedade, impaciência, irritabilidade, controle e o desespero silencioso de um líder que está funcionando nos vapores? O fruto não mente. É o diagnóstico mais preciso do que está acontecendo debaixo da superfície.

Quero encerrar este capítulo com a verdade que mantém todo o jardim unido. Antes de Jesus realizar um único milagre, antes de pregar um único sermão, antes de chamar um único discípulo, o Pai falou sobre Ele no Rio Jordão: "Este é o Meu Filho amado, em quem Me comprazo." Jesus não havia feito nada ainda. Não curou ninguém, não expulsou um único demônio, não ensinou uma única parábola, nem alimentou uma única multidão. E o Pai disse que já estava satisfeito. A aceitação veio antes da atividade. A identidade foi estabelecida antes do ministério começar.

Jesus não se esforçou para se tornar Filho. Ele liderou porque era Filho. Não trabalhou para conquistar a aprovação do Pai. Trabalhou a partir da aprovação do Pai. E tudo o que realizou nos três anos seguintes fluiu daquela identidade estabelecida e inabalável.

Lembro-me da estação em que essa verdade finalmente criou raízes na minha própria vida. Eu vinha pregando sobre graça por anos, mas vivia pela performance. Dizia à minha congregação que Deus os amava incondicionalmente e depois ia para casa e me julgava pelos números de frequência. A lacuna entre o que eu pregava e como eu vivia estava lentamente me destroçando. Foi somente quando me permiti estar no Rio Jordão — ouvir o Pai falar sobre mim não como pastor, não como líder, não como plantador de igrejas, mas como Seu filho — que o esforço começou a perder sua garra.

É aqui que o jardim começa, amigo. Não com um plano estratégico. Não com uma campanha de construção. Não com uma declaração de visão. Começa com você de pé no Rio Jordão e ouvindo o Pai dizer sobre sua vida: você é Meu amado. Estou satisfeito com você — não por causa do que você construiu, mas por causa de quem você é. Quando essa verdade se move da sua teologia para seus ossos, tudo muda. Você para de liderar a partir da ansiedade e começa a liderar a partir da abundância. Para de performar por aprovação e começa a servir a partir do transbordamento. Para de construir um reino para Deus e começa a cuidar do jardim que Ele já plantou. E o jardim começa a florescer.

"Permanecei em Mim, e Eu permanecerei em vós. Como o ramo não pode dar fruto de si mesmo, se não permanecer na videira, assim também vós não podeis, se não permanecerdes em Mim. Eu sou a videira; vós sois os ramos. Quem permanece em Mim e Eu nele, esse dá muito fruto; porque sem Mim nada podeis fazer." — João 15:4-5$conteudo$
    )
    returning id into v_aula_id;
  end if;

  if not exists (select 1 from public.atividades where aula_id = v_aula_id) then
    insert into public.atividades (aula_id, ordem, pergunta, tipo, razao) values
    (v_aula_id, 1,
     'O jardineiro aposentado disse: "Eu nunca grito com o tomate para crescer mais rápido." O autor admite que "gritava com o tomate" ao gerir a igreja como fábrica — controlando o que é domínio de Deus (resultados, timing, crescimento) e negligenciando o que é tarefa dele (cultivar o solo, guardar os portões). Onde, hoje, você tem gritado com o tomate?',
     'reflexao', null),
    (v_aula_id, 2,
     'Avad (servir/cultivar) e Shamar (guardar/proteger) eram a descrição de cargo de Adão — "não era CEO, não era visionário, não era construtor de plataformas". Olhando sua semana, quanto do seu tempo foi gasto tentando fazer o trabalho de Deus (forçar fruto) e quanto foi cuidar de verdade do solo das pessoas e do seu próprio coração?',
     'reflexao', null),
    (v_aula_id, 3,
     'Manhigut (conduzir o carro, força de vontade) x Parach (desabrochar, vida fluindo pela Fonte). E a vara morta de Arão floresceu só por ser posta na presença de Deus (Números 17). Em qual dos dois modos você tem operado — e qual das cinco mudanças (produção→presença, adrenalina→unção, hierarquia→família, escassez→abundância, crescimento forçado→ritmo sazonal) Deus está pedindo que você dê o primeiro passo?',
     'reflexao', null);
  end if;

end $migration$;
