-- Curso: Graça Livre (John Wesley) — slug graca-livre. Transcrição integral (PyMuPDF).
do $migration$
declare v_curso_id uuid; v_aula_id uuid; v_next_ordem int;
begin
  select id into v_curso_id from public.cursos where slug = 'graca-livre';
  if v_curso_id is null then
    select coalesce(max(ordem), 0) + 1 into v_next_ordem from public.cursos;
    insert into public.cursos (slug, titulo, descricao, imagem_url, is_pago, preco_centavos, categoria, ordem, publicado)
    values ('graca-livre','Graça Livre','Estudo a partir de Graça Livre, de John Wesley. Cada aula traz o texto na íntegra e, ao final, perguntas de reflexão para a sua caminhada com Deus.','/api/og/curso/graca-livre', false, 0, 'espiritual', v_next_ordem, true)
    returning id into v_curso_id;
  end if;

  select id into v_aula_id from public.aulas where curso_id = v_curso_id and ordem = 1;
  if v_aula_id is null then
    insert into public.aulas (curso_id, titulo, ordem, conteudo)
    values (v_curso_id, $t$Graça Livre$t$, 1,
$conteudo$“Aquele que nem mesmo a seu próprio Filho poupou, antes o entregou por todos nós, como não nos dará também com

” ele todas as coisas?

Romanos 8.32

1. Quão livremente Deus ama o mundo! Quando éramos ainda pecadores, “Cristo morreu pelos ímpios1.” Quando estávamos “mortos em nossos pecados,” Deus “nem mesmo a seu próprio Filho poupou, antes o entregou por todos nós.” E quão livremente com ele, ele “dá todas as coisas!” Verdadeiramente, a GRAÇA LIVRE é tudo em todos!

2. A graça ou amor de Deus, a fonte de nossa salvação, é LIVRE EM TODOS, e LIVRE PARA TODOS.

3. Primeiro. É livre EM TODOS a quem é dada. Não depende de qualquer poder ou mérito no homem; não, não em qualquer medida, nem no todo, nem em parte. Não depende de qualquer forma das boas obras ou da justiça do recebedor, nem de qualquer coisa que ele tenha feito, ou de qualquer coisa que ele é. Não depende de seus esforços. Não depende de sua boa disposição, ou bons desejos, ou bons propósitos e intenções; pois todas estas coisas fluem da livre graça de Deus; elas são apenas as correntes, não a fonte. Elas são os frutos da livre graça, e não a raiz. Elas não são a causa, mas os efeitos dela. Tudo de bom que esteja no homem, ou que seja feito pelo homem, Deus é o seu autor e doador. Dessa maneira é sua graça livre em todos; isto é, de nenhum modo dependendo de qualquer poder ou mérito no homem, mas em Deus somente, que livremente nos entregou seu próprio Filho, e “com ele livremente nos dá todas as coisas.”.

4. Mas é livre PARA TODOS, assim como EM TODOS. A isto alguns têm respondido, “Não: É livre somente para aqueles que Deus ordenou para a vida eterna; e eles são apenas em pequeno número. A maior parte Deus ordenou à morte eterna; e não é livre para eles. A esses Deus odeia; e, por isso, antes deles nascerem, decretou que eles devessem morrer eternamente. E isto ele absolutamente decretou; pois assim era seu beneplácito; pois era sua vontade soberana. Conseqüentemente, eles são nascidos para isto, - para ser destruídos corpo e alma no inferno. E eles crescem debaixo da irrevogável maldição de Deus, sem qualquer possibilidade de

4 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

redenção; quanto à graça que Deus dá, ele dá somente para isto, para aumentar, e não impedir, sua condenação.”

5. Este é aquele decreto da predestinação1. Mas, me parece, escuto alguém dizer, “Esta não é a predestinação que eu creio: Creio somente na eleição da graça. O que creio não é mais do que isto, - que Deus, antes da fundação do mundo, elegeu um certo número de homens para ser justificados, santificados, e glorificados. Agora, todos estes serão salvos, e ninguém mais; pois o resto da humanidade Deus deixa a si mesmos: Assim eles seguem as imaginações de seus próprios corações, que são apenas maus continuamente, e, tornando cada vez piores, são finalmente punidos com justiça com a destruição eterna.”

6. Esta é toda a predestinação que você crê? Pense mais um pouco; talvez não seja tudo. Você não crê que Deus os ordenou exatamente para isto? Se sim, você crê nisto; você afirma a predestinação no completo sentido que foi descrito acima. Mas pode ser que você ache que não. Você, então, não crê que Deus endurece os corações daqueles que perecem: Você não crê que ele (literalmente) endureceu o coração de Faraó; e que para este propósito ele o levantou, ou o criou? Ora, isto dá no mesmo. Se você acredita que Faraó, ou qualquer outra pessoa sobre a terra, foi criado para este fim, - ser condenado, - você afirma tudo o que foi dito a respeito da predestinação. E não há necessidade de você acrescentar que Deus suporta a condição dele, suposta ser inalterável e irresistível, ao endurecer os corações daqueles vasos da ira que esse decreto anteriormente os preparou para destruição.

7. Bem, mas pode ser que você não crê nem mesmo nisto; você não afirma nenhum grau de reprovação; você não acredita que Deus decreta que alguém seja condenado, nem que Ele endurece, nem que Ele irresistivelmente prepara-o, para a perdição; você somente diz, “Deus eternamente decretou que, todos estando mortos em pecados, ele diria a alguns dos ossos secos, Vivam, e a outros ele não diria; que, conseqüentemente, estes devem ser ressuscitados, e aqueles permanecer mortos, - estes glorificarão a Deus por sua salvação, e aqueles, por sua destruição.”

________________________________________ 1. Isto é, a predestinação segundo o Calvinismo.

5 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

8. Não é isto o que você quer dizer pela eleição da graça? Se for, eu farei uma ou duas perguntas: Alguém que não é eleito é salvo? Ou alguém foi salvo, desde a fundação do mundo? É possível que alguém seja salvo se não for eleito? Se você disser, “Não,” você não saiu do lugar; você não andou um milímetro; você ainda crê que, em conseqüência de um decreto imutável e irresistível de Deus, a maior parte da humanidade permanece morta, sem qualquer possibilidade de redenção; visto que ninguém pode salvá-los senão Deus, e ele não irá salvá-los. Você crê que ele absolutamente decretou não salvá-los; o que é isto senão decretar condená-los? É, de fato, nem mais nem menos; isto dá no mesmo; pois se você está morto, e completamente incapaz de ressuscitar a si mesmo, então, se Deus absolutamente decretou que ele ressuscitará somente os outros, e não você, ele absolutamente decretou sua morte eterna; você está absolutamente destinado à condenação. Então, embora você use palavras mais suaves do que alguns, você quer dizer a mesma coisa; e o decreto de Deus relativo à eleição da graça, de acordo com o seu relato, corresponde, nem mais nem menos, ao que outros chamam o decreto da reprovação de Deus.

9. Chame-o pelo nome que quiser, eleição, preterição, predestinação, ou reprovação, dá tudo no mesmo. O sentido de tudo é claramente isto, - em virtude de um eterno, imutável, irresistível decreto de Deus, uma parte da humanidade é infalivelmente salva, e o restante infalivelmente condenado; sendo impossível que alguns dos primeiros sejam condenados, ou que alguns dos últimos sejam salvos.

10. Mas se for assim, então toda pregação é vã. É inútil para aqueles que são eleitos; pois eles, com pregação ou sem, irão infalivelmente ser salvos. Por isso, o fim da pregação – salvar – é vão em relação a eles; e é inútil para aqueles que não são eleitos, pois eles não podem possivelmente ser salvos: Eles, com pregação ou não, serão infalivelmente condenados. O fim da pregação é, por essa razão, vão em relação a eles, da mesma forma; de modo que em qualquer caso nossa pregação é vã, como ouvi-la também é vão.

11. Isto, então, é uma clara prova de que a doutrina da predestinação1 não é uma doutrina de Deus, pois torna vã a ordenação de Deus; e Deus não está dividido contra si mesmo. Uma Segunda é, que ela diretamente tende a destruir a santidade, que é o fim de todas as ordenanças de Deus. Eu não estou dizendo que ninguém que a defende não é santo; (pois Deus é de afável misericórdia com aqueles que estão inevitavelmente envolvidos em

6 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

erros de qualquer espécie;) mas que a própria doutrina, - que todo homem, ou é eleito ou não é eleito desde a eternidade, e que um deve inevitavelmente ser salvo, e o outro inevitavelmente condenado, - tem uma tendência manifesta para destruir a santidade em geral; pois ela completamente elimina aqueles primeiros motivos para segui-la, tão freqüentemente propostos nas Escrituras, a esperança da recompensa futura e o medo da punição, a esperança do céu e o medo do inferno. Que estes irão para a punição eterna, e aqueles para a vida eterna, não é motivo para se esforçar pelo resto de sua vida aquele que crê que seu destino já está lançado; não é razoável a ele assim fazer, se ele pensa que está inalteravelmente ordenado para a vida ou para a morte. Você dirá, “Mas ele não sabe se é a vida ou a morte.” Quê! – isto não ajuda a questão; pois se um doente sabe que deve inevitavelmente morrer, ou inevitavelmente se recuperar, embora ele não saiba qual, é irracional ele tomar qualquer remédio. Ele poderia justamente dizer, (e assim escuto alguns falarem, tanto em doença física quanto espiritual,) “Se estou ordenado à vida, vou viver; se à morte, vou morrer; então eu não preciso me preocupar com isto.” Então, diretamente esta doutrina tende a fechar a própria porta da santidade, - a impedir homens não santos de aproximar dela, ou buscar entrar nela.

12. Assim como diretamente esta doutrina tende a destruir vários outros ramos da santidade. Tais como a humildade e o amor, - amor, eu quero dizer, de nossos inimigos, - dos maus e ingratos. Eu não estou dizendo que ninguém que a defende não tem humildade nem amor; (pois como é o poder de Deus, é sua misericórdia;) mas que ela naturalmente tende a inspirar, ou aumentar, uma impetuosidade ou impaciência de temperamento, que é totalmente contrária à humildade de Cristo; como então especialmente aparece, quando são contrariados neste assunto. E isto naturalmente inspira desprezo ou indiferença em relação àqueles que supomos serem rejeitados de Deus. “Ó, mas,” você diz, “Eu não suponho que ninguém seja um reprovado.” Você quer dizer que você não suporia se pudesse evitar: Mas você não pode deixar de algumas vezes aplicar sua doutrina geral a pessoas em particular: O inimigo das almas a aplicará por você. Você sabe o quão freqüentemente ele tem feito assim. Mas você rejeitou o pensamento com repugnância. Verdade; tão logo pôde; mas como exacerbou e estimulou seu espírito nessa hora! Você bem sabe que não foi o espírito de amor que depois sentiu por aquele pobre pecador, que você supôs ou suspeitou, querendo ou não, ter sido odiado de Deus desde a eternidade.

7 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

13. Em terceiro lugar. Esta doutrina tende a destruir o conforto da religião, a alegria do Cristianismo. Isto é evidente quanto àqueles que crêem que sejam reprovados, ou que somente suspeitam ou temem. Todas as grandes e preciosas promessas são perdidas para eles; elas não lhes proporcionam nenhum raio de conforto: Pois eles não são os eleitos de Deus; por isso eles não têm nenhuma parte nem porção nelas. Esta é uma barreira eficaz para que eles encontrem algum conforto ou felicidade, mesmo na religião cujos caminhos são objetivados ser “caminhos de delícias, e todas as suas veredas de paz”.

14. E quanto a vocês que crêem que são os eleitos de Deus, qual é sua felicidade? Espero, não uma noção, uma crença especulativa, uma mera opinião de qualquer espécie; mas uma posse ardente de Deus em seu coração, trabalhada em você pelo Espírito Santo, ou, o testemunho do Espírito de Deus com o seu espírito que você é um filho de Deus. Isto, de outra forma chamado “uma inteira certeza de fé,” é o verdadeiro fundamento da felicidade de um cristão. E isto de fato implica numa inteira certeza de que todos os seus pecados passados são perdoados, e que você agora é um filho de Deus. Mas isto não necessariamente implica numa inteira certeza de nossa futura perseverança. Eu não estou dizendo que esta nunca é ligada àquela, mas que não é necessariamente implicado nela; pois muitos têm uma que não têm a outra.

15. Agora, este testemunho da experiência do Espírito demonstra ser muito obstruído por esta doutrina, e não somente naqueles que, crendo que sejam reprovados, por esta crença lançamna para longe deles, mas até naqueles que têm experimentado dessa boa dádiva, que todavia a perderam novamente, e caíram de volta na dúvida, e temores, e escuridão, - escuridão horrível, que poderia ser sentida! E eu apelo a qualquer um de vocês que crêem nesta doutrina, dizer, entre Deus e seus próprios corações, se têm freqüentemente voltado dúvidas e temores sobre sua eleição ou perseverança! Se perguntarem, “Quem não tem?” Eu respondo, Muito pouco daqueles que crêem nesta doutrina; mas muitos, muitos mesmos, daqueles que não crêem nela, em todas as partes da terra; - muitos destes têm desfrutado o ininterrupto testemunho de seu Espírito, a luz contínua de sua duração, do momento em que primeiro creram, por muitos meses ou anos, até este dia.

16. Essa certeza de fé que estes desfrutam exclui toda dúvida e medo. Exclui todos os tipos de dúvida e medo sobre sua perseverança futura; embora não seja propriamente, como foi dito

8 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

antes, uma certeza do que é futuro, mas somente do que é agora. E esta não precisa para seu apoio uma crença especulativa, que uma vez que alguém é ordenado à vida deve viver; pois ela é trabalhada de hora em hora, pelo imenso poder de Deus, “pelo Espírito Santo que lhes foi dado.” E por essa razão essa doutrina não é de Deus, pois ela tende a obstruir, se não destruir, esta grande obra do Espírito Santo, de onde flui o principal conforto da religião, a felicidade do Cristianismo.

17. Novamente: Quão desagradável pensamento é este, que milhares e milhões de homens, sem qualquer ofensa ou falta precedente, foram irremediavelmente condenados ao fogo eterno! Quão peculiarmente desagradável deve ser para aqueles que têm confiado em Cristo! Para aqueles que, estando cheios de entranhas de misericórdias, ternura, e compaixão, poderiam até “desejar ser separados de Cristo, por amor de seus irmãos”.

18. Em quarto lugar. Esta desagradável doutrina diretamente tende a destruir nosso zelo pelas boas obras. E isto ela faz, Primeiro, visto que naturalmente tende (de acordo com o que foi observado antes) destruir nosso amor pela maior parte da humanidade, a saber, os maus e os ingratos. Pois o que quer que diminua nosso amor, deve também diminuir nosso desejo de lhes fazer o bem. Isto ela faz, Segundo, visto que elimina um dos motivos mais fortes para todos os atos de misericórdia material, como alimentar o faminto, vestir o nu, e coisas semelhantes, - a saber, a esperança de salvar suas almas da morte. Pois em que ajuda essa doutrina aliviar as necessidades temporais de quem está caindo no fogo eterno? “Bem; mas corra e arrebata-os como brasas do fogo.” Não, isto você supõe ser impossível. Eles foram apontados para lá, você diz, da eternidade, antes que tivessem feito bem ou mal. Você crê que é da vontade de Deus que eles morram. E “quem resiste à sua vontade?” Mas você diz que você não sabe se estes são eleitos ou não. O que então? Se você sabe que eles são um ou outro, - que eles são eleitos ou não eleitos, - todo seu trabalho é inútil e vão. Em qualquer caso, seu conselho, repreensão, ou exortação é tão desnecessário e inaproveitável quanto nossa pregação. É desnecessário para aqueles que são eleitos; pois eles infalivelmente serão salvos sem ele. É inaproveitável para aqueles que não são eleitos; pois com ou sem ele eles infalivelmente serão condenados; por essa razão você não pode, consistentemente com seus princípios, se esforçar pela salvação deles. Conseqüentemente, esses princípios diretamente tendem a destruir seu zelo pelas boas obras; por todas as boas obras; mas particularmente pela maior delas, salvar as almas da morte.

9 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

19. Mas, Quinto, esta doutrina não somente tende a destruir a santidade cristã, a alegria, e as boas obras, mas tem também uma tendência direta e manifesta de subverter toda a Revelação Cristã. O ponto que o mais sábio dos modernos incrédulos mais diligentemente trabalha para provar é que a Revelação Cristã não é necessária. Eles bem sabem que, pudessem uma vez demonstrarem isto, a conclusão seria clara demais para ser negada, “Se não é necessário, não é verdadeiro.” Agora, este ponto fundamental você abandona. Pois, supondo o decreto eterno, imutável, uma parte da humanidade deve ser salva, ainda que a Revelação Cristã não estivesse presente, e a outra parte da humanidade deve ser condenada, apesar dessa Revelação. E o que um pagão desejaria mais? Permitir tudo que ele pede. Ao fazer o evangelho desnecessário para todos os tipos de homens, você abandona toda a causa cristã. “Não o noticieis em Gate para que não exultem as filhas dos incircuncisos;” para que não triunfem os filhos da incredulidade!

20. E como esta doutrina manifesta e diretamente tende a subverter toda a Revelação Cristã, a mesma coisa ela faz, por evidente conseqüência, ao fazer a Revelação contradizer-se. Pois ela está fundamentada em tal interpretaçao de alguns textos (mais ou menos, isto não interessa) que categoricamente contradiz todos os outros textos, e de fato toda a extensão e tendência geral da Escritura. Por exemplo: Os defensores desta doutrina interpretam esse texto da Escritura, “Amei a Jacó, e odiei a Esaú,” como significando que Deus literalmente odiou a Esaú, e todos os reprovados, desde a eternidade. Agora, o que pode possivelmente ser uma contradição mais clara do que esta, não somente a toda a extensão e tendência geral da Escritura, mas também a todos aqueles textos particulares que expressamente declaram, “Deus é amor”? Novamente: Ele inferem desse texto, “Terei misericórdia de quem me aprouver ter misericórdia,” (Rm 9.15) que Deus é amor somente a alguns homens, a saber, os eleitos, e que ele tem misericórdia deles apenas; claramente contrário à tendência geral da Escritura, como é aquela declaração expressa em particular, “O Senhor é bom para todos, e as suas misericórdias estão sobre todas as suas obras.” (Sl 145.9) Novamente: Eles inferem desse e de outros textos semelhantes, “Isto não depende do que quer, nem do que corre, mas de Deus que usa de misericórdia,” (Rm 9.16) que ele demonstra misericórdia somente àqueles a quem ele tinha estimado desde toda eternidade. Não, mas quem a Deus replica agora? Você agora contradiz todos os oráculos de Deus, que declaram

10 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

completamente, “Deus não faz acepção de pessoas;” (At 10.34) “Para com Deus não há acepção de pessoas.” (Rm 2.11) Novamente: desse texto, “Não tendo os gêmeos ainda nascido, nem praticado bem ou mal, para que o propósito de Deus segundo a eleição permanecesse firme, não por causa das obras, mas por aquele que chama, foi-lhe dito,” a Rebeca, “O maior servirá o menor;” você infere que ser predestinado ou eleito de forma alguma depende do pré-conhecimento de Deus. Claramente contrárias a isto são todas as escrituras; e essas em particular, “Eleitos segundo a presciência de Deus Pai;” (1Pe 1.2) “Os que dantes conheceu, também os predestinou.” (Rm 8.29)

21. E “o mesmo Senhor o é de todos, rico” em misericórdia “para com todos os que o invocam:” (Rm 10.12:) Mas você diz, “Não; ele é assim somente para aqueles por quem Cristo morreu. E esses não são todos, mas somente alguns, que Deus escolheu do mundo; pois ele não morreu por todos, mas somente por aqueles que foram ‘eleitos nele antes da fundação do mundo.’” (Ef 1.4.) Completamente contrária à sua interpretação destas escrituras, também, está toda a tendência do Novo Testamento; como são em particular esses textos: - “Não faças perecer por causa da tua comida aquele por quem Cristo morreu,” (Rm 14.15,) – uma clara prova de que Cristo morreu, não somente por aqueles que são salvos, mas também por aqueles que perecem: Ele é “o Salvador do mundo;” (Jo 4.42;) Ele é “o Cordeiro de Deus, que tira o pecado do mundo;” (Jo 1.29;) “Ele é a propiciação pelos nossos pecados, e não somente pelos nossos, mas também pelos de todo o mundo;” (1Jo 2.2;) “Ele,” o Deus vivo, “é o Salvador de todos os homens;” (1Tm 4.10;) “O qual se deu a si mesmo em resgate por todos;” (1Tm 2.6;) “Ele provou a morte por todos.” (Hb 2.9)

22. Se você perguntar, “Então por que todos os homens não são salvos?” toda a lei e o testemunho respondem, Primeiro, Não por causa de qualquer decreto de Deus; nem porque é seu prazer que eles devessem morrer; pois, “Vivo eu, diz o Senhor Deus,” “não tenho prazer na morte de ninguém.” (Ez 18.3, 32.) Qualquer que seja a causa de seu perecimento, não pode ser sua vontade, se os oráculos de Deus forem verdadeiros; pois eles declaram, “O Senhor não quer que ninguém se perca, senão que todos venham a arrepender-se;” (2Pe 3.9;) “Ele quer que todos sejam salvos.” E eles, Segundo, declaram o que é a causa de todos os homens não serem salvos, a saber, que eles não serão salvos: Assim nosso Senhor expressamente, “Não quereis vir a mim para terdes vida.” (Jo 5.40.) “O poder do Senhor estava com ele para curá-los,” mas eles

11 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

não serão curados. “Eles rejeitam o conselho,” o misericordioso conselho, “de Deus contra si mesmos,” como fizeram seus obstinados antepassados. E por isso eles são inexcusáveis; porque Deus salvá-los-ia, mas eles não serão salvos: Esta é a condenação, “Quantas vezes quis eu ajuntá-los, e não o quiseste!” (Mt 23.37.)

23. Dessa forma, manifestamente, esta doutrina tende a arruinar toda a Revelação Cristã, fazendo-a contradizer-se; dando tal interpretação de alguns textos que completamente contradiz todos os outros textos, e na verdade todo o alvo e tendência da Escritura; - uma prova abundante de que não é de Deus. Mas ainda não é tudo: Pois, Sétimo, é uma doutrina cheia de blasfêmia; de tal grandeza que eu temo mencionar, mas que a honra de nosso gracioso Deus, e a causa de sua verdade, não permitirá que eu fique em silêncio. Pela causa de Deus, então, e de uma preocupação sincera pela glória de seu grande nome, mencionarei algumas das horríveis blasfêmias contidas nesta horrível doutrina. Mas, primeiro, devo alertar a todos que me ouvem, haja vista que irão responder no grande dia, não me acusar (como alguns têm feito) de blasfemar por mencionar a blasfêmia dos outros. E quanto mais vocês se ofendem com aqueles que assim blasfemam, vejam que “confirmem o seu amor por eles:” mais, e que o desejo de seu coração, e contínua oração a Deus, seja, “Pai, perdoa-lhes; porque eles não sabem o que fazem!”

24. Isto estabelecido, deve ser observado que esta doutrina representa nosso abençoado Senhor, “Jesus Cristo o justo,” “o unigênito Filho do Pai, cheio de graça e verdade,” como um hipócrita, um enganador, um mentiroso. Pois não pode ser negado que ele, em todo o lugar, fala como se estivesse desejando que todos os homens sejam salvos. Por isso, dizer que ele não estava desejando que todos os homens sejam salvos é representá-lo como um mero hipócrita e dissimulador. Não pode ser negado que as graciosas palavras que partiram de sua boca são repletas de convites a todos os pecadores. Dizer, então, que ele não pretendia salvar todos os pecadores é representá-lo como um flagrante enganador das pessoas. Ninguém pode negar que ele diz, “Vinde a mim, todos os que estais cansados e oprimidos.” Se, então, você diz que ele chama aqueles que não podem vir; aqueles que ele sabe ser incapazes de vir; aqueles que ele pode capacitá-los a vir, mas não os capacitará; como é possível descrever maior insinceridade? Você o representa como zombando de suas criaturas abandonadas, oferecendo o que ele nunca pretende dar. Você descreve-o como dizendo uma coisa e querendo dizer outra; como fingindo o amor que não teve. Ele, em “cuja boca não se achou engano,” você torna cheia de falsidade, de

12 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

insinceridade; - então especialmente, quando, aproximando-se da cidade, Ele chorou por ela, e disse, “Jerusalém, Jerusalém, que matas os profetas, apedrejas os que a ti são enviados! quantas vezes quis eu ajuntar os teus filhos, como a galinha ajunta os seus pintos debaixo das asas, e não o quiseste;” καὶ οὐκ ἠθελήσατε. Agora, se você disser, eles queriam, mas ele não queria, você o representa (quem poderia ouvir?) como chorando lágrimas de crocodilo; chorando sobre a presa que ele mesmo condenou à destruição!

25. Que blasfêmia esta, como alguém pensaria que poderia fazer tinir os ouvidos de um cristão! Mas ainda há mais coisas por trás; pois como ela honra o Filho, da mesma forma esta doutrina honra o Pai. Ela destrói todos seus atributos de uma só vez: Ela destrói sua justiça, misericórdia, e verdade; sim, ela representa o mais santo Deus como pior do que o diabo, como mais falso, mais cruel, e mais injusto. Mais falso; porque o diabo, mentiroso como é, nunca disse que “deseja que todos os homens sejam salvos:” Mais injusto; porque o diabo não pode, se quisesse, ser culpado de tal injustiça que você atribui a Deus, quando diz que Deus condenou milhões de almas ao fogo eterno, preparado para o diabo e seus anjos, por continuarem no pecado, que, por falta daquela graça que ele não lhes dará, eles não podem evitar: E mais cruel; porque esse espírito infeliz “busca repouso e não encontra nenhum;” para que sua própria miséria impaciente seja uma espécie de tentação para que ele tente os outros. Mas Deus repousa em seu elevado e santo lugar; de modo que supor que ele, de seu próprio impulso, de sua pura vontade e prazer, feliz como ele é, condenar suas criaturas, se desejam ou não, à miséria sem fim, é atribuir tamanha crueldade a ele como não podemos atribuir até mesmo ao grande inimigo de Deus e do homem. É representar o grande Deus (aquele que tem ouvidos para ouvir ouça!) como mais cruel, falso, e injusto do que o diabo!

26. Esta é a blasfêmia claramente contida no decreto horrível da predestinação! E aqui eu fixo meu pé. Sobre isto eu discuto a opinião de quem a afirme. Você representa Deus como pior do que o diabo; mais falso, mais cruel, mais injusto. Mas você diz que irá prová-la pela escritura. Espere! O que você irá provar pela Escritura? Que Deus é pior do que o diabo? Não pode ser. O que quer que a Escritura prove, ela nunca prova isto; qualquer que seja seu verdadeiro significado, este não pode sê-lo. Você quer saber, “Qual é seu verdadeiro significado então?” Se eu disser, “Eu não sei,” você não ganhou nada; pois há muitas escrituras que o verdadeiro sentido

13 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

delas nem você nem eu saberá até que a morte seja tragada na vitória. Mas de uma coisa eu sei, melhor fosse dizer que não tivesse sentido nenhum do que dizer que tem tal sentido como este. Não pode significar, o que quer que signifique, que o Deus da verdade seja um mentiroso. Não pode significar que o Juiz de todo o mundo seja injusto. Nenhuma escritura pode signifcar que Deus não seja amor, ou que sua misericórdia não seja sobre todas as suas obras; isto é, o que quer que ela prova, nenhuma escritura pode provar a predestinação.

27. Esta é a blasfêmia pela qual (apesar de amar as pessoas que a afirmam) eu abomino a doutrina da predestinação, uma doutrina, sob a suposição de que, se alguém pudesse possivelmente supô-la por um instante, (chame-a eleição, reprovação, ou o que quiser, pois dá tudo na mesma,) alguém poderia dizer ao nosso adversário, o diabo, “Seu idiota, por que você continua rugindo? Sua espera por almas é tão desnecessária e inútil quanto nossa pregação. Não está sabendo que Deus tirou o trabalho de suas mãos; e que ele faz isto muito mais eficientemente? Você, com todos os seus principados e potestades, pode somente atacar que podemos resistir a você; mas Ele pode irresistivelmente destruir corpo e alma no inferno! Você pode apenas incitar; mas seus imutáveis decretos, para deixar milhares de almas na morte, compele-os a continuar no pecado, até que desçam às profundezas do fogo eterno. Você tenta; Ele nos força a ser condenados; pois não podemos resistir sua vontade. Seu tolo, por que anda em derredor, buscando a quem possa tragar? Não ouviu que Deus é o leão devorador, o destruidor das almas, o assassino dos homens? Moloque fazia somente as crianças passarem pelo fogo: e aquele fogo logo foi extinto; ou, o corpo corruptível sendo consumido, seu tormento acabava; mas Deus, fique sabendo, por seu eterno decreto, fixado antes que eles fizessem bem ou mal, causa, não somente que crianças pequeninas, mas que os pais também, passem pelo fogo do inferno, o ‘fogo que nunca se apaga;’ e o corpo que é para lá lançado, sendo agora incorruptível e imortal, estará sempre consumindo mas nunca será consumido, mas ‘a fumaça de seu tormento,’ porque foi do beneplácito de Sua vontade, ‘sobe para todo o sempre.’”

28. Ó, como iria se regozijar o inimigo de Deus e do homem ao ouvir que estas coisas foram assim! Como ele gritaria alto, com toda a sua força! Como ele levantaria sua voz e diria, “Às suas tendas, Ó Israel! Fugi da face deste Deus, ou completamente perecereis! Mas para onde fugireis? Para o céu? Ele está lá. Para o inferno? Ele também está lá. Vós não podeis fugir de um tirano onipresente e

14 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

todo-poderoso. E para onde fugirdes ou ficardes, eu chamarei o céu, seu trono, e a terra, o escabelo de seus pés, para testemunhar contra vós, e perecereis e morrereis eternamente. Cante, Ó inferno, e regozijeis, vós que estais debaixo da terra! Pois Deus, o próprio Deus todo-poderoso, tem falado, e condenado à morte milhares de almas, do nascer ao pôr do sol! Aqui, Ó morte, o seu aguilhão! Eles não fugirão nem podem fugir; pois a boca do Senhor tem falado. Aqui, Ó sepultura, sua vitória. Nações ainda não nascidas, antes de terem feito bem ou mal estão destinadas a nunca ver a luz da vida, mas tu irás consumi-las para todo sempre! Deixais todas as estrelas da manhã cantarem juntas, que caíram com Lúcifer, filho da manhã! Deixais todos os filhos do inferno exultarem de alegria! Pois o decreto já foi feito, e quem poderá anulá-lo?”

29. Sim, o decreto já foi feito; e aconteceu antes da fundação do mundo. Mas que decreto? Certamente este: “Eu colocarei diante dos filhos dos homens ‘a vida e a morte, a benção e a maldição.’ E a alma que escolher a vida viverá, assim como a alma que escolher a morte morrerá.” Este decreto pelo qual “os que dantes conheceu, também os predestinou,” foi de fato desde a eternidade; este, pelo qual todos que permitem Cristo vivificá-los são “eleitos segundo a presciência de Deus Pai,” agora resistem, assim como a lua, e como as testemunhas fiéis no céu; e quando o céu e a terra passar, todavia isto não passará; pois é tão imutável e eterno quanto o ser de Deus que o deu. Este decreto produz o mais vigoroso encorajamento para abundar em todas as boas obras e em toda santidade; e é uma fonte de júbilo, de felicidade também, para nosso bem-estar maior e eterno. Isto é digno de Deus; é de todas as formas consistente com todas as perfeições de sua natureza. Nos dá a concepção mais nobre de sua justiça, misericórdia, e verdade. Com isto concorda toda a extensão da Revelação Cristã, assim como todas as suas partes. Tem o testemunho de Moisés e de todos os profetas, e de nosso abençoado Senhor e de todos os seus apóstolos. Assim Moisés, em nome de seu Senhor: “O céu e a terra tomo hoje por testemunhas contra ti de que te pus diante de ti a vida e a morte, a bênção e a maldição; escolhe, pois, a vida, para que vivas, tu e a tua descendência.” Assim Ezequiel: (para citar um profeta por todos:) “A alma que pecar, essa morrerá; o filho não levará” eternamente, “a iniquidade do pai. A justiça do justo ficará sobre ele, e a impiedade do ímpio cairá sobre ele.” (Ez 18.20) Assim nosso abençoado Senhor: “Se alguém tem sede, venha a mim e beba.” (Jo 7.37.) Assim seu grande apóstolo, São Paulo: (At 17.30:) “Deus manda agora que todos os homens em todo lugar se arrependam;” – “todos os

15 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

homens em todo lugar;” todo homem em qualquer lugar, sem exceção de lugar ou pessoa. Assim São Tiago: “Se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não censura, e ser-lhe-á dada.” (Tg 1.5.) Assim São Pedro: (2Pe 3.9:) “O Senhor não quer que ninguém se perca, senão que todos venham a arrepender-se.” E assim São João: “Se alguém pecar, temos um Advogado para com o Pai; e ele é a propiciação pelos nossos pecados, e não somente pelos nossos, mas também pelos de todo o mundo.” (1Jo 2.1-2.)

30. Ouçam vocês isto, vocês que se esquecem de Deus! Vocês não podem atribuir sua morte a ele! “‘Tenho eu algum prazer na morte do ímpio?’ diz o Senhor Deus.” (Ez 18.23ff.) “Vinde, e convertei-vos de todas as vossas transgressões, para que a iniqüidade não vos leve à perdição. Lançai de vós todas as vossas transgressões que cometestes contra mim, - pois, por que morrereis, ó casa de Israel? Porque não tenho prazer na morte de ninguém, diz o Senhor Deus; convertei-vos, pois, e vivei.” “Vivo eu, diz o Senhor Deus, que não tenho prazer na morte do ímpio. - Convertei-vos, convertei-vos dos vossos maus caminhos; pois, por que morrereis, ó casa de Israel?” (Ez 33.11.).

16 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

SOBRE O AUTOR

John Wesley nasceu em 1703, durante o reinado da boa rainha Anne. Sua infância foi dirigida por sua mãe, uma mulher rígida e piedosa e seu pai, um homem difícil de agradar. Sua mãe acreditava que os desejos das crianças deviam ser subjugados, que eles deveriam ser açoitados quando não se comportassem e que deviam chorar baixinho depois de açoitados. John era o décimo quarto filho. Ele teria morrido num incêndio em Epworth Rectory se não tivesse sido arrancado das chamas por um vizinho que subiu nos ombros de outro vizinho. Ele tinha sete anos então, e depois disso, sua mãe o lembrou várias vezes que ele era “um tição colhido do fogo”. Ela sentia – e mais tarde ele veio a sentir – que ele tinha sido poupado por um propósito, servir a Deus.

Samuel, o pai de John, era um erudito, que por muitos anos trabalhou numa obra monumental sobre o livro de Jó. Um pregador severo, para não dizer implacável, uma vez exigiu que uma adúltera andasse nas ruas em sua vergonha e ele forçou o casamento de uma de suas filhas depois que ela tentou fugir com um homem que não era o escolhido de seu pai. Com seu pai e sua mãe, John Wesley desenvolveu excelentes hábitos de estudo e também se acostumou com sofrimento físico.

John Wesley foi para Charterhouse School em 1714, para Christ Church College, Oxford, em 1720, e em 1726 foi eleito membro na Lincoln College, Oxford. Depois de aceitar uma posição de pastor auxiliar em Wroote, Lincolnshire, de 1727 a 1729, ele voltou à Oxford não apenas para continuar seus estudos, mas também começar a viver a vida santa. Muitos outros jovens brilhantes tinham um curriculum como o de Wesley, mas poucos tinham a sua dedicação. Ele dominava pelo menos sete idiomas e desenvolveu uma visão verdadeiramente abrangente em todas as áreas da investigação. Sua mente nunca encerrou a busca pelo resto de sua vida. Quando ele voltou de Wroote para Oxford, ele assumiu a liderança de um grupo chamado Holy Club (Clube Santo), iniciado por seu irmão Charles. Aqui, eles buscavam reforçar a fé através do estudo das Escrituras e medindo a qualidade da santidade da vida de cada membro.

O Holy Club fazia mais que pensar e orar. Eles foram às prisões levar salvação aos prisioneiros. Embora eles fossem ridicularizados por seus companheiros de Oxford, de seu grupo de baixa posição saíram homens que se tornaram importantes para

17 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

aquele tempo, particularmente os irmãos Wesley e George Whitefield. O seu regime exigia jejuns periódicos, encontros regulares para estudo e auto-exame. Somente muito tempo depois foi que John Wesley percebeu que eles seguiam mais a letra do que o espírito do cristianismo.

Em 1735 grandes mudanças atingiram John e Charles Wesley. O seu pai morreu e ambos foram com o governador Ogilthorpe para a colônia Georgia com a bênção e encorajamento de sua mãe. A Georgia foi uma prova para John, que logrou que realmente não gostava dos índios e que sua rigidez não era muito apreciada pelas pessoas da Georgia. Mas importante que isto, foi o contato de John com uma pequena banda de morávios na viagem para a colônia. Estes homens e mulheres destemidamente cantavam hinos durante terríveis tempestades no mar, enquanto ele se desesperava. Ele queria conhecer a fé que eles pareciam ter. Em 1737 ele retornou à Inglaterra.

Devemos dar a John Wesley o crédito, pois ele podia ser crítico o bastante consigo mesmo para parar naquele momento e saber que ele era um ministro experiente para examinar sua falta de fé. Peter Boehler, um morávio, deu-lhe a chave – pregar a fé até que ele a tivesse, e então ele pregava a fé. Então aconteceu que John Wesley habitou na fé até 24 de maio, uma quarta-feira, em 1738, no famoso encontro de Aldersgate, ele teve uma conversão, uma profunda e inconfundível experiência de fé. Seu “coração foi estranhamente aquecido”. Então seu verdadeiro trabalho começou.

Como tinha uma mente livre, John Wesley ainda conseguia retirar os melhores recursos das melhores mentes do seu tempo. William Law, por exemplo, foi seu professor, amigo e mentor por vários anos; mas Wesley achou que um ingrediente importante estava faltando no programa de Law para uma vida devota. Os seguidores de Platão conseguiram comunicar a Wesley uma estrutura intelectual que era mais espiritual do que material, mas os hábitos mentais de Wesley estavam moldados tanto pelo modelo de análise de Newton do que pelo platonismo. Os morávios eram o mais perto de uma síntese de todos os elementos que ele desejava e pôde encontrar. Ele até mesmo visitou Herrnhut para saber como sua comunidade trabalhava. Mas algo estava faltando lá, como em todo lugar, e em 1740, ele e seus seguidores romperam com os morávios, mas não antes que ele tivesse aprendido a pregar sermões ao ar livre, o que veio a ser uma parte essencial de seu programa mais tarde.

18 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

John Wesley tinha 37 anos de idade quando começou a viajar e pregar. Ele freqüentemente exagerava o número daqueles que vinham ouvi-lo. Muitas vezes, as mesmas pessoas que precisaram de sua ajuda eram as mesmas que mais o perseguiam. Ele pregava em púlpitos até que eles fossem fechados para ele, e ele então pregava nos campos abertos. Ele pregava três vezes por dia, começando às 5 da manhã, uma vez que os trabalhadores poderiam parar para ouvilo enquanto andavam para o seu trabalho monótono.

Algumas vezes ele andava 60 milhas (90 quilômetros) por dia a cavalo. As condições do tempo não importavam; ele fazia seu horário e o cumpria, não importavam as dificuldades. Ele fugia de uma multidão zangada pulando num lago gelado, nadava para fora dele e continuava a pregar novamente. Ele tinha a habilidade de trazer as pessoas hostis para o seu lado.

Ele foi para Gales do Sul em 1741, para o norte da Inglaterra em 1742, Irlanda em 1747, e Escócia em 1751. No total, ele foi à Irlanda quarenta e duas vezes e à Escócia vinte e duas vezes. Ele retornou às cidades vezes e mais vezes. Houve ocasiões em que ele retornava anos depois de sua última visita e registrava que a pequena sociedade que ele ajudara ainda estava intacta e fiel. Ele examinava cada membro de cada sociedade pessoalmente para buscar crescimento espiritual e de fé. As sociedades então formadas proviam a organização local para seu movimento.

Durante 53 anos de um ministério incansável, Wesley chamou a si mesmo de "homem de um livro só" — a Bíblia. Ele escreveu, todavia, mais de 200 livros, editou uma revista, compilou dicionários em quatro línguas — tudo escrito a mão. Ele percorreu a Inglaterra a cavalo, num total de 250.000 milhas. Durante anos, fez uma média de 20 milhas diárias e muitas vezes andava 50 a 60 e até mais milhas por dia, parando para pregar ao longo do caminho. Ele pregou 40.000 sermões — raramente menos que dois por dia e às vezes sete, oito ou até mais.

O que Wesley pregava? Frugalidade, limpeza, honestidade, salvação, boas relações familiares, dúzias de outros temas, mas acima de tudo, a fé em Cristo. Ele não pedia aos seus ouvintes para deixarem suas igrejas, mas para continuarem indo nelas. Ele lhes deu o refrigério espiritual que eles não achavam fora do círculo. Quando suas décadas de provação produziram décadas de triunfo, as

19 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

multidões aumentaram. Ricos e pobres vinham para ouvi-lo falar. Ele desenvolveu redes de assistentes leigos. Suas exortações para viver perfeitamente em amor hoje parecem duras, mas considere os efeitos em suas congregações. Os xingamentos nas fábricas pararam, os homens e as mulheres começaram a se preocupar com vestimentas limpas e simples, extravagâncias como chá caro e vícios como o gim foram deixados por seus seguidores, vizinhos deram um ao outro ajuda mútua através das sociedades.

Wesley ensinou tanto pelo exemplo como pelos seus sermões tão medidos. Suas despesas anuais já foram mencionadas. Ele publicou muitos volumes para serem usados em devocionais e direcionou o lucro para projetos, como um local de ajuda para os pobres. Sua vida pessoal estava além de reprovação. Ele traduziu hinos, interpretou as Escrituras, escreveu centenas de cartas, treinou centenas de homens e mulheres e manteve em seus diários um registro da energia dispensada, que dificilmente tem um rival na literatura ocidental. Sua maneira de falar na linguagem do homem comum teve um impacto imensurável no surgimento do inglês moderno, assim como os hinos de Charles Wesley tiveram um grande impacto na música com suas muitas canções sem mencionar a poesia da subseqüente era Romântica.

Mas o impacto dos Wesleys nas classes mais baixas foi além de afetar seus hábitos de vida e modo de falar. John Wesley proveu uma estrutura religiosa que era local e pessoal, bem como energeticamente moral. Sua teologia não tirava a liberdade e o direito de ninguém, pois qualquer um podia achar a graça de Deus para resistir ao diabo e ser salvo, se tão somente buscasse e recebesse. As sociedades que ele formou preservaram em seus estudos um foco de fé – uma fé que também levou a uma maneira de lidar com a realidade da vida das classes mais pobres. A religião não era só para os ricos, mas Wesley também não estava pregando uma revolta contra o anglicanismo – até muito tarde e então quase por um acidente histórico.

O anglicanismo de John Wesley era muito forte, embora os púlpitos anglicanos tornassem-se universalmente fechados a ele. Só quando tinha oitenta e um anos ele permitiu uma pequena divisão entre seus seguidores e a igreja nacional. Tendo mandado muitos homens à América, em 1784 ele ordenou mais pessoas para este esforço missionário e, porque “ordenação é separação”, efetivamente começou uma nova igreja. O conservadorismo dele era tanto político como religioso. Ele publicou uma carta aberta às colônias

20 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

americanas, aconselhando-as a permanecerem leais à Grã-Bretanha, logo antes da Revolução Americana. Ele não tolerava nenhuma conversa sobre agitação civil na Inglaterra.

Tem se discutido que outras forças estavam trabalhando na Inglaterra além de Wesley e uns outros poucos pregadores. Por exemplo, a Revolução Industrial que estava vindo progrediu mais rápido na Inglaterra do que em qualquer outro lugar, dando aos homens novos tipos de trabalho; a justiça do Sistema de Paz e o sistema de governo com um Primeiro-Ministro eram únicos na sua forma e deram muito mais poder do que era possível em qualquer outro lugar à classe média local e os grandes problemas, que poderiam, de outra forma, causar revolução, simplesmente não estavam presentes depois de 1750. Ainda assim, sem Wesley e seus seguidores, como poderia o ateísmo, tal como existia entre os camponeses franceses, ser evitado e como poderia uma classe inferior oprimida e dominada pelos vícios ter esperança?

John Wesley morreu em 2 de março de 1791, cerca de três anos depois que seu irmão Charles morreu. Até seus anos finais, ele fez a mesma frase de abertura em seu diário a cada ano no seu aniversário, agradecendo a Deus por sua longa vida e sua contínua boa saúde, afirmando que sermões pregados de manhã cedo e muita atividade ao ar livre o mantiveram em forma para a obra de Deus. Desde o momento em que ele tornou-se livre de influências, exceto a de Deus, ele teve cinqüenta anos de serviço constante e fez um bem imensurável à Inglaterra através da perseverança, resistência e fé. Seu legado não se limitou ao seu século ou país, mas sobrevive até hoje na fé de milhões em uma variedade de igrejas.

A seguinte frase foi escrita em seu diário em 28 de junho de 1774:

Sendo hoje meu aniversário, o primeiro dia do septuagésimo segundo ano, eu estava pensando, Como pode ser isso, que eu ache a mesma força que tinha trinta anos atrás? Que a minha vista esteja consideravelmente melhor agora, e meus nervos mais firmes do que eram antes? Que eu não tenha nenhuma enfermidade da velhice, e não tenha mais aquelas que tive na juventude? A grande causa é, o bom prazer de Deus, que faz o que lhe agrada. Os meios principais são: meu constante levantar às quatro da madrugada, por cerca de cinqüenta anos; o fato de geralmente pregar às cinco da manhã, um dos exercícios mais saudáveis do mundo; o fato de

21 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”

que nunca viajo menos, por mar ou terra, do que 4500 milhas (6.750 km) por ano.

Referências da Biografia: Christianity Today International – 2008

Wesley Dwel - Em Chamas para Deus

22 Projecto Wesley “GRAÇA LIVRE EM TODOS E PARA TODOS”$conteudo$)
    returning id into v_aula_id;
    insert into public.atividades (aula_id, ordem, pergunta, tipo, razao) values

    (v_aula_id, 1, $p$Se a graça que te salva não depende de nenhum mérito, poder ou esforço teu, mas flui inteiramente do amor gratuito de Deus, como isso muda a forma como você se aproxima do Pai hoje?$p$, 'reflexao', null),
    (v_aula_id, 2, $p$Wesley insiste que Cristo é o Salvador de todo o mundo e que Deus não tem prazer na morte de ninguém; de que maneira essa certeza do amor universal de Deus liberta você do medo de não ser amado o suficiente?$p$, 'reflexao', null),
    (v_aula_id, 3, $p$Diante de um Deus que livremente entrega o próprio Filho e clama "convertei-vos, e vivei", qual resposta de fé e de amor ao próximo Ele está esperando da sua vida neste momento?$p$, 'reflexao', null);
  end if;

end $migration$;
