-- =============================================================
-- EKBALLO ENGLISH · Áudio dos módulos 4 a 12
--
-- Fecha a cobertura de fala do curso inteiro. Mesma voz neural de
-- sempre (en-US-AriaNeural, -6%), gerada por
-- scripts/gerar-audios-english.mjs. Voz única do módulo 1 ao 12 —
-- a pronúncia de referência não troca de professor no meio da
-- jornada.
-- =============================================================

alter table english_exercicios add column if not exists audio_url text;

update english_exercicios set audio_url = '/english/audio/my-purpose-36cfaf.mp3' where audio_texto = 'my purpose';
update english_exercicios set audio_url = '/english/audio/my-plan-a24576.mp3' where audio_texto = 'my plan';
update english_exercicios set audio_url = '/english/audio/how-do-i-get-there-bc596f.mp3' where audio_texto = 'How do I get there?';
update english_exercicios set audio_url = '/english/audio/turn-left-920999.mp3' where audio_texto = 'Turn left';
update english_exercicios set audio_url = '/english/audio/every-week-d01ee2.mp3' where audio_texto = 'every week';
update english_exercicios set audio_url = '/english/audio/can-you-help-me-bf1355.mp3' where audio_texto = 'Can you help me?';
update english_exercicios set audio_url = '/english/audio/to-serve-dd8057.mp3' where audio_texto = 'to serve';
update english_exercicios set audio_url = '/english/audio/hello-this-is-ana-6fd5c6.mp3' where audio_texto = 'Hello this is Ana';
update english_exercicios set audio_url = '/english/audio/i-love-my-church-and-i-serve-there-69e81e.mp3' where audio_texto = 'I love my church and I serve there';
update english_exercicios set audio_url = '/english/audio/the-reason-is-c2bd95.mp3' where audio_texto = 'the reason is';
update english_exercicios set audio_url = '/english/audio/my-purpose-is-to-serve-people-25a1fe.mp3' where audio_texto = 'My purpose is to serve people';
update english_exercicios set audio_url = '/english/audio/tomorrow-2dac81.mp3' where audio_texto = 'tomorrow';
update english_exercicios set audio_url = '/english/audio/one-moment-please-8c1023.mp3' where audio_texto = 'One moment, please';
update english_exercicios set audio_url = '/english/audio/the-same-f35b07.mp3' where audio_texto = 'the same';
update english_exercicios set audio_url = '/english/audio/i-think-0596d6.mp3' where audio_texto = 'I think';
update english_exercicios set audio_url = '/english/audio/every-good-gift-cd000b.mp3' where audio_texto = 'every good gift';
update english_exercicios set audio_url = '/english/audio/how-have-you-been-ffc227.mp3' where audio_texto = 'How have you been?';
update english_exercicios set audio_url = '/english/audio/i-respect-your-opinion-8e396b.mp3' where audio_texto = 'I respect your opinion';
update english_exercicios set audio_url = '/english/audio/i-like-my-job-560c44.mp3' where audio_texto = 'I like my job';
update english_exercicios set audio_url = '/english/audio/god-is-faithful-cea3df.mp3' where audio_texto = 'God is faithful';
update english_exercicios set audio_url = '/english/audio/i-think-it-is-a-good-idea-830219.mp3' where audio_texto = 'I think it is a good idea';
update english_exercicios set audio_url = '/english/audio/this-is-my-testimony-e1984d.mp3' where audio_texto = 'This is my testimony.';
update english_exercicios set audio_url = '/english/audio/i-do-not-speak-english-well-397584.mp3' where audio_texto = 'I do not speak English well';
update english_exercicios set audio_url = '/english/audio/welcome-to-our-church-443758.mp3' where audio_texto = 'Welcome to our church!';
update english_exercicios set audio_url = '/english/audio/to-give-4e89ea.mp3' where audio_texto = 'to give';
update english_exercicios set audio_url = '/english/audio/i-read-the-bible-before-lunch-240a18.mp3' where audio_texto = 'I read the Bible before lunch';
update english_exercicios set audio_url = '/english/audio/old-c00dbb.mp3' where audio_texto = 'old';
update english_exercicios set audio_url = '/english/audio/nice-talking-to-you-f43684.mp3' where audio_texto = 'Nice talking to you.';
update english_exercicios set audio_url = '/english/audio/that-is-why-301537.mp3' where audio_texto = 'that is why';
update english_exercicios set audio_url = '/english/audio/just-a-moment-please-8b8156.mp3' where audio_texto = 'Just a moment please';
update english_exercicios set audio_url = '/english/audio/i-see-it-differently-but-i-respect-you-534e19.mp3' where audio_texto = 'I see it differently but I respect you';
update english_exercicios set audio_url = '/english/audio/the-doctor-0ab551.mp3' where audio_texto = 'the doctor';
update english_exercicios set audio_url = '/english/audio/to-believe-c5bf36.mp3' where audio_texto = 'to believe';
update english_exercicios set audio_url = '/english/audio/she-is-very-kind-4e4c7e.mp3' where audio_texto = 'She is very kind.';
update english_exercicios set audio_url = '/english/audio/the-grace-of-god-is-enough-d5037a.mp3' where audio_texto = 'The grace of God is enough';
update english_exercicios set audio_url = '/english/audio/it-is-difficult-bf33f8.mp3' where audio_texto = 'It is difficult';
update english_exercicios set audio_url = '/english/audio/i-hope-to-travel-one-day-ec832f.mp3' where audio_texto = 'I hope to travel one day.';
update english_exercicios set audio_url = '/english/audio/go-straight-and-turn-left-ed2c35.mp3' where audio_texto = 'Go straight and turn left';
update english_exercicios set audio_url = '/english/audio/i-want-to-learn-english-97c7ef.mp3' where audio_texto = 'I want to learn English.';
update english_exercicios set audio_url = '/english/audio/let-us-talk-about-it-8d319a.mp3' where audio_texto = 'Let us talk about it';
update english_exercicios set audio_url = '/english/audio/i-study-english-because-i-like-it-ea18a5.mp3' where audio_texto = 'I study English because I like it';
update english_exercicios set audio_url = '/english/audio/i-went-to-church-yesterday-0f6afe.mp3' where audio_texto = 'I went to church yesterday.';
update english_exercicios set audio_url = '/english/audio/not-really-aa1816.mp3' where audio_texto = 'Not really';
update english_exercicios set audio_url = '/english/audio/i-had-016be2.mp3' where audio_texto = 'I had';
update english_exercicios set audio_url = '/english/audio/it-was-a-good-day-f56116.mp3' where audio_texto = 'It was a good day.';
update english_exercicios set audio_url = '/english/audio/god-is-good-to-me-f11595.mp3' where audio_texto = 'God is good to me';
update english_exercicios set audio_url = '/english/audio/it-is-okay-130d50.mp3' where audio_texto = 'It is okay';
update english_exercicios set audio_url = '/english/audio/i-want-to-serve-people-137081.mp3' where audio_texto = 'I want to serve people';
update english_exercicios set audio_url = '/english/audio/grace-fd1cf5.mp3' where audio_texto = 'grace';
update english_exercicios set audio_url = '/english/audio/afraid-2ae387.mp3' where audio_texto = 'afraid';
update english_exercicios set audio_url = '/english/audio/i-trust-god-f627ce.mp3' where audio_texto = 'I trust God.';
update english_exercicios set audio_url = '/english/audio/the-service-76c0b3.mp3' where audio_texto = 'the service';
update english_exercicios set audio_url = '/english/audio/i-will-take-this-one-d7b593.mp3' where audio_texto = 'I will take this one.';
update english_exercicios set audio_url = '/english/audio/let-us-pray-together-089447.mp3' where audio_texto = 'Let us pray together.';
update english_exercicios set audio_url = '/english/audio/this-is-the-best-day-9766a2.mp3' where audio_texto = 'This is the best day.';
update english_exercicios set audio_url = '/english/audio/to-buy-5358d0.mp3' where audio_texto = 'to buy';
update english_exercicios set audio_url = '/english/audio/because-eaebe4.mp3' where audio_texto = 'Because';
update english_exercicios set audio_url = '/english/audio/where-is-the-hospital-98310f.mp3' where audio_texto = 'Where is the hospital?';
update english_exercicios set audio_url = '/english/audio/see-you-soon-43708e.mp3' where audio_texto = 'See you soon';
update english_exercicios set audio_url = '/english/audio/this-is-my-life-today-6ff56d.mp3' where audio_texto = 'This is my life today';
update english_exercicios set audio_url = '/english/audio/what-are-you-doing-today-a9a45d.mp3' where audio_texto = 'What are you doing today?';
update english_exercicios set audio_url = '/english/audio/god-is-with-me-every-day-a1a779.mp3' where audio_texto = 'God is with me every day';
update english_exercicios set audio_url = '/english/audio/i-am-going-to-travel-next-year-0d598f.mp3' where audio_texto = 'I am going to travel next year.';
update english_exercicios set audio_url = '/english/audio/i-want-to-learn-dd1a3c.mp3' where audio_texto = 'I want to learn';
update english_exercicios set audio_url = '/english/audio/i-help-my-mother-24df4e.mp3' where audio_texto = 'I help my mother';
update english_exercicios set audio_url = '/english/audio/where-are-you-from-7bc5e7.mp3' where audio_texto = 'Where are you from?';
update english_exercicios set audio_url = '/english/audio/how-often-do-you-study-0b4508.mp3' where audio_texto = 'How often do you study?';
update english_exercicios set audio_url = '/english/audio/my-dream-is-to-teach-f1fd4b.mp3' where audio_texto = 'my dream is to teach';
update english_exercicios set audio_url = '/english/audio/my-faith-is-my-foundation-ee2b8e.mp3' where audio_texto = 'My faith is my foundation';
update english_exercicios set audio_url = '/english/audio/why-do-you-study-english-e9b61b.mp3' where audio_texto = 'Why do you study English';
update english_exercicios set audio_url = '/english/audio/then-everything-changed-dd7205.mp3' where audio_texto = 'Then everything changed';
update english_exercicios set audio_url = '/english/audio/that-is-why-i-study-english-50212f.mp3' where audio_texto = 'That is why I study English.';
update english_exercicios set audio_url = '/english/audio/in-my-opinion-this-is-true-4539f9.mp3' where audio_texto = 'In my opinion this is true';
update english_exercicios set audio_url = '/english/audio/can-you-help-me-e4354a.mp3' where audio_texto = 'Can you help me';
update english_exercicios set audio_url = '/english/audio/when-i-was-a-child-i-lived-in-a-small-ci-565e75.mp3' where audio_texto = 'When I was a child I lived in a small city';
update english_exercicios set audio_url = '/english/audio/two-years-ago-2de0c7.mp3' where audio_texto = 'two years ago';
update english_exercicios set audio_url = '/english/audio/the-hotel-51d804.mp3' where audio_texto = 'the hotel';
update english_exercicios set audio_url = '/english/audio/i-prefer-684f88.mp3' where audio_texto = 'I prefer';
update english_exercicios set audio_url = '/english/audio/the-reason-is-simple-10b698.mp3' where audio_texto = 'The reason is simple';
update english_exercicios set audio_url = '/english/audio/the-price-695574.mp3' where audio_texto = 'the price';
update english_exercicios set audio_url = '/english/audio/i-am-sorry-860de5.mp3' where audio_texto = 'I am sorry.';
update english_exercicios set audio_url = '/english/audio/my-brother-is-funny-and-kind-bcee67.mp3' where audio_texto = 'My brother is funny and kind';
update english_exercicios set audio_url = '/english/audio/to-read-3d527a.mp3' where audio_texto = 'to read';
update english_exercicios set audio_url = '/english/audio/i-respect-your-opinion-051eb5.mp3' where audio_texto = 'I respect your opinion.';
update english_exercicios set audio_url = '/english/audio/to-learn-1e66d7.mp3' where audio_texto = 'to learn';
update english_exercicios set audio_url = '/english/audio/i-will-take-this-one-70e0e4.mp3' where audio_texto = 'I will take this one';
update english_exercicios set audio_url = '/english/audio/do-not-be-afraid-9fff21.mp3' where audio_texto = 'Do not be afraid';
update english_exercicios set audio_url = '/english/audio/i-do-not-feel-well-today-8ac674.mp3' where audio_texto = 'I do not feel well today.';
update english_exercicios set audio_url = '/english/audio/thank-you-lord-5b7698.mp3' where audio_texto = 'Thank you, Lord';
update english_exercicios set audio_url = '/english/audio/let-me-explain-my-opinion-030f9f.mp3' where audio_texto = 'Let me explain my opinion';
update english_exercicios set audio_url = '/english/audio/when-30603f.mp3' where audio_texto = 'when';
update english_exercicios set audio_url = '/english/audio/cheap-fb8df4.mp3' where audio_texto = 'cheap';
update english_exercicios set audio_url = '/english/audio/i-want-to-learn-the-word-46d7a7.mp3' where audio_texto = 'I want to learn the Word';
update english_exercicios set audio_url = '/english/audio/i-am-a-child-of-god-33dffb.mp3' where audio_texto = 'I am a child of God';
update english_exercicios set audio_url = '/english/audio/what-do-you-think-cd736b.mp3' where audio_texto = 'What do you think?';
update english_exercicios set audio_url = '/english/audio/my-house-is-small-68c27f.mp3' where audio_texto = 'My house is small.';
update english_exercicios set audio_url = '/english/audio/god-is-love-eb9546.mp3' where audio_texto = 'God is love.';
update english_exercicios set audio_url = '/english/audio/i-agree-6a151a.mp3' where audio_texto = 'I agree';
update english_exercicios set audio_url = '/english/audio/jesus-loves-you-4f4750.mp3' where audio_texto = 'Jesus loves you';
update english_exercicios set audio_url = '/english/audio/i-can-sing-68402a.mp3' where audio_texto = 'I can sing';
update english_exercicios set audio_url = '/english/audio/good-morning-everyone-06fd10.mp3' where audio_texto = 'Good morning, everyone';
update english_exercicios set audio_url = '/english/audio/i-am-fine-and-you-f3e80c.mp3' where audio_texto = 'I am fine. And you?';
update english_exercicios set audio_url = '/english/audio/welcome-e52e5e.mp3' where audio_texto = 'Welcome!';
update english_exercicios set audio_url = '/english/audio/i-understand-however-b2d682.mp3' where audio_texto = 'I understand, however';
update english_exercicios set audio_url = '/english/audio/which-one-do-you-like-5d98b0.mp3' where audio_texto = 'Which one do you like?';
update english_exercicios set audio_url = '/english/audio/i-serve-in-my-church-5a43d9.mp3' where audio_texto = 'I serve in my church';
update english_exercicios set audio_url = '/english/audio/i-am-working-df209e.mp3' where audio_texto = 'I am working';
update english_exercicios set audio_url = '/english/audio/the-airport-dc7d26.mp3' where audio_texto = 'the airport';
update english_exercicios set audio_url = '/english/audio/this-is-my-favorite-song-07437c.mp3' where audio_texto = 'This is my favorite song';
update english_exercicios set audio_url = '/english/audio/when-do-you-work-036446.mp3' where audio_texto = 'When do you work';
update english_exercicios set audio_url = '/english/audio/i-am-studying-english-4081a5.mp3' where audio_texto = 'I am studying English.';
update english_exercicios set audio_url = '/english/audio/this-is-my-testimony-90d13a.mp3' where audio_texto = 'This is my testimony';
update english_exercicios set audio_url = '/english/audio/i-work-in-the-morning-and-i-study-at-nig-485656.mp3' where audio_texto = 'I work in the morning and I study at night';
update english_exercicios set audio_url = '/english/audio/a-dream-be77f8.mp3' where audio_texto = 'a dream';
update english_exercicios set audio_url = '/english/audio/strong-011769.mp3' where audio_texto = 'strong';
update english_exercicios set audio_url = '/english/audio/before-i-met-jesus-my-life-was-empty-f9fb63.mp3' where audio_texto = 'Before I met Jesus my life was empty';
update english_exercicios set audio_url = '/english/audio/my-friends-are-kind-9a34d8.mp3' where audio_texto = 'My friends are kind';
update english_exercicios set audio_url = '/english/audio/i-am-going-to-church-a12354.mp3' where audio_texto = 'I am going to church';
update english_exercicios set audio_url = '/english/audio/i-believe-in-jesus-b208f1.mp3' where audio_texto = 'I believe in Jesus.';
update english_exercicios set audio_url = '/english/audio/the-bible-03982a.mp3' where audio_texto = 'the Bible';
update english_exercicios set audio_url = '/english/audio/i-need-a-doctor-b9a935.mp3' where audio_texto = 'I need a doctor.';
update english_exercicios set audio_url = '/english/audio/can-i-speak-to-bruno-1a7eb9.mp3' where audio_texto = 'Can I speak to Bruno?';
update english_exercicios set audio_url = '/english/audio/where-do-you-live-210e78.mp3' where audio_texto = 'Where do you live?';
update english_exercicios set audio_url = '/english/audio/one-day-ba08e9.mp3' where audio_texto = 'one day';
update english_exercicios set audio_url = '/english/audio/it-changed-my-life-2450a2.mp3' where audio_texto = 'It changed my life';
update english_exercicios set audio_url = '/english/audio/i-feel-sick-02fd62.mp3' where audio_texto = 'I feel sick';
update english_exercicios set audio_url = '/english/audio/hope-495574.mp3' where audio_texto = 'hope';
update english_exercicios set audio_url = '/english/audio/i-have-a-reservation-791e01.mp3' where audio_texto = 'I have a reservation.';
update english_exercicios set audio_url = '/english/audio/new-c2a6b0.mp3' where audio_texto = 'new';
update english_exercicios set audio_url = '/english/audio/i-have-a-big-family-and-we-live-together-c8bfe4.mp3' where audio_texto = 'I have a big family and we live together';
update english_exercicios set audio_url = '/english/audio/who-is-your-teacher-a1dad0.mp3' where audio_texto = 'Who is your teacher?';
update english_exercicios set audio_url = '/english/audio/i-love-my-church-and-i-serve-there-d8d519.mp3' where audio_texto = 'I love my church and I serve there.';
update english_exercicios set audio_url = '/english/audio/thank-you-for-listening-1624bf.mp3' where audio_texto = 'Thank you for listening.';
update english_exercicios set audio_url = '/english/audio/angry-246d1d.mp3' where audio_texto = 'angry';
update english_exercicios set audio_url = '/english/audio/i-am-eating-028a9a.mp3' where audio_texto = 'I am eating';
update english_exercicios set audio_url = '/english/audio/then-6f8f8e.mp3' where audio_texto = 'then';
update english_exercicios set audio_url = '/english/audio/i-feel-better-today-bfeb81.mp3' where audio_texto = 'I feel better today';
update english_exercicios set audio_url = '/english/audio/excuse-me-28bb4d.mp3' where audio_texto = 'Excuse me';
update english_exercicios set audio_url = '/english/audio/i-am-lost-can-you-help-me-264e88.mp3' where audio_texto = 'I am lost can you help me';
update english_exercicios set audio_url = '/english/audio/this-is-a-beautiful-city-40e0fb.mp3' where audio_texto = 'This is a beautiful city.';
update english_exercicios set audio_url = '/english/audio/i-am-thankful-for-this-day-718c5c.mp3' where audio_texto = 'I am thankful for this day';
update english_exercicios set audio_url = '/english/audio/hi-how-are-you-05cc82.mp3' where audio_texto = 'Hi! How are you?';
update english_exercicios set audio_url = '/english/audio/it-is-raining-today-827e40.mp3' where audio_texto = 'It is raining today';
update english_exercicios set audio_url = '/english/audio/yes-i-am-731e8c.mp3' where audio_texto = 'Yes, I am';
update english_exercicios set audio_url = '/english/audio/i-went-da963b.mp3' where audio_texto = 'I went';
update english_exercicios set audio_url = '/english/audio/a-problem-ccc6d3.mp3' where audio_texto = 'a problem';
update english_exercicios set audio_url = '/english/audio/my-name-is-ana-and-i-am-from-brazil-23186c.mp3' where audio_texto = 'My name is Ana and I am from Brazil';
update english_exercicios set audio_url = '/english/audio/the-medicine-c01adb.mp3' where audio_texto = 'the medicine';
update english_exercicios set audio_url = '/english/audio/patient-b1b0b8.mp3' where audio_texto = 'patient';
update english_exercicios set audio_url = '/english/audio/i-prefer-coffee-9d7574.mp3' where audio_texto = 'I prefer coffee.';
update english_exercicios set audio_url = '/english/audio/happy-3978d0.mp3' where audio_texto = 'happy';
update english_exercicios set audio_url = '/english/audio/amen-1f90d2.mp3' where audio_texto = 'Amen';
update english_exercicios set audio_url = '/english/audio/to-pray-a8465e.mp3' where audio_texto = 'to pray';
update english_exercicios set audio_url = '/english/audio/i-will-call-you-later-435d90.mp3' where audio_texto = 'I will call you later';
update english_exercicios set audio_url = '/english/audio/i-have-a-big-family-708201.mp3' where audio_texto = 'I have a big family';
update english_exercicios set audio_url = '/english/audio/always-665601.mp3' where audio_texto = 'always';
update english_exercicios set audio_url = '/english/audio/yes-i-do-016f7e.mp3' where audio_texto = 'Yes, I do';
update english_exercicios set audio_url = '/english/audio/i-think-my-family-is-a-gift-d712e7.mp3' where audio_texto = 'I think my family is a gift';
update english_exercicios set audio_url = '/english/audio/your-word-is-truth-f70d10.mp3' where audio_texto = 'Your word is truth';
update english_exercicios set audio_url = '/english/audio/it-is-near-here-b2c952.mp3' where audio_texto = 'It is near here';
update english_exercicios set audio_url = '/english/audio/my-favorite-place-is-my-church-16f5de.mp3' where audio_texto = 'My favorite place is my church';
update english_exercicios set audio_url = '/english/audio/the-best-4363f2.mp3' where audio_texto = 'the best';
update english_exercicios set audio_url = '/english/audio/i-want-to-buy-new-shoes-7dde6f.mp3' where audio_texto = 'I want to buy new shoes';
update english_exercicios set audio_url = '/english/audio/sad-b49146.mp3' where audio_texto = 'sad';
update english_exercicios set audio_url = '/english/audio/i-forgive-you-e4aab8.mp3' where audio_texto = 'I forgive you';
update english_exercicios set audio_url = '/english/audio/let-me-tell-you-a-story-f2b13d.mp3' where audio_texto = 'Let me tell you a story';
update english_exercicios set audio_url = '/english/audio/right-now-6b6d41.mp3' where audio_texto = 'right now';
update english_exercicios set audio_url = '/english/audio/this-is-my-friend-ana-5be3fc.mp3' where audio_texto = 'This is my friend Ana';
update english_exercicios set audio_url = '/english/audio/where-46148c.mp3' where audio_texto = 'where';
update english_exercicios set audio_url = '/english/audio/that-is-why-i-study-f1bd8c.mp3' where audio_texto = 'That is why I study';
update english_exercicios set audio_url = '/english/audio/just-a-moment-eda690.mp3' where audio_texto = 'Just a moment';
update english_exercicios set audio_url = '/english/audio/we-pray-together-every-night-056533.mp3' where audio_texto = 'We pray together every night.';
update english_exercicios set audio_url = '/english/audio/god-changed-my-life-88f51f.mp3' where audio_texto = 'God changed my life.';
update english_exercicios set audio_url = '/english/audio/my-job-22b3f3.mp3' where audio_texto = 'my job';
update english_exercicios set audio_url = '/english/audio/i-go-to-church-every-sunday-c25310.mp3' where audio_texto = 'I go to church every Sunday';
update english_exercicios set audio_url = '/english/audio/let-me-introduce-myself-5ae8a3.mp3' where audio_texto = 'Let me introduce myself';
update english_exercicios set audio_url = '/english/audio/next-year-i-want-to-speak-english-well-ffec46.mp3' where audio_texto = 'Next year I want to speak English well';
update english_exercicios set audio_url = '/english/audio/i-trust-god-ef6513.mp3' where audio_texto = 'I trust God';
update english_exercicios set audio_url = '/english/audio/we-sing-and-worship-together-7ec7e8.mp3' where audio_texto = 'We sing and worship together.';
update english_exercicios set audio_url = '/english/audio/help-3e8ade.mp3' where audio_texto = 'Help!';
update english_exercicios set audio_url = '/english/audio/expensive-e0d587.mp3' where audio_texto = 'expensive';
update english_exercicios set audio_url = '/english/audio/in-the-afternoon-1619b7.mp3' where audio_texto = 'in the afternoon';
update english_exercicios set audio_url = '/english/audio/i-am-going-to-travel-7b02c1.mp3' where audio_texto = 'I am going to travel';
update english_exercicios set audio_url = '/english/audio/this-is-who-i-am-2f8c05.mp3' where audio_texto = 'This is who I am';
update english_exercicios set audio_url = '/english/audio/what-do-you-like-to-do-bab84c.mp3' where audio_texto = 'What do you like to do?';
update english_exercicios set audio_url = '/english/audio/have-a-good-day-63801e.mp3' where audio_texto = 'Have a good day!';
update english_exercicios set audio_url = '/english/audio/i-do-not-know-07afb5.mp3' where audio_texto = 'I do not know';
update english_exercicios set audio_url = '/english/audio/do-you-like-coffee-564b6c.mp3' where audio_texto = 'Do you like coffee?';
update english_exercicios set audio_url = '/english/audio/god-changed-my-life-59fdd5.mp3' where audio_texto = 'God changed my life';
update english_exercicios set audio_url = '/english/audio/to-worship-1fea18.mp3' where audio_texto = 'to worship';
update english_exercicios set audio_url = '/english/audio/god-is-love-bd3454.mp3' where audio_texto = 'God is love';
update english_exercicios set audio_url = '/english/audio/it-is-a-beautiful-day-d78a80.mp3' where audio_texto = 'It is a beautiful day.';
update english_exercicios set audio_url = '/english/audio/i-am-busy-right-now-5e6311.mp3' where audio_texto = 'I am busy right now.';
update english_exercicios set audio_url = '/english/audio/i-read-the-bible-every-morning-48f7e8.mp3' where audio_texto = 'I read the Bible every morning.';
update english_exercicios set audio_url = '/english/audio/i-want-to-serve-god-fc6742.mp3' where audio_texto = 'I want to serve God.';
update english_exercicios set audio_url = '/english/audio/how-many-brothers-do-you-have-3ab10d.mp3' where audio_texto = 'How many brothers do you have';
update english_exercicios set audio_url = '/english/audio/funny-bf4809.mp3' where audio_texto = 'funny';
update english_exercicios set audio_url = '/english/audio/in-my-opinion-b43191.mp3' where audio_texto = 'In my opinion';
update english_exercicios set audio_url = '/english/audio/i-saw-7120ed.mp3' where audio_texto = 'I saw';
update english_exercicios set audio_url = '/english/audio/can-you-repeat-please-964c05.mp3' where audio_texto = 'Can you repeat, please?';
update english_exercicios set audio_url = '/english/audio/tomorrow-i-will-pray-in-the-morning-15de09.mp3' where audio_texto = 'Tomorrow I will pray in the morning';
update english_exercicios set audio_url = '/english/audio/i-see-it-differently-b4a73b.mp3' where audio_texto = 'I see it differently';
update english_exercicios set audio_url = '/english/audio/in-the-morning-9ab043.mp3' where audio_texto = 'in the morning';
update english_exercicios set audio_url = '/english/audio/no-problem-it-is-okay-c2bc18.mp3' where audio_texto = 'No problem it is okay';
update english_exercicios set audio_url = '/english/audio/a-verse-6aea80.mp3' where audio_texto = 'a verse';
update english_exercicios set audio_url = '/english/audio/i-am-reading-779f20.mp3' where audio_texto = 'I am reading';
update english_exercicios set audio_url = '/english/audio/i-am-thankful-1db6fc.mp3' where audio_texto = 'I am thankful';
update english_exercicios set audio_url = '/english/audio/i-prefer-coffee-b6ea60.mp3' where audio_texto = 'I prefer coffee';
update english_exercicios set audio_url = '/english/audio/i-feel-sick-today-695f6d.mp3' where audio_texto = 'I feel sick today';
update english_exercicios set audio_url = '/english/audio/last-week-c4a943.mp3' where audio_texto = 'last week';
update english_exercicios set audio_url = '/english/audio/peace-d7c50a.mp3' where audio_texto = 'peace';
update english_exercicios set audio_url = '/english/audio/before-i-met-jesus-3fdbd8.mp3' where audio_texto = 'Before I met Jesus';
update english_exercicios set audio_url = '/english/audio/i-study-because-i-want-to-serve-6c873c.mp3' where audio_texto = 'I study because I want to serve';
update english_exercicios set audio_url = '/english/audio/my-brothers-and-sisters-0732f7.mp3' where audio_texto = 'my brothers and sisters';
update english_exercicios set audio_url = '/english/audio/god-gives-me-peace-0d0284.mp3' where audio_texto = 'God gives me peace';
update english_exercicios set audio_url = '/english/audio/come-and-see-672e5e.mp3' where audio_texto = 'Come and see';
update english_exercicios set audio_url = '/english/audio/i-hope-to-09162e.mp3' where audio_texto = 'I hope to';
update english_exercicios set audio_url = '/english/audio/my-passport-883155.mp3' where audio_texto = 'my passport';
update english_exercicios set audio_url = '/english/audio/why-are-you-sad-78e90f.mp3' where audio_texto = 'Why are you sad';
update english_exercicios set audio_url = '/english/audio/call-the-police-5ca5d9.mp3' where audio_texto = 'Call the police';
update english_exercicios set audio_url = '/english/audio/how-often-do-you-study-29ec04.mp3' where audio_texto = 'How often do you study';
update english_exercicios set audio_url = '/english/audio/i-will-study-tomorrow-295af9.mp3' where audio_texto = 'I will study tomorrow.';
update english_exercicios set audio_url = '/english/audio/she-is-my-sister-2d970a.mp3' where audio_texto = 'She is my sister';
update english_exercicios set audio_url = '/english/audio/i-believe-in-jesus-and-i-serve-in-my-chu-492819.mp3' where audio_texto = 'I believe in Jesus and I serve in my church';
update english_exercicios set audio_url = '/english/audio/i-was-happy-yesterday-5ddcfa.mp3' where audio_texto = 'I was happy yesterday';
update english_exercicios set audio_url = '/english/audio/hi-i-am-ana-2bc0c4.mp3' where audio_texto = 'Hi I am Ana';
update english_exercicios set audio_url = '/english/audio/i-always-pray-in-the-morning-31cd12.mp3' where audio_texto = 'I always pray in the morning.';
update english_exercicios set audio_url = '/english/audio/it-was-a-good-day-7908d7.mp3' where audio_texto = 'It was a good day';
update english_exercicios set audio_url = '/english/audio/no-problem-243ee8.mp3' where audio_texto = 'No problem';
update english_exercicios set audio_url = '/english/audio/i-am-sorry-it-was-my-fault-0aeadf.mp3' where audio_texto = 'I am sorry it was my fault';
update english_exercicios set audio_url = '/english/audio/i-was-born-in-brazil-and-i-live-here-0d3c3b.mp3' where audio_texto = 'I was born in Brazil and I live here';
update english_exercicios set audio_url = '/english/audio/are-you-a-student-703817.mp3' where audio_texto = 'Are you a student?';
update english_exercicios set audio_url = '/english/audio/a-ticket-2502d5.mp3' where audio_texto = 'a ticket';
update english_exercicios set audio_url = '/english/audio/yes-i-do-7694bd.mp3' where audio_texto = 'Yes, I do.';
update english_exercicios set audio_url = '/english/audio/what-time-is-the-meeting-76544d.mp3' where audio_texto = 'What time is the meeting?';
update english_exercicios set audio_url = '/english/audio/i-prefer-to-read-at-night-5c699e.mp3' where audio_texto = 'I prefer to read at night';
update english_exercicios set audio_url = '/english/audio/my-favorite-ab933f.mp3' where audio_texto = 'my favorite';
update english_exercicios set audio_url = '/english/audio/better-than-042716.mp3' where audio_texto = 'better than';
update english_exercicios set audio_url = '/english/audio/small-89f622.mp3' where audio_texto = 'small';
update english_exercicios set audio_url = '/english/audio/it-is-cold-this-morning-ae9ed5.mp3' where audio_texto = 'It is cold this morning';
update english_exercicios set audio_url = '/english/audio/maybe-you-are-right-cd656c.mp3' where audio_texto = 'Maybe you are right.';
update english_exercicios set audio_url = '/english/audio/i-am-twenty-years-old-036ea4.mp3' where audio_texto = 'I am twenty years old';
update english_exercicios set audio_url = '/english/audio/a-solution-9162a8.mp3' where audio_texto = 'a solution';
update english_exercicios set audio_url = '/english/audio/it-is-a-beautiful-day-f24943.mp3' where audio_texto = 'It is a beautiful day';
update english_exercicios set audio_url = '/english/audio/i-have-a-new-book-542766.mp3' where audio_texto = 'I have a new book';
update english_exercicios set audio_url = '/english/audio/hello-this-is-ana-865721.mp3' where audio_texto = 'Hello, this is Ana';
update english_exercicios set audio_url = '/english/audio/i-disagree-6ad8cb.mp3' where audio_texto = 'I disagree';
update english_exercicios set audio_url = '/english/audio/turn-right-39fa44.mp3' where audio_texto = 'Turn right';
update english_exercicios set audio_url = '/english/audio/i-am-sorry-0e5e90.mp3' where audio_texto = 'I am sorry';
update english_exercicios set audio_url = '/english/audio/i-want-to-help-you-514ccf.mp3' where audio_texto = 'I want to help you.';
update english_exercicios set audio_url = '/english/audio/god-is-with-me-b434a6.mp3' where audio_texto = 'God is with me';
update english_exercicios set audio_url = '/english/audio/the-hospital-354535.mp3' where audio_texto = 'the hospital';
update english_exercicios set audio_url = '/english/audio/where-is-the-airport-c1b06e.mp3' where audio_texto = 'Where is the airport?';
update english_exercicios set audio_url = '/english/audio/because-i-like-english-e087fe.mp3' where audio_texto = 'Because I like English';
update english_exercicios set audio_url = '/english/audio/i-read-the-bible-and-i-pray-f70121.mp3' where audio_texto = 'I read the Bible and I pray';
update english_exercicios set audio_url = '/english/audio/for-example-7e2fb9.mp3' where audio_texto = 'for example';
update english_exercicios set audio_url = '/english/audio/i-need-help-please-267728.mp3' where audio_texto = 'I need help, please.';
update english_exercicios set audio_url = '/english/audio/i-love-my-church-0f3a68.mp3' where audio_texto = 'I love my church';
update english_exercicios set audio_url = '/english/audio/i-will-study-cfd678.mp3' where audio_texto = 'I will study';
update english_exercicios set audio_url = '/english/audio/let-me-tell-you-a-story-98d184.mp3' where audio_texto = 'Let me tell you a story.';
update english_exercicios set audio_url = '/english/audio/i-am-sad-today-7b10e6.mp3' where audio_texto = 'I am sad today';
update english_exercicios set audio_url = '/english/audio/what-time-is-the-service-6d0659.mp3' where audio_texto = 'What time is the service?';
update english_exercicios set audio_url = '/english/audio/jesus-loves-you-f683a3.mp3' where audio_texto = 'Jesus loves you.';
update english_exercicios set audio_url = '/english/audio/to-sing-87d881.mp3' where audio_texto = 'to sing';
update english_exercicios set audio_url = '/english/audio/nice-to-meet-you-too-abbff8.mp3' where audio_texto = 'Nice to meet you too';
update english_exercicios set audio_url = '/english/audio/that-is-right-948d6d.mp3' where audio_texto = 'That is right';
update english_exercicios set audio_url = '/english/audio/i-can-speak-english-c9be01.mp3' where audio_texto = 'I can speak English.';
update english_exercicios set audio_url = '/english/audio/i-saw-my-friend-last-week-dc67e2.mp3' where audio_texto = 'I saw my friend last week';
update english_exercicios set audio_url = '/english/audio/thank-you-for-listening-faaedd.mp3' where audio_texto = 'Thank you for listening';
update english_exercicios set audio_url = '/english/audio/i-am-not-sure-about-that-2bae3f.mp3' where audio_texto = 'I am not sure about that.';
update english_exercicios set audio_url = '/english/audio/who-b7adf7.mp3' where audio_texto = 'who';
update english_exercicios set audio_url = '/english/audio/i-cannot-382cdf.mp3' where audio_texto = 'I cannot';
update english_exercicios set audio_url = '/english/audio/i-pray-every-day-f586db.mp3' where audio_texto = 'I pray every day';
update english_exercicios set audio_url = '/english/audio/next-year-i-will-study-more-5b9a57.mp3' where audio_texto = 'Next year I will study more';
update english_exercicios set audio_url = '/english/audio/thank-you-lord-7c72ca.mp3' where audio_texto = 'Thank you, Lord.';
update english_exercicios set audio_url = '/english/audio/i-think-so-cbd238.mp3' where audio_texto = 'I think so';
update english_exercicios set audio_url = '/english/audio/first-i-woke-up-then-i-prayed-221265.mp3' where audio_texto = 'First I woke up then I prayed';
update english_exercicios set audio_url = '/english/audio/after-that-e55b2c.mp3' where audio_texto = 'after that';
update english_exercicios set audio_url = '/english/audio/because-d1ef47.mp3' where audio_texto = 'because';
update english_exercicios set audio_url = '/english/audio/i-want-to-make-a-difference-9f106e.mp3' where audio_texto = 'I want to make a difference.';
update english_exercicios set audio_url = '/english/audio/sorry-wrong-number-e95b32.mp3' where audio_texto = 'Sorry, wrong number';
update english_exercicios set audio_url = '/english/audio/yesterday-1aa96b.mp3' where audio_texto = 'yesterday';
update english_exercicios set audio_url = '/english/audio/can-you-repeat-please-a0aa6c.mp3' where audio_texto = 'Can you repeat please';
update english_exercicios set audio_url = '/english/audio/why-10cff4.mp3' where audio_texto = 'why';
update english_exercicios set audio_url = '/english/audio/i-agree-with-you-34c7ad.mp3' where audio_texto = 'I agree with you.';
update english_exercicios set audio_url = '/english/audio/last-year-a7d16e.mp3' where audio_texto = 'last year';
update english_exercicios set audio_url = '/english/audio/next-year-i-want-to-speak-english-well-d31bc1.mp3' where audio_texto = 'Next year I want to speak English well.';
update english_exercicios set audio_url = '/english/audio/how-much-is-this-12f611.mp3' where audio_texto = 'How much is this?';
update english_exercicios set audio_url = '/english/audio/the-pastor-4cd29f.mp3' where audio_texto = 'the pastor';
update english_exercicios set audio_url = '/english/audio/god-called-me-to-serve-229152.mp3' where audio_texto = 'God called me to serve';
update english_exercicios set audio_url = '/english/audio/it-is-cold-ef95af.mp3' where audio_texto = 'It is cold';
update english_exercicios set audio_url = '/english/audio/sure-113540.mp3' where audio_texto = 'Sure!';
update english_exercicios set audio_url = '/english/audio/big-95c4be.mp3' where audio_texto = 'big';
update english_exercicios set audio_url = '/english/audio/i-need-a-doctor-ecf798.mp3' where audio_texto = 'I need a doctor';
update english_exercicios set audio_url = '/english/audio/where-is-the-hospital-e04e3a.mp3' where audio_texto = 'Where is the hospital';
update english_exercicios set audio_url = '/english/audio/my-house-is-small-e0c9dd.mp3' where audio_texto = 'My house is small';
update english_exercicios set audio_url = '/english/audio/no-i-do-not-ab73f3.mp3' where audio_texto = 'No, I do not';
update english_exercicios set audio_url = '/english/audio/let-us-talk-about-it-tomorrow-f52fd0.mp3' where audio_texto = 'Let us talk about it tomorrow';
update english_exercicios set audio_url = '/english/audio/my-home-is-a-happy-place-9a229f.mp3' where audio_texto = 'My home is a happy place';
update english_exercicios set audio_url = '/english/audio/my-father-is-a-patient-man-69d11c.mp3' where audio_texto = 'My father is a patient man.';
update english_exercicios set audio_url = '/english/audio/i-can-swim-e8af0c.mp3' where audio_texto = 'I can swim';
update english_exercicios set audio_url = '/english/audio/i-agree-with-you-7fe7db.mp3' where audio_texto = 'I agree with you';
update english_exercicios set audio_url = '/english/audio/at-night-8812b0.mp3' where audio_texto = 'at night';
update english_exercicios set audio_url = '/english/audio/god-is-good-to-me-373c4a.mp3' where audio_texto = 'God is good to me.';
update english_exercicios set audio_url = '/english/audio/i-am-not-sure-9832ca.mp3' where audio_texto = 'I am not sure';
update english_exercicios set audio_url = '/english/audio/my-life-was-empty-6a649f.mp3' where audio_texto = 'my life was empty';
update english_exercicios set audio_url = '/english/audio/i-believe-in-jesus-b13d85.mp3' where audio_texto = 'I believe in Jesus';
update english_exercicios set audio_url = '/english/audio/of-course-885af3.mp3' where audio_texto = 'Of course';
update english_exercicios set audio_url = '/english/audio/you-are-right-that-is-true-7a8fe9.mp3' where audio_texto = 'You are right that is true';
update english_exercicios set audio_url = '/english/audio/it-is-near-here-00348f.mp3' where audio_texto = 'It is near here.';
update english_exercicios set audio_url = '/english/audio/i-have-a-headache-39252e.mp3' where audio_texto = 'I have a headache';
update english_exercicios set audio_url = '/english/audio/my-city-is-smaller-than-sao-paulo-f13dca.mp3' where audio_texto = 'My city is smaller than São Paulo';
update english_exercicios set audio_url = '/english/audio/i-have-a-reservation-e4699c.mp3' where audio_texto = 'I have a reservation';
update english_exercicios set audio_url = '/english/audio/i-would-like-to-serve-god-41fca5.mp3' where audio_texto = 'I would like to serve God';
update english_exercicios set audio_url = '/english/audio/good-morning-everyone-my-name-is-ana-and-49bbb5.mp3' where audio_texto = 'Good morning, everyone. My name is Ana and I am from Brazil.';
update english_exercicios set audio_url = '/english/audio/a-meeting-868772.mp3' where audio_texto = 'a meeting';
update english_exercicios set audio_url = '/english/audio/let-me-explain-a05824.mp3' where audio_texto = 'Let me explain';
update english_exercicios set audio_url = '/english/audio/how-many-brothers-do-you-have-e535cb.mp3' where audio_texto = 'How many brothers do you have?';
update english_exercicios set audio_url = '/english/audio/i-see-your-point-but-0a5c37.mp3' where audio_texto = 'I see your point, but';
update english_exercicios set audio_url = '/english/audio/i-feel-happy-today-3bbc95.mp3' where audio_texto = 'I feel happy today.';
update english_exercicios set audio_url = '/english/audio/where-is-the-airport-a6bce4.mp3' where audio_texto = 'Where is the airport';
update english_exercicios set audio_url = '/english/audio/i-am-thankful-for-a771b6.mp3' where audio_texto = 'I am thankful for';
update english_exercicios set audio_url = '/english/audio/now-i-have-hope-a14618.mp3' where audio_texto = 'Now I have hope';
update english_exercicios set audio_url = '/english/audio/i-am-fine-thank-you-and-you-4f39d5.mp3' where audio_texto = 'I am fine thank you and you';
update english_exercicios set audio_url = '/english/audio/hi-i-am-bruno-261a0e.mp3' where audio_texto = 'Hi, I am Bruno';
update english_exercicios set audio_url = '/english/audio/i-feel-better-today-ecc374.mp3' where audio_texto = 'I feel better today.';
update english_exercicios set audio_url = '/english/audio/worse-than-3e7265.mp3' where audio_texto = 'worse than';
update english_exercicios set audio_url = '/english/audio/i-met-jesus-two-years-ago-5553c3.mp3' where audio_texto = 'I met Jesus two years ago';
update english_exercicios set audio_url = '/english/audio/i-praise-you-a7efa5.mp3' where audio_texto = 'I praise you';
update english_exercicios set audio_url = '/english/audio/go-straight-cd7712.mp3' where audio_texto = 'Go straight';
update english_exercicios set audio_url = '/english/audio/i-work-in-the-morning-8b46f5.mp3' where audio_texto = 'I work in the morning';
update english_exercicios set audio_url = '/english/audio/to-go-cbd74c.mp3' where audio_texto = 'to go';
update english_exercicios set audio_url = '/english/audio/my-home-is-a-happy-place-c4d06e.mp3' where audio_texto = 'My home is a happy place.';
update english_exercicios set audio_url = '/english/audio/i-need-a-ticket-to-sao-paulo-70e131.mp3' where audio_texto = 'I need a ticket to São Paulo';
update english_exercicios set audio_url = '/english/audio/who-is-he-c12502.mp3' where audio_texto = 'Who is he?';
update english_exercicios set audio_url = '/english/audio/i-went-to-school-yesterday-145d62.mp3' where audio_texto = 'I went to school yesterday.';
update english_exercicios set audio_url = '/english/audio/who-is-that-woman-1e4390.mp3' where audio_texto = 'Who is that woman?';
update english_exercicios set audio_url = '/english/audio/that-is-true-91921b.mp3' where audio_texto = 'That is true';
update english_exercicios set audio_url = '/english/audio/how-is-the-weather-0171e8.mp3' where audio_texto = 'How is the weather?';
update english_exercicios set audio_url = '/english/audio/bigger-than-a0cb22.mp3' where audio_texto = 'bigger than';
update english_exercicios set audio_url = '/english/audio/kind-0ef25a.mp3' where audio_texto = 'kind';
update english_exercicios set audio_url = '/english/audio/i-was-born-in-brazil-bbe9f0.mp3' where audio_texto = 'I was born in Brazil';
update english_exercicios set audio_url = '/english/audio/maybe-you-are-right-b9e40c.mp3' where audio_texto = 'Maybe you are right';
update english_exercicios set audio_url = '/english/audio/help-me-god-e86ba7.mp3' where audio_texto = 'Help me, God';
update english_exercicios set audio_url = '/english/audio/i-believe-9bb3f3.mp3' where audio_texto = 'I believe';
update english_exercicios set audio_url = '/english/audio/faith-hope-and-love-33c7a1.mp3' where audio_texto = 'Faith, hope and love.';
update english_exercicios set audio_url = '/english/audio/it-is-raining-3f353b.mp3' where audio_texto = 'It is raining';
update english_exercicios set audio_url = '/english/audio/what-a110e6.mp3' where audio_texto = 'what';
update english_exercicios set audio_url = '/english/audio/to-see-be5382.mp3' where audio_texto = 'to see';
update english_exercicios set audio_url = '/english/audio/she-is-very-kind-54a0ba.mp3' where audio_texto = 'She is very kind';
update english_exercicios set audio_url = '/english/audio/in-the-morning-i-work-and-at-night-i-stu-071f05.mp3' where audio_texto = 'In the morning I work and at night I study';
update english_exercicios set audio_url = '/english/audio/love-9f2feb.mp3' where audio_texto = 'love';
update english_exercicios set audio_url = '/english/audio/you-are-right-e1551e.mp3' where audio_texto = 'You are right';
update english_exercicios set audio_url = '/english/audio/why-do-you-study-english-967412.mp3' where audio_texto = 'Why do you study English?';
update english_exercicios set audio_url = '/english/audio/finally-8f4e3e.mp3' where audio_texto = 'finally';
update english_exercicios set audio_url = '/english/audio/god-gives-me-peace-5caf7e.mp3' where audio_texto = 'God gives me peace.';
update english_exercicios set audio_url = '/english/audio/we-live-together-381aa9.mp3' where audio_texto = 'We live together';
update english_exercicios set audio_url = '/english/audio/he-is-a-teacher-bfe962.mp3' where audio_texto = 'He is a teacher';
update english_exercicios set audio_url = '/english/audio/what-do-you-do-ace108.mp3' where audio_texto = 'What do you do?';
update english_exercicios set audio_url = '/english/audio/i-want-to-make-a-difference-c0659d.mp3' where audio_texto = 'I want to make a difference';
update english_exercicios set audio_url = '/english/audio/my-church-is-my-family-f1490b.mp3' where audio_texto = 'My church is my family';
update english_exercicios set audio_url = '/english/audio/i-can-b3e2b8.mp3' where audio_texto = 'I can';
update english_exercicios set audio_url = '/english/audio/it-is-difficult-but-we-can-solve-it-985ab6.mp3' where audio_texto = 'It is difficult but we can solve it';
update english_exercicios set audio_url = '/english/audio/thank-you-lord-for-this-day-dbe171.mp3' where audio_texto = 'Thank you Lord for this day';
update english_exercicios set audio_url = '/english/audio/i-think-so-25f2e7.mp3' where audio_texto = 'I think so.';
update english_exercicios set audio_url = '/english/audio/i-am-lost-8e6168.mp3' where audio_texto = 'I am lost';
update english_exercicios set audio_url = '/english/audio/what-are-you-doing-today-c71089.mp3' where audio_texto = 'What are you doing today';
update english_exercicios set audio_url = '/english/audio/welcome-to-our-church-2a5d82.mp3' where audio_texto = 'Welcome to our church';
update english_exercicios set audio_url = '/english/audio/we-can-solve-it-together-9a447e.mp3' where audio_texto = 'We can solve it together.';
update english_exercicios set audio_url = '/english/audio/how-much-is-this-shirt-5edafc.mp3' where audio_texto = 'How much is this shirt';
update english_exercicios set audio_url = '/english/audio/we-can-solve-it-3028bd.mp3' where audio_texto = 'We can solve it';
update english_exercicios set audio_url = '/english/audio/do-you-like-coffee-50c760.mp3' where audio_texto = 'Do you like coffee';
update english_exercicios set audio_url = '/english/audio/i-am-not-sure-about-that-627321.mp3' where audio_texto = 'I am not sure about that';
update english_exercicios set audio_url = '/english/audio/never-85777c.mp3' where audio_texto = 'never';
update english_exercicios set audio_url = '/english/audio/what-is-your-name-21eb49.mp3' where audio_texto = 'What is your name?';
update english_exercicios set audio_url = '/english/audio/we-pray-together-every-night-8dff44.mp3' where audio_texto = 'We pray together every night';
update english_exercicios set audio_url = '/english/audio/i-serve-in-my-church-8cf8f3.mp3' where audio_texto = 'I serve in my church.';
update english_exercicios set audio_url = '/english/audio/sometimes-297f31.mp3' where audio_texto = 'sometimes';
update english_exercicios set audio_url = '/english/audio/can-i-pray-for-you-84d783.mp3' where audio_texto = 'Can I pray for you';
update english_exercicios set audio_url = '/english/audio/faith-102712.mp3' where audio_texto = 'faith';
update english_exercicios set audio_url = '/english/audio/when-i-was-a-child-2f5804.mp3' where audio_texto = 'When I was a child';
update english_exercicios set audio_url = '/english/audio/i-want-to-learn-english-017400.mp3' where audio_texto = 'I want to learn English';
update english_exercicios set audio_url = '/english/audio/i-need-help-please-30782b.mp3' where audio_texto = 'I need help please';
update english_exercicios set audio_url = '/english/audio/no-i-do-not-526261.mp3' where audio_texto = 'No I do not';
update english_exercicios set audio_url = '/english/audio/i-am-thankful-for-my-family-953c50.mp3' where audio_texto = 'I am thankful for my family.';
update english_exercicios set audio_url = '/english/audio/it-is-hot-today-becc8e.mp3' where audio_texto = 'It is hot today';
update english_exercicios set audio_url = '/english/audio/i-trust-god-every-day-aef29e.mp3' where audio_texto = 'I trust God every day';
update english_exercicios set audio_url = '/english/audio/i-read-the-bible-every-morning-ca939a.mp3' where audio_texto = 'I read the Bible every morning';
update english_exercicios set audio_url = '/english/audio/maybe-56dd8d.mp3' where audio_texto = 'Maybe';
update english_exercicios set audio_url = '/english/audio/i-am-busy-3a0646.mp3' where audio_texto = 'I am busy';
update english_exercicios set audio_url = '/english/audio/nice-to-meet-you-too-83d766.mp3' where audio_texto = 'Nice to meet you too.';
update english_exercicios set audio_url = '/english/audio/next-year-f84c8f.mp3' where audio_texto = 'next year';
update english_exercicios set audio_url = '/english/audio/i-have-faith-6bc328.mp3' where audio_texto = 'I have faith';
update english_exercicios set audio_url = '/english/audio/i-would-like-to-travel-340f1e.mp3' where audio_texto = 'I would like to travel';
update english_exercicios set audio_url = '/english/audio/let-us-worship-0ea016.mp3' where audio_texto = 'Let us worship';
update english_exercicios set audio_url = '/english/audio/god-called-me-2f139b.mp3' where audio_texto = 'God called me';
update english_exercicios set audio_url = '/english/audio/my-church-is-my-family-7e1f6d.mp3' where audio_texto = 'My church is my family.';
update english_exercicios set audio_url = '/english/audio/a-blessing-a12c0c.mp3' where audio_texto = 'a blessing';
update english_exercicios set audio_url = '/english/audio/to-help-6c0952.mp3' where audio_texto = 'to help';
update english_exercicios set audio_url = '/english/audio/thank-you-for-listening-to-me-af403c.mp3' where audio_texto = 'Thank you for listening to me';
update english_exercicios set audio_url = '/english/audio/thank-you-for-listening-to-me-29ede9.mp3' where audio_texto = 'Thank you for listening to me.';
update english_exercicios set audio_url = '/english/audio/nice-talking-to-you-e25b59.mp3' where audio_texto = 'Nice talking to you';
update english_exercicios set audio_url = '/english/audio/i-forgive-you-a49305.mp3' where audio_texto = 'I forgive you.';
update english_exercicios set audio_url = '/english/audio/i-study-every-day-b200fc.mp3' where audio_texto = 'I study every day.';
update english_exercicios set audio_url = '/english/audio/i-do-not-know-50703f.mp3' where audio_texto = 'I do not know.';
update english_exercicios set audio_url = '/english/audio/i-live-with-my-family-in-a-small-city-11897d.mp3' where audio_texto = 'I live with my family in a small city';
update english_exercicios set audio_url = '/english/audio/first-e0996a.mp3' where audio_texto = 'first';
update english_exercicios set audio_url = '/english/audio/better-a31e44.mp3' where audio_texto = 'better';
update english_exercicios set audio_url = '/english/audio/in-my-opinion-it-is-important-adedc3.mp3' where audio_texto = 'In my opinion, it is important';
update english_exercicios set audio_url = '/english/audio/it-changed-my-life-0195ca.mp3' where audio_texto = 'It changed my life.';
update english_exercicios set audio_url = '/english/audio/i-am-learning-right-now-ad3fe1.mp3' where audio_texto = 'I am learning right now';
update english_exercicios set audio_url = '/english/audio/what-should-we-do-19c298.mp3' where audio_texto = 'What should we do?';
update english_exercicios set audio_url = '/english/audio/we-have-a-problem-and-a-solution-ed33d9.mp3' where audio_texto = 'We have a problem and a solution';
update english_exercicios set audio_url = '/english/audio/today-is-better-than-yesterday-2dc872.mp3' where audio_texto = 'Today is better than yesterday.';
update english_exercicios set audio_url = '/english/audio/can-i-pray-for-you-201ef5.mp3' where audio_texto = 'Can I pray for you?';
update english_exercicios set audio_url = '/english/audio/my-favorite-place-is-my-church-6069dd.mp3' where audio_texto = 'My favorite place is my church.';
update english_exercicios set audio_url = '/english/audio/i-was-happy-651dbd.mp3' where audio_texto = 'I was happy';
update english_exercicios set audio_url = '/english/audio/my-parents-taught-me-e862a9.mp3' where audio_texto = 'My parents taught me';
update english_exercicios set audio_url = '/english/audio/today-is-better-than-yesterday-7bf205.mp3' where audio_texto = 'Today is better than yesterday';
update english_exercicios set audio_url = '/english/audio/let-me-introduce-myself-ba4dc8.mp3' where audio_texto = 'Let me introduce myself.';
update english_exercicios set audio_url = '/english/audio/what-do-you-think-about-it-f66008.mp3' where audio_texto = 'What do you think about it?';
update english_exercicios set audio_url = '/english/audio/i-am-thankful-for-my-family-663d92.mp3' where audio_texto = 'I am thankful for my family';
update english_exercicios set audio_url = '/english/audio/i-want-to-serve-god-1e9125.mp3' where audio_texto = 'I want to serve God';
update english_exercicios set audio_url = '/english/audio/i-am-studying-english-ab0c54.mp3' where audio_texto = 'I am studying English';
update english_exercicios set audio_url = '/english/audio/a-gift-bd7952.mp3' where audio_texto = 'a gift';
update english_exercicios set audio_url = '/english/audio/i-study-every-week-808389.mp3' where audio_texto = 'I study every week';
update english_exercicios set audio_url = '/english/audio/before-lunch-8469f8.mp3' where audio_texto = 'before lunch';
update english_exercicios set audio_url = '/english/audio/to-come-ef5b69.mp3' where audio_texto = 'to come';
update english_exercicios set audio_url = '/english/audio/after-that-i-went-home-9871b6.mp3' where audio_texto = 'After that I went home';
