-- entendes-o-que-les — devolve as figuras do miolo.
--
-- Duas figuras do miolo (pags. 198 e 201), as unicas do livro com texto na mesma pagina.
--
-- Classificacao feita imagem a imagem: a varredura bruta do acervo confundia
-- capa, folha de rosto, logo de editora e anuncio de fim de livro com figura de
-- conteudo. Aqui so entram as do miolo.
--
-- Posicionamento pela fracao de pagina dentro da faixa do capitulo.
-- Idempotente: so altera mesa que ainda nao tem bloco [figura].

do $migration$
declare
  v_curso_id uuid;
begin
  select id into v_curso_id from public.cursos where slug = 'entendes-o-que-les';
  if v_curso_id is null then
    raise exception 'curso entendes-o-que-les nao encontrado';
  end if;

  update public.aulas set conteudo = $c$Por consequência, à luz desses princípios, podemos formar um argumento muito forte em prol da imersão como sendo o modo do batismo, um argumento mais fraco em prol da observância da Ceia do Senhor todos os domingos, mas quase nenhum argumento a favor do batismo de crianças (este pode, naturalmente, ser argumentado a partir do precedente histórico na igreja, mas não tão facilmente a partir do precedente bíblico, que é a questão em pauta aqui). Da mesma forma, a função do ministro cristão como sacerdote (com base na analogia do Antigo Testamento!) fracassa em todos os casos, em termos da sua base bíblica.

Não imaginamos com isso que solucionamos todos os problemas, mas pensamos que são sugestões funcionais, e esperamos que elas levem você a pensar exegeticamente e com maior precisão hermenêutica nos momentos em que lê as narrativas bíblicas.

Evangelhos: uma história, muitas

dimensões

Do mesmo modo que acontece com as epístolas e Atos, os evangelhos parecem, à primeira vista, ser livros fáceis de interpretar. Uma vez que nosso material dos evangelhos pode ser dividido, a grosso modo, em ditos e narrativas — ou seja, em ensinos de Jesus e em histórias acerca de Jesus —, pela teoria, poderíamos seguir os mesmos princípios de interpretação das epístolas em relação aos ditos, e os mesmos princípios de interpretação das narrativas históricas em relação às narrativas.

Em certo sentido, isso é verdade. No entanto, essa questão não é tão fácil assim. Os quatro evangelhos formam um gênero literário inigualável, para o qual há poucas analogias reais. Sua singularidade, que

examinaremos por um momento, é a responsável pela maioria dos nossos problemas exegéticos. Mas ainda há algumas dificuldades hermenêuticas. Algumas delas, é claro, assumem a forma daquelas “palavras duras” registradas nos evangelhos. A principal dificuldade hermenêutica, porém, encontra-se na compreensão do “Reino de Deus”, termo este que é, ao mesmo tempo, absolutamente crucial para a totalidade do ministério de Jesus, mas é também apresentado em linguagem e conceitos do judaísmo do século I. O problema é como traduzir tais ideias para nossos próprios contextos culturais.

Natureza dos evangelhos

Quase todas as dificuldades que encontramos na interpretação dos evangelhos têm sua origem em dois fatos óbvios: (1) O próprio Jesus não escreveu um evangelho; eles foram escritos por outras pessoas, e não por ele. (2) Há quatro evangelhos.

1. O fato de que os quatro evangelhos não provêm do próprio Jesus é uma consideração muito importante. Se ele tivesse escrito algo, é claro que isso provavelmente não teria tanto o aspecto dos nossos evangelhos; seria então algo mais próximo dos livros proféticos do Antigo Testamento, como, por exemplo, Amós — uma coletânea de oráculos falados e ditos com algumas poucas narrativas curtas e pessoais (como Am 7.10-17). Nossos evangelhos realmente contêm coletâneas de ditos, mas estas sempre estão entretecidas, como parte integrante, numa narrativa histórica da vida e do ministério de Jesus. Logo, não são livros de Jesus, mas livros acerca de Jesus, que contêm ao mesmo tempo uma coleção considerável de seus ensinos.

A dificuldade que se apresenta diante de nós não deve ser exagerada, mas também não deve ser ignorada; ela existe e precisamos aprender a lidar com ela. Para

identificarmos melhor a natureza dessa dificuldade, podemos recorrer a uma analogia de Paulo em Atos e em suas epístolas. Se não tivéssemos Atos, por exemplo, poderíamos ajuntar alguns dos elementos da vida de Paulo com base nas epístolas, mas para uma apresentação dessa natureza isso seria insuficiente. Do mesmo modo, se não tivéssemos suas epístolas, a nossa compreensão da teologia paulina, com base apenas nos discursos que ele fez em Atos, seria igualmente insuficiente — e um pouco fora do normal. Para obtermos os itens-chave da vida de Paulo, temos então de ler Atos e, em seguida, completarmos as informações com o que está registrado em suas epístolas. Para seus ensinos, não recorremos primeiramente a Atos, mas sim às epístolas, e a Atos como uma fonte adicional.

Mas os evangelhos não são como Atos, porque nesse caso temos tanto uma narrativa da vida de Jesus como grandes blocos de seus ditos (ensinos), como uma parte absolutamente básica de sua vida. Mas os ditos não foram escritos por ele, do mesmo modo que as epístolas foram escritas por Paulo. O idioma nativo de Jesus era o aramaico; seus ensinos chegaram a nós apenas em grego. Além disso, em muitos casos, o mesmo dito é registrado em dois ou três dos evangelhos, mas raras vezes é achado com a mesma redação em cada evangelho — mesmo quando aparece na sequência cronológica ou em situação histórica exatas. '

Para alguns, essa realidade pode ser ameaçadora, mas não precisa ser assim. Naturalmente, é verdade que certos tipos de erudição distorceram essa realidade de tal forma que acabaram por sugerir que nada nos quatro evangelhos é fidedigno. Contudo, essa conclusão é problemática em termos históricos. Erudição igualmente válida já demonstrou a fidedignidade histórica do material existente nos evangelhos.

Nesse caso, nosso argumento é simples: Deus nos deu dessa forma aquilo que sabemos sobre o ministério terreno

de Jesus, e não de outra forma, que talvez pudesse se adaptar melhor à mentalidade mecanicista, de alguém que com um simples gravador resolveria tudo. De qualquer maneira, argumentamos que o fato de os evangelhos não terem sido escritos por Jesus, mas terem sido escritos para falar sobre Jesus é algo que faz parte da genialidade deles, e não da sua fraqueza.

2. Além disso, há quatro deles. Como isso aconteceu, e por quê? Afinal de contas, não temos quatro Atos dos Apóstolos. Ademais, o material dos três primeiros evangelhos são em muitos casos semelhantes. Por isso, são conhecidos como evangelhos sinóticos (“do ponto de vista comum”). De fato, poderíamos perguntar por que conservar Marcos, uma vez que a quantidade de material encontrada.exclusivamente em seu evangelho dificilmente encheria duas páginas impressas. Mas também nesse caso, cremos que o fato de haver quatro é parte da genialidade deles.

Qual, pois, é a natureza dos evangelhos, e por que sua natureza inigualável faz parte da genialidade? A melhor maneira de responder a essa questão é começarmos pela pergunta: Por que quatro? Não podemos dar uma resposta absolutamente definitiva, mas pelo menos podemos apresentar uma das razões, que é simples e pragmática: diferentes comunidades cristãs tinham a necessidade de ter um livro que falasse sobre Jesus. Por uma variedade de razões, o evangelho escrito para uma comunidade ou grupo de cristãos não satisfazia necessariamente as necessidades de outra comunidade. Logo, um deles foi escrito primeiro (Marcos, de acordo com a opinião mais amplamente aceita), e este evangelho foi “reescrito” duas vezes (Mateus e Lucas) por razões consideravelmente diferentes. A parte deles (também de acordo com a opinião mais amplamente aceita), João escreveu um evangelho diferente, ainda por um outro conjunto de razões ainda. Cremos que tudo isso foi orquestrado pelo Espírito Santo.

Para a igreja posterior, nenhum dos evangelhos substitui o outro, mas cada um está lado a lado com os demais, e são igualmente valiosos e igualmente dignos de autoridade. Como assim? Porque em cada caso o interesse por Jesus pode ser visto em dois níveis. Em primeiro lugar, havia a preocupação puramente histórica: essa é a Pessoa de Jesus, foi isso que ele disse e fez; e é este Jesus — que foi crucificado e ressurreto dentre os mortos — a quem agora adoramos como o Senhor ressurreto e exaltado. Em segundo lugar, havia o empenho existencial de repetir essa história para atender às necessidades de comunidades posteriores que não falavam aramaico, mas grego, e que não viviam num âmbito basicamente rural, agrícola e judaico, mas sim em Roma, ou Éfeso, ou Antioquia, onde o evangelho se circunscrevia num ambiente urbano e pagão.

Em certo sentido, portanto, os evangelhos já funcionam como modelos hermenêuticos para nós, insistindo, por sua própria natureza, que nós também narremos de novo a mesma história em nossos próprios contextos do século XXI.

Dessa forma, esses livros, que nos contam virtualmente tudo quanto sabemos acerca de Jesus, não são por esse motivo biografias — embora sejam parcialmente biográficos. Também não são como as “vidas” contemporâneas dos grandes homens — embora registrem a vida do maior homem de todos os tempos. Fazendo uso da frase Justino Mártir, pai eclesiástico do século li, eles são “as memórias dos apóstolos”. Quatro biografias não poderiam ficar lado a lado tendo o mesmo valor: esses livros ficam lado a lado, porque, ao mesmíssimo tempo, registram os fatos acerca de Jesus, relembram o ensino de Jesus, e dão testemunho de Jesus. Essa é a sua natureza, e essa é a sua genialidade, o que é importante para a exegese bem como para a hermenêutica.

A exegese dos quatro evangelhos, portanto, requer que pensemos tanto em termos do contexto histórico de Jesus

quanto em termos do contexto histórico dos autores.

Contexto histórico

Você deve se lembrar que a primeira tarefa da exegese é ter consciência do contexto histórico. Isso implica conhecer não apenas o contexto histórico em geral, mas também implica formar uma reconstrução experimental, mas bem- informada, da situação a qual o autor se dirige. Pode ser que isso às vezes se torne complexo, por causa da natureza dos evangelhos como documentos em dois níveis. Em princípio, o contexto histórico tem a ver com o próprio Jesus. Inclui tanto uma consciência da cultura e da religião do século I, do judaísmo palestino em que Jesus vivia e ensinava, bem como uma tentativa de compreender o contexto específico de um determinado dito ou parábola. Entretanto, o contexto histórico também tem a ver com os autores individuais (os evangelistas) e suas razões para escreverem.

Temos consciência de que tomar a iniciativa de pensar sobre esses vários contextos pode ser uma tarefa imponente para o leitor comum. Além disso, reconhecemos que provavelmente mais estudos especulativos são realizados aqui do que em qualquer outro lugar do Novo Testamento. Mesmo assim, a natureza dos evangelhos é um fato dado; são documentos em dois níveis, quer queiramos, quer não. Não temos a pretensão de que podemos fazer de você um perito nessas questões. Nossa esperança aqui é simplesmente aumentar seu nível de consciência para que você tenha maior apreço por aquilo que/os evangelhos são, e também para que você tenha uma boa compreensão dos tipos de perguntas que precisará fazer enquanto os lê.

Contexto histórico de Jesus — em geral

Para entender Jesus, é imperativo que você se aprofunde no judaísmo do século I do qual ele fazia parte. E isso significa muito mais do que simplesmente saber que os saduceus não acreditam na ressurreição. Precisamos saber por que não acreditavam, e por que Jesus tinha tão pouco contato com eles.

Para esse tipo de informação sobre a situação histórica, simplesmente não há alternativa para boas leituras externas. Dois livros serão muito úteis: Joachim Jeremias: Jerusalém nos tempos de Jesus (São Paulo, Paulinas, 1983); Henri Daniel-Rops: A vida diária nos tempos de Jesus (São Paulo, Vida Nova, 2008).

Um aspecto importante nessa dimensão do contexto histórico, que é muitas vezes esquecido, tem a ver com a forma do ensino de Jesus. Todos sabem que muitas vezes Jesus ensinava por meio de parábolas. O que as pessoas menos sabem é que ele usava uma grande variedade de formas para contar essas parábolas. Por exemplo, ele era um mestre do exagero proposital (hipérbole). Em Mateus 5.29,30 (e no paralelo em Mc 9.43-48), Jesus manda seus discípulos arrancarem um olho que os leva a tropeçar, ou cortarem um braço que os leva ao pecado. Ora, todos nós sabemos que Jesus “realmente não queria dizer aquilo”. O que ele queria dizer era que as pessoas deviam arrancar de sua vida aquilo que as levava ao pecado. Mas como podemos saber que ele não queria que entendêssemos suas palavras literalmente? Porque todos nós somos capazes de reconhecer o exagero como uma técnica muito eficaz, em que podemos ir além das palavras literais de um professor e perceber com clareza o significado do que ele quer falar!

Além disso, com bastante eficácia, Jesus fazia uso de: provérbios (e.g. Mt 6.21; Mc 3.24); símiles e metáforas (e.g., Mt 10.16; 5.13); linguagem poética (e.g., Mt 7.7-8; Lc 6.27-28); perguntas (e.g., Mt 17.25); e ironia (e.g., Mt 16.2- 3). E isso só para mencionar algumas das formas usadas

por Cristo. Para mais informações sobre esse assunto, você poderia ler The Method and Message of Jesus’ Teaching, de Robert H. Stein (Louisville, Ky., Westminster John Knox, 1994).

Contexto histórico de Jesus — em particular

Na tentativa de reconstruir o contexto histórico de Jesus, esse é um dos aspectos mais difíceis, principalmente porque muitos de seus ensinos são apresentados nos quatro evangelhos sem muito contexto. A razão disso é que as palavras e os atos de Jesus foram transmitidos oralmente durante um período de cerca de trinta anos ou mais. Durante esse período, os evangelhos completos ainda não existiam. Além disso, o conteúdo dos evangelhos era passado adiante em histórias e ditos, chamados de “perícopes”. Muitos desses ditos de Jesus foram também transmitidos com seus contextos originais. Os estudiosos chegaram a chamar tais perícopes de “histórias de pronunciamentos”, porque a própria narrativa apenas existe por causa do dito que a conclui. Uma história típica de pronunciamento é Marcos 12.13-17, texto em que o contexto é uma pergunta sobre o ato de pagar impostos aos romanos. Tal situação termina com o famoso pronunciamento de Jesus: “Dai a César o que é de César, e a Deus o que é de Deus”. Você pode imaginar o que poderíamos ter feito para reconstruir um contexto original para esse dito, se este não tivesse sido transmitido com seu contexto original?

É claro que a verdadeira dificuldade advém do fato de que um grande número dos ditos e ensinos foi transmitido sem seus contextos. O próprio Paulo confirma essa realidade. Por três vezes, ele cita ditos de Jesus (lCo 7.10; 9.14; At 20.35) sem fazer qualquer alusão aos contextos históricos originais deles — nem poderíamos esperar que ele o fizesse. Dentre esses ditos, dois em lCoríntios também

se encontram nos evangelhos. O dito sobre o divórcio é encontrado em dois contextos diferentes (no ensino dado aos discípulos, em Mt 5.31-32; e na controvérsia registrada em Mt 19.1-10 e Mc 10.1-12). O dito sobre o “direito à remuneração” é encontrado em Mateus 10.10 e seu paralelo em Lucas 10.7 no contexto em que Jesus envia os doze (em Mateus) e os setenta e dois (em Lucas). Contudo, o dito em Atos não é achado de modo algum nos evangelhos, de modo que, para nós, está totalmente fora de um contexto original.

Não podemos nos surpreender, portanto, quando ficamos sabendo que muitos de tais ditos (sem contextos) estavam disponíveis aos evangelistas. Foram os próprios evangelistas, sob a orientação que receberam do Espírito Santo, que deram a esses ditos seu presente contexto. Essa é uma das razões por que muitas vezes encontramos o mesmo dito ou ensino em contextos diferentes nos quatro evangelhos. E por isso também que ditos com temas semelhantes, ou que tratam do mesmo assunto, frequentemente são agrupados de acordo com os tópicos.

Mateus, por exemplo, tem cinco grandes coletâneas que seguem um tópico (cada uma delas termina com algo como: “Ao concluir Jesus esse discurso...” [7.28]): a vida no reino (o conhecido Sermão do Monte, caps. 5—7); as instruções para os ministros do reino (10.5-42); as parábolas do reino em ação no mundo (13.1-52); o ensino sobre relacionamentos e disciplina no reino (18.1-35); a escatologia, ou a consumação do reino (caps. 23—25).

Para identificarmos que essas cinco coletâneas pertencem ao evangelho de Mateus, pode-se recorrer ao capítulo 10, ressaltando-se dois pontos. (1) O contexto é a missão histórica dos Doze e as instruções de Jesus a eles enquanto os enviava (v. 5-12). No entanto, nos v. 16-20, as instruções se referem a um tempo muito posterior, visto que nos v. 5 e 6 os discípulos receberam a ordem de ir somente em busca das ovelhas perdidas de Israel e foram

ao mesmo tempo alertados, no v. 18, de que seriam trazidos diante de “governadores e reis,” e dos “gentios,” e nenhum destes estava incluído na missão original dos Doze. (2) Esses ditos, muito bem dispostos, são achados espalhados em muitas partes do evangelho de Lucas na seguinte ordem: 9.2-5; 10.3; 21.12-17; 12.11,12; 6.40; 12.2- 9; 12.51-53; 14.25-27; 17.33; 10.16. Isso sugere que Lucas também teve acesso à maioria desses ditos como unidades separadas, o que fez com que ele os dispusesse em contextos separados.

Dessa forma, enquanto você lê os quatro evangelhos, uma das perguntas que desejará fazer — mesmo que não consiga respondê-la com absoluta certeza — é se o auditório para o qual Jesus promulgou um determinado ensinamento era composto de seus discípulos íntimos, das grandes multidões, ou de seus oponentes. Descobrir o contexto histórico de Jesus, ou qual era seu auditório, não é algo que necessariamente afetará o significado básico de um determinado dito. Contudo, o fato de conhecê-lo ampliará nossa perspectiva e muitas vezes nos ajudará a compreender a razão de ser daquilo que Jesus disse.

Contexto histórico do evangelista

A essa altura, não falamos do contexto literário que cada evangelista escolheu para dispor o material que tinha disponível acerca de Jesus, mas sim acerca do contexto histórico de cada autor, que o impulsionou a escrever, sobretudo, um evangelho. Mais uma vez, entramos em um campo em que há apenas certa quantidade de conjeturas propostas pela erudição, uma vez que os próprios evangelhos são anônimos (no sentido de que os autores não são nominalmente identificados neles), e não podemos ter certeza dos seus lugares de origem. No entanto, podemos ter uma certeza razoável quanto ao interesse e quanto às

preocupações de cada evangelista, a partir do modo como selecionaram, formaram e dispuseram seu material.

O evangelho de Marcos, por exemplo, está especialmente interessado em explicar a natureza do messiado de Jesus à luz da ideia central do “segundo êxodo” de Isaías (consulte, se possível, Gordon D. Fee; Douglas Stuart, How to Read the Bible Book by Book (2a

ed.), p. 279-280). Embora Marcos saiba que o Messias é o poderoso Filho de Deus (1.1), que andou pela Galileia com poder e compaixão (caps. 1.1—8.26), sabe também que Jesus por várias vezes conservava oculto o seu messiado (ver e.g., 1.34; 1.43; 3.12; 4.11; 5.43; 7.24; 7.36; 8.26; 8.30). A razão desse silêncio é que somente Jesus compreendia a verdadeira natureza de seu destino messiânico — o destino do “Servo Sofredor” (como se vê em Isaías), que conquista através da morte. Embora isso seja explicado três vezes aos discípulos, eles também não conseguem compreender (8.27-33; 9.30-32; 10.32-45). Como o homem que foi tocado duas vezes (8.22-26), eles precisavam de um segundo toque — a ressurreição — para que pudessem ver com clareza.

O fato de o interesse de Marcos centralizar-se na natureza de servo sofredor do messiado de Jesus fica ainda mais evidente com o fato de ele não incluir qualquer dos ensinos de Jesus sobre o discipulado até depois da primeira explicação do seu próprio sofrimento em 8.31-33. A implicação, bem como o ensino explícito, fica clara. A cruz e a condição de servo que Jesus experimentou são também as marcas do discipulado genuíno. Como disse o poeta: “Esse é o caminho que o Mestre palmilhou. Não deve o servo continuar a palmilhá-lo?”.

Tudo isso pode ser visto numa leitura cuidadosa do evangelho de Marcos. Esse é o contexto histórico dele. Tentar torná-lo mais específico produziria mais conjeturas, mas não vemos razão alguma para não seguirmos a antiga

tradição que diz que o evangelho de Marcos reflete as “memórias” de Pedro e que esse evangelho apareceu em Roma pouco depois do martírio desse apóstolo, num período de grande sofrimento entre os cristãos em Roma. De qualquer forma, semelhante leitura e estudo do contexto é tão importante para os evangelhos quanto o é para as epístolas.

Contexto literário

Já tocamos um pouco no assunto do contexto literário na seção sobre “o contexto histórico de Jesus — em particular”. O contexto literário tem a ver com o lugar de uma determinada perícope no contexto de qualquer um dos evangelhos. Até certo ponto, esse contexto provavelmente já era fixado pelo seu próprio contexto histórico original, e possivelmente o evangelista tenha tido algum conhecimento acerca dele. Contudo, como já vimos, muito do material encontrado nos quatro evangelhos deve seu atual contexto aos próprios evangelistas, conforme sua inspiração pelo Espírito Santo.

Nossa preocupação aqui é dupla: (1) ajudar você a fazer exegese ou ler com entendimento um determinado dito ou narrativa no seu presente contexto, e (2) ajudar você a entender a natureza da composição dos evangelhos como um todo, e assim interpretar qualquer um dos evangelhos em si mesmo (consulte, se possível, Gordon D. Fee; Douglas Stuart, How to Read the Bible Book by Book [2a ed.]), e não apenas fatos isolados da vida de Jesus.

Interpretando as perícopes individuais

Ao discutirmos como interpretar as epístolas, notamos que você deve aprender a “pensar em parágrafos”. Isso não é tão importante no caso dos evangelhos, embora em

alguns momentos ainda seja apropriado, especialmente quando se trata de grandes blocos de ensino. Como notamos de início, essas seções de ensino realmente terão algumas semelhanças com a abordagem que adotamos para o estudo das epístolas. No entanto, por causa da natureza inigualável dos evangelhos, há duas coisas que precisamos fazer: pensar horizontalmente, e pensar verticalmente.

Essa é tão somente a forma de dizermos que, quando interpretamos ou lemos um dos evangelhos, precisamos ter em mente estas duas realidades que já foram notadas acima: que há quatro deles, e que são documentos “em dois níveis”.

Pense horizontalmente Pensar horizontalmente significa que devemos ter consciência dos paralelos de uma perícope nos demais evangelhos enquanto a estudamos em qualquer um dos evangelhos. Sem dúvida, essa consideração não deve ser exagerada, visto que nenhum dos evangelistas pretendeu que seu evangelho fosse lido em paralelo com os demais. Mesmo assim, o fato de Deus ter providenciado quatro evangelhos no cânon significa que não podem ser legitimamente lidos de forma totalmente isolada em relação aos outros.

Nossa primeira palavra aqui é de cautela. O propósito de estudar os evangelhos em paralelo não é preencher a história em um evangelho com pormenores tirados dos outros. E comum que tal modo de ler os evangelhos siga a tendência de harmonizar todos os detalhes, ofuscando, assim, os próprios aspectos distintivos existentes em cada evangelho inspirado pelo Espírito Santo. Tal “preenchimento” pode ser interessante no nível do Jesus histórico, mas este não é o nível canônico, que deve ser o nosso primeiro interesse.

Há duas razões básicas para pensarmos horizontalmente. Em primeiro lugar, os paralelos muitas

vezes nos darão uma apreciação acerca dos aspectos distintivos de qualquer um dos evangelhos. Afinal de contas, a princípio, são exatamente os aspectos distintivos a razão por que existem quatro evangelhos. Em segundo lugar, os paralelos nos ajudarão a ter consciência dos tipos diferentes de contextos em que os mesmos materiais, ou materiais semelhantes, sobreviveram na vida da igreja. Cada um destes será aqui ilustrado, mas antes temos uma palavra importante acerca das pressuposições.

É impossível ler os quatro evangelhos sem ter algum tipo de pressuposição acerca dos relacionamentos que têm entre si — mesmo se você nunca pensou acerca da questão. A pressuposição mais comum, mas aquela que é a menos provável de ser verdadeira, é que cada evangelho foi escrito independentemente dos outros. Simplesmente há uma quantidade demasiada de evidência clara contra ela para que seja uma opção viável para você enquanto lê.

Pense, por exemplo, no fato de que há um grau tão alto de semelhança verbal entre Mateus, Marcos e Lucas em suas narrativas, bem como na sua maneira de registrar os ditos de Jesus. As semelhanças verbais notáveis não devem nos surpreender no que diz respeito aos ditos daquele que falava como “ninguém falou” (Jo 7.46). No entanto, o fato de essas semelhanças se aplicarem às narrativas é outra coisa diferente — especialmente quando consideramos (1) que, embora essas histórias tenham sido primeiramente contadas em aramaico, nós estamos falando acerca do uso das palavras gregas, (2) que a ordem das palavras em grego é extremamente livre, mas frequentemente as semelhanças se estendem à ordem exata das palavras, e (3) que é altamente improvável que três pessoas em três partes diferentes do Império Romano contassem a mesma história com as mesmas palavras — até mesmo nos casos de pormenores secundários de estilo individual, como preposições e conjunções. Mas é isso que acontece muitas vezes nos três primeiros evangelhos.

Este fato pode ser facilmente ilustrado com a narrativa da multiplicação dos pães para os cinco mil, que é uma das poucas histórias achadas em todos os quatro evangelhos. Observe as seguintes estatísticas:

· Quantidade de palavras usadas para contar a história: Mateus 157 Marcos 194 Lucas 153 João 199

· Quantidade de palavras em comum em todos os três primeiros evangelhos: 53

4. Quantidade de palavras que João tem em comum

com todos os demais: 8 (cinco, dois, cinco mil, tomou pães, doze cestos de pedaços).

5. Porcentagem de concordância:

Mateus com Marcos 59%

Mateus com Lucas 44%

Lucas com Marcos 40%

João com Mateus 8.5%

João com Marcos 8.5%

João com Lucas 6.5%

As seguintes conclusões parecem inevitáveis. João apresenta uma narração claramente independente da história. Ele usa apenas as palavras absolutamente necessárias para contar a mesma história, e até mesmo emprega uma palavra grega diferente para “peixe”! Os outros três já são claramente interdependentes de alguma maneira. Aqueles que conhecem grego reconhecem quão improvável é que duas pessoas, independentemente, contém a mesma história em forma de narrativa e tenham 60% de concordância quanto às palavras usadas, e frequentemente na ordem exata das palavras.

Tome como outro exemplo as palavras de Marcos 13.14 e o paralelo em Mateus 24.15: (“quem lê, entenda”). Essas palavras dificilmente poderiam ter feito parte da tradição oral (o texto cita “quem lê”, e não “quem ouve”; e visto que na sua forma mais antiga [que é o relato de Marcos] não há menção a Daniel, é improvável que se trata de uma palavra de Jesus referindo-se a Daniel). As palavras, portanto, foram acrescentadas no dito de Jesus por um dos evangelistas por causa dos seus leitores. Parece altamente improvável que exatamente o mesmo parêntese teria sido encaixado de forma independente exatamente no mesmo lugar por dois autores que escreviam de forma independente um do outro.

A melhor explicação de todos os dados é aquela que sugerimos anteriormente — que Marcos escreveu seu evangelho primeiro, provavelmente — pelo menos em parte — a partir de suas lembranças da pregação e do ensino de Pedro. Lucas e Mateus tinham acesso ao evangelho de Marcos e o usaram independentemente como a fonte básica para produzir os deles. Além disso, porém, tinham acesso a todo tipo de outros materiais acerca de Jesus, alguns dos quais tinham em comum. No entanto, esse material em comum quase nunca é apresentado na mesma ordem nos dois evangelhos, fato este que sugere que nenhum deles teve acesso ao escrito do outro. Por fim, João escreveu de

forma independente dos outros três. Dessa forma, seu evangelho tem pouco material em comum em comparação com os demais. Notamos, então, que esse é o modo pelo qual o Espírito Santo inspirou a escrita dos evangelhos.

A ajuda que esse conhecimento lhe dará na interpretação dos evangelhos pode ser vista no seguinte exemplo da ARA. Note como o dito de Jesus sobre “o abominável da desolação” aparece quando é lido em colunas paralelas:

Mt 24.15-16 Quando, pois virdes o abominável da desolação de que falou o profeta Daniel, no lugar santo (quem lê, entenda), então, os que estiverem na Judeia fujam para os montes Mc 13.14 Quando, pois virdes abominável da desolação situado onde

não deve estar (quem lê, entenda), então, os que estiverem na Judeia fujam para os montes Lc 21.20.21 - Quando porém, virdes Jerusalém sitiada de exércitos, sabei que está próxima a sua devastação. Então, os que estiverem na Judeia fujam para os montes;

Em primeiro lugar, deve-se notar que esse dito faz parte do discurso do monte das Oliveiras que aparece exatamente na mesma sequência em todos os três evangelhos. Quando Marcos registrou essas palavras, conclamou seus leitores a uma reflexão acerca daquilo que Jesus queria dizer com “o abominável da desolação situado onde não deve estar”. Mateus, também inspirado pelo Espírito, ajudou seus leitores ao tornar o dito um pouco mais explícito. O “abominável da desolação”, ele relembra aos leitores, já fora mencionado por Daniel, e o que Jesus

queria dizer com “onde não deve estar” era “no lugar santo” (o templo em Jerusalém). Lucas, inspirado do mesmo modo pelo Espírito, simplesmente interpretou o dito inteiro, para que seus leitores gentios pudessem ser beneficiados. Realmente ele permite que seus leitores o compreendam! O que Jesus queria dizer com tudo isso era: “Quando vocês virem Jerusalém cercada por exércitos, então saibam que está próxima a sua desolação”.

Dessa forma, podemos ver como a atitude de pensar horizontalmente e o conhecimento de que Mateus e Lucas usaram como base Marcos podem ajudar você a interpretar qualquer um dos evangelhos enquanto o lê. Do mesmo modo, a consciência dá existência dos paralelos entre os evangelhos também nos ajuda a ver como os mesmos materiais às vezes vieram a ser usados em novos contextos na vida da igreja.

Verifiquemos, por exemplo, o lamento de Jesus sobre Jerusalém, que é um dos ditos que Mateus e Lucas têm em comum, mas que não é encontrado em Marcos. O dito é bem parecido, palavra por palavra, nos dois evangelhos. Em Lucas 13.34,35, o dito se encontra em uma longa coletânea de narrativas e ensino de Jesus em sua trajetória para Jerusalém (9.51—19.44; veja Gordon D. Fee; Douglas Stuart, How to Read the Bible Book by Book [2a ed.], p. 292, 293); e segue imediatamente após a advertência acerca de Herodes, a qual Jesus concluiu com a seguinte resposta: “Nenhum profeta deve morrer fora de Jerusalém”. A rejeição do mensageiro de Deus leva ao julgamento de Israel.

Em Mateus 23.37-39, o lamento conclui a coletânea de Jesus de ais contra os fariseus, sendo que o último deles reflete o tema dos profetas sendo mortos em Jerusalém. Você deve notar que o dito tem a mesma razão de ser nos dois evangelhos, embora seja colocado em contextos diferentes.

A mesma questão também se aplica a muitos outros ditos. O Pai Nosso é colocado nos dois evangelhos (Mt 6.7- 13; Lc 11.2-4) em contextos de ensinos sobre a oração, embora o sentido principal de cada seção seja consideravelmente diferente. Note também que em Mateus serve como modelo: “Portanto, orai deste modo”; em Lucas, a repetição é permitida: “Quando orardes, dizei”. De forma semelhante, observe as Bem-Aventuranças (Mt 5.3-11; Lc 6.20-23). Em Mateus, os pobres são “os pobres em espírito”; em Lucas são simplesmente “vocês, os pobres” em contraste com “vocês, os ricos” (6.24). Em tais situações, a maioria das pessoas tende a assumir apenas a metade de um cânon. Os evangélicos tradicionais tendem a ler apenas “os pobres em espírito”; e os ativistas sociais tendem a ler somente “vocês, os pobres”. Insistimos que as duas expressões são canônicas. Num sentido verdadeiro, os pobres verdadeiros são os que se reconhecem empobrecidos diante de Deus. Mas o Deus da Bíblia, que se encarnou em Jesus de Nazaré, é um Deus que pleiteia a causa dos oprimidos e dos privados de direitos civis. Dificilmente podemos ler o evangelho de Lucas sem reconhecer seu interesse por esse aspecto da revelação divina (ver 14.12-14; cf. 12.33,34 com o paralelo em Mateus 6.19-21; ver também Gordon D. Fee; Douglas Stuart, How to Read the Bible Book by Book [2a ed.], p. 289).

Uma palavra final. Se você se interessar por um estudo sério dos evangelhos, precisará recorrer a uma sinopse (uma apresentação dos evangelhos em colunas paralelas). A melhor delas é Synopsis of the Four Gospels, editada por Kurt Aland (Nova York, United Bible Societies, 1975).

Pense verticalmente Pensar verticalmente significa que devemos procurar ter consciência dos dois contextos históricos — o de Jesus e o

do evangelista —, quando lemos ou estudamos uma narrativa ou um ensino dos evangelhos.

Mais uma vez, nossa primeira palavra aqui é de cautela. O propósito de pensar verticalmente não é, em princípio, estudar a vida do Jesus histórico. Realmente, ela deve sempre ser interessante para nós. No entanto, os evangelhos em sua presente forma são a Palavra de Deus para nós; já as nossas próprias reconstruções acerca da vida de Jesus não são. Além disso, não devemos exagerar nessa maneira de pensar. Trata-se apenas de uma chamada à consciência de que muitos dos materiais encontrados nos evangelhos devem seu presente contexto aos evangelistas, e de que a boa interpretação talvez requeira a avaliação de um determinado dito primeiramente no seu contexto histórico original, como um prelúdio apropriado ao entendimento da mesma palavra no seu presente contexto canônico.

Podemos ilustrar esse fato a partir da passagem de Mateus 20.1-16, a parábola dos trabalhadores na vinha, ensinada por Jesus. Nosso interesse é responder à seguinte questão: o que ela significa no seu presente contexto em Mateus? Se a princípio pensarmos horizontalmente, notaremos que Mateus tem, em todos os pontos da parábola, longas seções de material bem semelhante a Marcos (Mt 19.1-30; 20.17-34 é paralelo de Mc 10.1-52). Marcos 10.31 registra o dito:

“Muitos dos primeiros serão últimos, e os últimos serão primeiros”, que Mateus conservou intacto em 19.30. Mas é exatamente nesse ponto que Mateus encaixou essa parábola, que terminou com a repetição desse dito (20.16), mas agora em ordem inversa. Dessa forma, no evangelho de Mateus, o contexto imediato para a parábola é o dito acerca da inversão da ordem entre o primeiro e o último.

Quando observar a parábola propriamente dita (20.1- 15), você notará que termina com a justificativa da sua

própria generosidade, feita pelo proprietário. O pagamento no reino, disse Jesus, não é predicado daquilo que é equitativo, mas sim da graça de Deus! Em seu contexto original, essa parábola provavelmente serviria para justificar a aceitação dos pecadores por Jesus, à luz da contestação dos fariseus contra ele. Eles pensavam que, por “suportarem a fadiga e o calor do dia”, eram dignos de mais pagamento. Deus, porém, é generoso e gracioso, e aceita livremente os pecadores assim como aceita os “justos”.

Uma vez que esse é o contexto original mais provável, como a parábola funciona agora no evangelho de Mateus? A lição da parábola: a generosidade graciosa de Deus para com aqueles que nada merecem certamente permanece a mesma. Contudo, essa lição não mais tem a preocupação de justificar as ações do próprio Jesus. No evangelho de Mateus, isso acontece em outros trechos e de outras maneiras. Aqui, a parábola funciona num contexto de discipulado, em que aqueles que abandonaram tudo para seguir a Jesus são os últimos que se tornaram os primeiros (talvez, de fato, em contraste com os líderes judaicos, consideração que Mateus faz várias vezes).

É claro que muitas vezes o ato de pensar verticalmente revelará que a mesma lição é ensinada em dois níveis. No entanto, a ilustração que acaba de ser dada demonstra quão frutífero esse modo de pensar pode ser para a exegese.

Interpretando os evangelhos como um todo

Uma parte importante do contexto literário é aprender a ver os tipos de preocupações que se circunscreveram na composição de cada um dos evangelhos e que fazem com que cada um deles seja inigualável.

No decorrer deste capítulo, já notamos que, ao ler e estudar os evangelhos, devemos levar a sério não só o interesse dos evangelistas no próprio Jesus — naquilo que

ele fez e disse —, mas também suas razões para contar de novo uma só história para seus próprios leitores. Como notamos, os evangelistas eram autores, e não meros compiladores. Entretanto, o fato de que eram autores não implicava que eram criadores do material; a verdade é bem oposta a isso. Vários fatores proibiam uma maior criatividade; incluindo o próprio fato de as palavras serem as palavras de Jesus, aquele que eles tinham deixado tudo para segui-lo, e a natureza fixa do material no processo da transmissão. Dessa forma, eram autores no sentido de que, com a ajuda do Espírito, criativamente fizeram a estrutura e recompuseram o material a fim de suprir as necessidades de seus leitores. O que nos preocupa aqui é ajudar você, no momento em que lê e estuda os evangelhos, a ter consciência do empenho de cada um dos evangelistas na sua composição e da técnica que usaram.

Havia três princípios operantes na composição dos evangelhos: seletividade, harmonia e adaptação. De um lado, os evangelistas como autores divinamente inspirados selecionaram aquelas narrativas e ensinos que eram apropriados para seus propósitos. Naturalmente, é verdade que o simples zelo pela preservação daquilo que lhes era disponível pode ter sido um daqueles propósitos. Apesar disso, João que tem menos narrativas e discursos — embora sejam estes consideravelmente mais expandidos — nos diz especificamente que foi muito seletivo (20.30,31; 21.25). Essa última palavra (21.25), dita de forma hiperbólica, provavelmente também expressa a situação dos demais evangelhos. Lucas, por exemplo, escolheu não incluir uma seção considerável de Marcos (6.45—8.26).

Ao mesmo tempo, os evangelistas e suas igrejas tinham interesses especiais, que também os levaram a harmonizar e adaptar aquilo que era selecionado. João, por exemplo, nos diz distintamente que seu propósito era patentemente teológico: “para que possais crer que Jesus é o Cristo, o Filho de Deus” (20.31). Esse interesse em Jesus como o

Messias judaico é provavelmente a razão principal por que a vasta maioria do seu material tem a ver com o ministério de Jesus na Judeia e em Jerusalém, em contraste com o ministério quase totalmente galileu nos Sinóticos. Para os judeus, o verdadeiro lar do Messias era Jerusalém. Dessa forma, João sabe que Jesus disse que o profeta não tem honra no seu próprio lar ou na sua própria pátria. Isso foi dito originalmente na ocasião de sua rejeição em Nazaré (Mt 13.57; Mc 6.4; Lc 4.24). No evangelho de João, esse dito é apresentado como uma explicação dada à rejeição do Messias em Jerusalém (4.44) — uma profunda dedução teológica sobre o ministério de Jesus.

O princípio de adaptação também explica a maioria das conhecidas discrepâncias entre os evangelhos. Dentre elas, uma das mais conhecidas, por exemplo, é o relato da figueira amaldiçoada (Mc 11.12-14, 20-25; Mt 21.18-22). No evangelho de Marcos, a história é contada por sua relevância teológica simbólica. Observe que, entre a maldição e a secagem da figueira, Jesus pronuncia um julgamento semelhante sobre o judaísmo ao purificar o templo. Contudo, a história da figueira tinha grande significado para a igreja primitiva também por causa da lição sobre a fé que se pode concluir com base no relato. No evangelho de Mateus, a lição sobre a fé é o interesse exclusivo da história, pois no relato a figueira seca imediatamente após a maldição, o que enfatiza essa lição. Lembre-se de que em cada caso esse modo de contar a história é obra do Espírito Santo, que inspirou os dois evangelistas.

Para ilustrar esse processo de composição numa escala um pouco maior, examinemos os capítulos iniciais de Marcos (1.14—3.6). Esses capítulos são uma obra de arte. São tão bem construídos que muitos leitores provavelmente entenderão a lição de Marcos mesmo sem reconhecerem como ele a expressou.

Há três temas no ministério público de Jesus que são de interesse especial para Marcos: a popularidade com as multidões, o discipulado para uma minoria e a oposição das autoridades. Note com que habilidade de seleção e disposição das narrativas Marcos nos apresenta esses temas. Depois de anunciado o ministério público de Jesus (1.14,15), a primeira narrativa registra o chamado dos primeiros discípulos. Esse tema será elaborado nas seções seguintes (3.13-19; 4.10-12; 4.34-41, et ah); seu interesse maior nos dois primeiros capítulos diz respeito aos dois outros itens. Começando com 1.21 até 1.45, Marcos tem apenas quatro perícopes: um dia em Cafamaum (1.21-28, 29-34), uma breve excursão de pregação no dia seguinte (1.35-39), e a história da cura do leproso (1.40-45). O tema comum do começo ao fim é a rápida propagação da fama e da popularidade de Jesus (ver v. 27-28, 32-33, 37, 45), que culmina quando “Jesus já não podia entrar abertamente numa cidade, mas ficava fora, em lugares desertos [...] as pessoas iam até ele, vindas de todos os lugares”. Tudo parece ofegante; mas Marcos pintou esse quadro com apenas quatro narrativas, mais a repetição da frase “e imediatamente” (1.21, 23, 28, 29, 31,42 [no original — traduzida de várias maneiras em ara]) e a opção por iniciar quase todas as frases com “e” (tradução conservada em arc). (Note que para preservar a língua-alvo a conservação dessas características textuais tendem a ser obscurecidas em traduções contemporâneas, inclusive na nkjv).

Com esse quadro diante de nós, Marcos passa a selecionar cinco tipos diferentes de narrativas que, em seu conjunto, pintam o quadro da oposição e apresentam as razões para a existência dessa oposição. Note que o denominador comum das quatro primeiras perícopes é a pergunta “Por quê?” (v. 2.7,16,18,24). A oposição vem porque Jesus perdoa os pecados, come com pecadores, negligencia a tradição do jejum, e “quebra” o sábado. Este último item, que era considerado pelos contemporâneos de

Jesus o maior insulto à tradição, torna-se evidente quando Marcos acrescenta uma segunda narrativa desse tipo (3.1- 6).

Não queremos sugerir que, em todas as seções de todos os evangelhos, poderemos traçar tão facilmente os interesses do evangelista na sua composição. O que sugerimos, porém, é a necessidade de examinarmos os evangelhos dessa forma.

Algumas observações hermenêuticas Na sua maior parte, os princípios hermenêuticos dos evangelhos são uma combinação daquilo que foi dito em capítulos anteriores acerca das epístolas e das narrativas históricas.

Ensinos e imperativos Depois de fazermos a exegese com cuidado, os ensinos e os imperativos de Jesus nos evangelhos devem ser trazidos para o século XXI da mesma forma como fazemos com os ensinos de Paulo — ou Pedro, ou Tiago — nas epístolas. Até mesmo as questões da relatividade cultural devem ser levantadas da mesma forma. O divórcio dificilmente seria uma opção válida para casais, quando os dois querem ser seguidores de Jesus — consideração esta que é repetida por Paulo em ICoríntios 7.10,11. Numa cultura pós-moderna como a dos Estados Unidos em que um de dois adultos convertidos terá sido divorciado, a questão de um novo casamento provavelmente não deve ser decidida sem consideração e sem solicitude redentora para com os novos convertidos. Nossas primeiras suposições acerca do significado das palavras de Jesus, faladas num contexto cultural inteiramente diferente, devem ser cuidadosamente examinadas. Do mesmo modo, dificilmente teremos um soldado romano, forçando-nos a andar uma milha (Mt 5.41). Contudo, nesse caso, a lição de Jesus, o “extra do

cristão”, de fato é aplicável a qualquer número de situações comparáveis.

Algo importante precisa ser dito aqui. Uma vez que muitos dos imperativos de Jesus aparecem num contexto de exposição da Lei do Antigo Testamento, e uma vez que, para muitas pessoas, eles parecem representar um ideal impossível, uma variedade de truques hermenêuticos tem sido oferecida para evitar esses imperativos como autoridade normativa para a igreja. Não podemos gastar tempo aqui para delinear essas várias tentativas e refutá- las, mas algumas poucas palavras podem ser ditas. (Um excelente resumo é dado no capítulo 6 de: The Method and Message of Jesus’ Teachings, de Stein).

A maior parte desses truques hermenêuticos surgiu porque os imperativos se assemelham à lei — e uma lei tão impossível de ser cumprida! E de acordo com o Novo Testamento a vida cristã é baseada na graça de Deus, e não na obediência à lei. No entanto, ver os imperativos como lei é compreendê-los erroneamente. Não são lei no sentido de que devemos obedecer a ela a fim de nos tornarmos cristãos ou permanecermos cristãos; nossa salvação não depende da perfeita obediência a eles. Pelo contrário, são descrições, em forma de imperativos, daquilo que a vida cristã deve ser por ter Deus nos aceitado anteriormente. Uma ética de não retaliação (Mt 5.38-42) é, na realidade, a ética do reino — para esta era presente. Contudo, ela se baseia no amor não retaliativo de Deus por nós; e no reino será “tal Pai, tal filho” (v. Mt 5.48). E nossa experiência do perdão incondicional e ilimitado de Deus que vem em primeiro lugar, mas deve ser seguida por nosso perdão incondicional e ilimitado dos outros. Alguém já disse que, no cristianismo, a religião é a graça; a ética é a gratidão. Logo, os imperativos de Jesus são uma palavra para nós; mas não são como a lei do Antigo Testamento. Descrevem o amor evidente em nossa nova vida como filhos redimidos e amados por Deus — um amor que, é claro, não é opcional.

Narrativas As narrativas tendem a funcionar de várias maneiras nos evangelhos. As histórias dos milagres, por exemplo, não são registradas para oferecer morais nem para servir de precedentes. Pelo contrário, funcionam como ilustrações vitais do poder do reino irrompendo através do ministério do próprio Jesus. De modo indireto, podem ilustrar a fé, o medo ou o fracasso, mas essa não é a sua função primária. Mesmo assim, histórias como a do jovem rico (Mc 10.17-22 e paralelos) ou como o pedido no sentido de sentar-se à destra de Jesus (Mc 10.35-45 e paralelos) estão colocadas num contexto de ensino, em que a própria história serve como ilustração daquilo que é ensinado. Parece-nos que a prática hermenêutica correta a ser usada nessas narrativas é exatamente igual.

Assim, a lição da história do jovem rico não é que todos os discípulos de Jesus devem vender todas as suas posses para segui-lo. Há exemplos claros nos evangelhos que ilustram que esse não era o caso (cf. Lc 5.27-30; 8.3; Mc 14.3-9). Em vez disso, a história ilustra a lição de quão difícil é para os ricos entrarem no reino, precisamente porque têm compromissos prévios com Mamom e procuram garantir suas vidas com isso. O amor gracioso de Deus, porém, pode operar milagres também com os ricos, como Jesus continua a dizer. A história de Zaqueu (Lc 19.1-10) é uma ilustração disso.

Além disso, podemos ver a importância da boa exegese, que nos permite extrair de tais narrativas a lição que realmente foi ensinada pelo próprio evangelho.

Uma palavra final, importantíssima

Essa palavra também se aplica à discussão anterior' acerca do contexto histórico de Jesus, mas também se inclui aqui por ser tão crucial à questão hermenêutica. A

palavra é esta: ninguém ouse pensar que pode interpretar corretamente os evangelhos sem um claro entendimento do conceito do reino de Deus no ministério de Jesus. Para uma breve introdução, porém boa, a essa questão, veja o capítulo 4 de The Method and Message of Jesus’ Teachings, de Stein. Aqui, poderemos apenas oferecer um breve esboço, com algumas palavras acerca de como isso afeta a hermenêutica.

Em primeiro lugar, você deve saber que o arcabouço teológico básico de todo o Novo Testamento é escatológico. A escatologia tem a ver com o fim, quando Deus encerra a era. A maioria dos judeus nos dias de Jesus seguia a escatologia em seu pensamento. Ou seja, pensavam que estavam vivendo na última virada do tempo, quando então Deus interviria na história e terminaria essa era e introduziria a era do porvir. A palavra grega para o fim que aguardavam é eschaton. Dessa forma, no pensamento deles, ser escatológico significava viver esperando o fim.

[figura] /figuras/entendes-o-que-les/mesa07-fig1.png

Naturalmente, os cristãos mais primitivos compreendiam bem esse modo escatológico de considerar a vida. Para eles, os eventos da vinda de Jesus, sua morte e ressurreição, e o derramamento do Espírito estavam todos

relacionados às expectativas acerca da chegada do fim. Aconteceu assim.

A vinda do fim também significava um novo início — o início da nova era de Deus, a era messiânica. A nova era também se chamava o Reino de Deus, que significava: “o tempo do domínio de Deus”. Essa nova era seria um tempo de justiça (e.g., Is 11.4-5), e os homens viveriam em paz (e.g., Is 2.2-4). Seria um tempo de plenitude do Espírito (J1 2.28-30) quando então a nova aliança apregoada por Jeremias seria realizada (Jr 31.31-34; 32.38-40). O pecado e a enfermidade seriam anulados (e.g., Zc 13.1; Is 53.5). Até mesmo a criação material sentiria os efeitos jubilosos dessa nova era (e.g. Is 11.6-9).

Dessa forma, quando João Batista anunciou que a vinda do fim estava muito próxima, e batizou o Messias de Deus, a escatologia entrou em efervescência. O Messias estava por perto, aquele que introduziria a nova era do Espírito (Lc 3.7-17).

Jesus veio e anunciou com seu ministério que o reino vindouro estava próximo (e.g., Mc 1.14,15; Lc 17.20,21). Expulsou demônios, operou milagres e livremente aceitou os rejeitados e os pecadores — todos esses fatos eram sinais de que o fim se iniciara (e.g., Lc 11.20; Mt 11.2-6; Lc 14.21; 15.1,2). Todos observavam Jesus constantemente para ver se realmente ele em aquele que havia de vir. Ele realmente introduziria a era messiânica em todo o seu esplendor? Mas, de repente, foi crucificado — e as luzes se apagaram.

Mas não! Houve uma continuação gloriosa! No terceiro dia, ressuscitou dentre os mortos e apareceu a muitos dos seus seguidores. Por certo, agora ele “restauraria o reino a Israel” (At 1.6). No entanto, em vez disso, ele voltou ao Pai e derramou o Espírito prometido. E aqui que aparecem os problemas para a igreja primitiva e para nós. Jesus

anunciou que o reino vindouro tinha chegado com sua própria vinda. A vinda do Espírito em plenitude e poder, com sinais e maravilhas, e a vinda da Nova Aliança eram sinais de que a nova era chegara. Mas, aparentemente, o fim dessa era ainda não acontecera. Como deviam entender isso?

Desde os primórdios, a partir do sermão de Pedro em Atos 3, os cristãos primitivos chegaram a reconhecer que Jesus não viera para introduzir o fim “definitivo”, mas o “começo” do fim, por assim dizer. Dessa forma, chegaram a perceber que, com a morte e a ressurreição, e com a vinda do Espírito, as bênçãos e os benefícios do futuro já tinham chegado. Em certo sentido, portanto, o fim já chegara. Num outro sentido, no entanto, o fim ainda não chegara totalmente. Era, pois, 7«, mas ainda não.

Portanto, os cristãos primitivos aprenderam a ser um povo verdadeiramente escatológico. Viviam entre os tempos — ou seja, entre o início do fim e a consumação do fim. A Mesa do Senhor, celebravam sua existência escatológica, ao anunciar “a morte do Senhor, até que ele venha” (ICo 11.26). Já conheciam o perdão divino, livre e integral, mas ainda não tinham sido aperfeiçoados (Fp 3.10-14). Já a vitória sobre a morte era deles (ICo 3.22), mas ainda teriam de morrer (Fp 3.20,21). Já viviam no Espírito, mas ainda viviam no mundo onde Satanás podia atacar (e.g., Ef 6.10-17)./« tinham sido justificados e não tinham nenhuma condenação para enfrentar (Rm 8.1), mas ainda haveriam de ter um julgamento futuro (2Co 5.10). Eram o povo futuro de Deus; tinham sido condicionados pelo futuro. Sabiam seus benefícios, viviam à luz dos seus valores, mas eles, assim como nós, ainda tinham de viver esses benefícios e valores no mundo presente. Dessa forma, o arcabouço teológico essencial para compreender o Novo$c$
  where curso_id = v_curso_id and ordem = 7
    and position('[figura]' in conteudo) = 0;
  update public.aulas set conteudo = $c$[figura] /figuras/entendes-o-que-les/mesa08-fig2.png

Testamento tem a seguinte aparência:

A chave hermenêutica para muita coisa no Novo Testamento, e especialmente para o ministério e o ensino de Jesus, encontra-se nesse tipo de “tensão”. Precisamente porque o reino, o tempo do reinado de Deus, foi inaugurado com a própria vinda de Jesus, somos chamados para a vida no reino, que significa a vida sob seu senhorio. Fomos livremente aceitos e perdoados, mas agora nos dedicamos à ética da nova era, e à concretização dela em nossas próprias vidas e em nosso próprio mundo nesta era presente. Por consequência, quando oramos: “Venha o teu reino”, oramos primeiramente em prol da consumação. No entanto, uma vez que o reino — o governo de Deus — que ansiamos por ver consumado já começou, a mesma oração está cheia de implicações para o presente.

A princípio, deve-se notar que tudo o que foi dito no capítulo 7 sobre o ensino de Jesus é aplicável às parábolas. Por que então as parábolas precisam de um capítulo exclusivo para elas num livro como este? Como essas pequenas histórias, simples e diretas, que Jesus contava podem levantar problemas para o leitor ou para o intérprete? Parece que seríamos suficientemente simplórios se deixássemos de lado a lição do bom samaritano ou do filho pródigo. A simples leitura dessas histórias confronta ou consola o coração.

Apesar disso, é necessário um capítulo especial para discutirmos esse assunto, porque, apesar de todo seu encanto e simplicidade, as parábolas têm sofrido uma triste sorte de interpretações errôneas na igreja, superada somente pelo Apocalipse.

As parábolas na história

A razão para o longo histórico de interpretação errônea das parábolas remonta a algo dito pelo próprio Jesus, como registrado em Marcos 4.10-12 (e paralelos: Mt 13.10-13; Lc 8.9,10). Quando lhe perguntaram acerca do propósito das parábolas, Jesus parece ter sugerido que elas continham mistérios para os de dentro, ao passo que endureciam os de fora. O fato de Jesus ter tomado a atitude de “interpretar” a parábola do semeador de modo semialegórico foi visto como uma licença à teoria do endurecimento e a interpretações alegóricas intermináveis. As parábolas eram consideradas simples estórias para aqueles que estavam de fora, para os quais os “significados verdadeiros”, os “mistérios”, estavam ocultos; estes pertenciam somente à igreja e podiam ser descobertos por meio da alegoria.

Foi assim que um brilhante estudioso, como Agostinho, ofereceu a seguinte interpretação da parábola do bom samaritano (ara):

Um homem descia de Jerusalém para Jericó'. Adão Jerusalém: a cidade celestial da paz, da qual Adão caiu Jerico: a lua, e, portanto, significa a mortalidade de Adão salteadores: o diabo e seus anjos lhe roubarem: a saber, a sua imortalidade lhe causaram ferimentos: ao persuadi-lo a pecar deixando-o semimorto\ como homem ele está vivo, mas morreu espiritualmente; está, portanto, semimorto o sacerdote e o levita: o sacerdócio e ministério do Antigo Testamento o samaritano: diz-se que significa Guardião; logo, há uma referência ao próprio Cristo pensou-lhe os ferimentos: significa restringir o

constrangimento ao pecado óleo\ o consolo da boa esperança vinho: a exortação para trabalhar com um espírito fervoroso

animal, a carne da encarnação de Cristo hospedaria', a igreja dia seguinte', depois da Ressurreição dois denários'. a promessa desta vida e da vida vindoura hospedeiro-, Paulo

Por mais novo e interessante que tudo isso possa ser, podemos ter a certeza de que não é isso que Jesus queria dizer. Afinal de contas, o contexto claramente exige uma compreensão que esteja no domínio dos relacionamentos humanos (“Quem é o meu próximo?”), e não no domínio dos relacionamentos divinos e humanos; e não há motivo para pensar que Jesus já iria predizer a existência da igreja e de Paulo dessa forma obtusa!

Na realidade, seria algo extremamente duvidoso se a maioria das parábolas visasse a um círculo interno em tudo. Em pelo menos três casos, Lucas especificamente diz que Jesus contava parábolas para as pessoas (15.3; 18.9; 19.11) com a implicação clara de que as parábolas podiam ser compreendidas. Além disso, o intérprete da lei, a quem

Jesus contou a parábola do bom samaritano (Lc 10.25-37), claramente a compreendeu, assim como os principais sacerdotes e os fariseus compreenderam a parábola dos agricultores em Mateus 21.45. O problema deles não era com a compreensão da parábola, mas sim com o fato de permitir que ela mudasse seu comportamento!

A dificuldade que às vezes temos de entender as parábolas não se relaciona ao fato de serem alegorias para as quais precisamos de algumas chaves interpretativas especiais. Pelo contrário, essa dificuldade se relaciona com algumas coisas que sugerimos no capítulo anterior sobre os evangelhos. Uma das chaves para entender as parábolas é descobrir o público original para o qual foram pronunciadas; como já notamos, muitas vezes foram transmitidas aos evangelistas sem um contexto.

Se as parábolas não são, pois, mistérios alegóricos para a igreja, o que Jesus queria dizer em Marcos 4.10-12 com o mistério do reino e seu relacionamento com as parábolas? É bem provável que a chave desse dito se encontre num jogo de palavras que foi produzido no aramaico falado por Jesus. A palavra methal, traduzida por parabolê em grego, era usada para uma gama inteira de figuras de linguagem na categoria de enigmas, quebra-cabeças e parábolas, e não apenas se referia à variedade em forma de história, que/é çhamada de “parábola” em português. Provavelmente, o v. 11 significava que o significado do ministério de Jesus (o segredo do reino) não podia ser percebido pelos de fora; era como um methal, um enigma, para eles. Assim, seu discurso em mathelin (parábolas) fazia parte do methal (enigma) de todo o seu ministério dedicado a eles. Olhavam, mas deixavam de ver; escutavam — e até mesmo compreendiam — as parábolas, mas falharam em escutá-las de um modo que os levasse à obediência.

Portanto, nossa exegese das parábolas deve começar com as mesmas suposições que aplicamos para todos os

demais gêneros estudados até aqui. Jesus não estava procurando ser obtuso; tinha a perfeita intenção de ser entendido. Nossa tarefa é, sobretudo, procurar ouvir o que eles ouviram. Mas antes de podermos fazer isso de modo adequado, devemos começar perguntando: o que é uma parábola?

Natureza das parábolas -Variedade dos tipos

A primeira coisa que devemos notar é que nem todos os ditos que rotulamos como parábolas são do mesmo tipo. Há uma diferença básica, por exemplo, entre a história que Jesus conta sobre o Bom Samaritano (uma parábola verdadeira) e o que ele diz sobre o fermento que leveda toda a massa (uma similitude). E as duas ainda diferem do dito: “Vós sois o sal da terra” (metáfora), ou: “Por acaso colhem-se uvas dos espinheiros, ou figos de plantas com espinhos?” (epigrama). No entanto, todos esses tipos podem ser encontrados, de forma esporádica, em discussões sobre as parábolas.

O bom samaritano é um exemplo de uma parábola verdadeira. É uma história, pura e simples, com começo e fim; e, sobretudo, possui um “enredo”. Há ainda outras parábolas desse tipo, que se apresentam em forma de história. São elas: a parábola da ovelha perdida, do filho pródigo, da grande ceia, dos trabalhadores na vinha, do rico e Lázaro, e da dez virgens.

Por outro lado, o que Jesus diz sobre o fermento que leveda a massa se aproxima mais de uma similitude. O que se diz sobre o fermento, ou sobre o semeador, ou sobre o grão de mostarda sempre era algo verdadeiro no que diz respeito ao fermento, à semeadura ou aos grãos de mostarda, respectivamente. Tais “parábolas” se aproximam mais de ilustrações extraídas da vida diária, as quais Jesus usava para ressaltar um argumento.

Ditos, como “Vocês são o sal da terra”, diferenciam-se destes últimos casos. Às vezes, são chamados de “ditos parabólicos”, mas na realidade são metáforas e símiles. Às vezes, parece que funcionam de forma semelhante à similitude, mas sua lição — a razão para serem falados — é consideravelmente diferente.

Deve-se notar que em alguns casos, especialmente no caso dos agricultores maus (Mc 12.1-11; Mt 21.33-44; Lc 20.9-18), uma parábola pode se aproximar bastante da alegoria, em que muitos dos pormenores numa história visam representar outra coisa (como na interpretação errônea que Agostinho fez da parábola do bom samaritano). Mas as parábolas não são alegorias — mesmo que às vezes tenham aspectos que pareçam semelhantes a uma alegoria. A razão pela qual podemos ter certeza disso tem a ver com suas diferentes funções.

Uma vez que as parábolas não são todas do mesmo tipo, não podemos necessariamente estipular regras que abranjam a todas. O que dizemos aqui visa ser aplicado às parábolas propriamente ditas, mas muita coisa que será discutida a respeito delas também se relaciona com os demais tipos.

Como as parábolas funcionam Os melhores indícios quanto à natureza das parábolas se encontram em sua função. Em contraste com os ditos parabólicos, tais como os figos de plantas com espinhos, as parábolas com histórias não servem para ilustrar o ensino prosaico de Jesus com palavras ilustrativas. Também não são contadas como veículos para revelar a verdade — embora claramente acabem fazendo isso. Mais do que isso, as parábolas com histórias funcionam como um meio de evocar uma resposta por parte do ouvinte. Em certo sentido, a própria parábola é a mensagem. Ela é contada para dirigir-se aos ouvintes e cativá- los, a fim de fazê-los

parar e pensar acerca das suas próprias ações, ou de levá- los a dar alguma resposta a Jesus e ao seu ministério.

E essa natureza da parábola, que “conclama a uma resposta”, que desencadeia o nosso grande dilema em sua interpretação. De algumas maneiras, pois, interpretar uma parábola é destruir o que era em sua origem. Ê como interpretar uma piada. Toda a razão de ser de uma piada, e aquilo que a torna divertida, é o contato imediato que o ouvinte tem com ela enquanto é contada. E divertida para o ouvinte exatamente porque ela o “captura”, como se pode dizer. Mas somente pode “capturá-lo” se ele conseguir compreender os pontos de referência na piada. Se precisarmos interpretar a piada tentando explicar os pontos de referência, isso já não vai capturar o ouvinte, e, por conseguinte, tal atitude falhará em provocar a mesma qualidade de risadas. Quando a piada é interpretada, sem dúvida ela passa então a ser entendida, e talvez ainda seja divertida (pelo menos compreendemos aquilo que deveria ter provocado nossos risos), mas com certeza não terá o mesmo impacto. Logo, já não funciona da mesma maneira.

Assim acontece com as parábolas. Foram faladas, e podemos tomar por certo que a maioria dos ouvintes tinha identificação imediata com os pontos de referência que os levaram a captar a lição — ou a ser capturados por ela. Para nós, no entanto, as parábolas estão escritas. Podemos, ou não, captar imediatamente os pontos de referência; e, portanto, elas nunca podem funcionar para nós exatamente como funcionaram para os primeiros ouvintes. Ao interpretá-las, porém, podemos compreender ou o que eles captaram, ou o que nós teríamos captado se tivéssemos estado ali. E é assim que devemos fazer em nossa exegese. A tarefa hermenêutica vai ainda mais além: como podemos resgatar o impacto das parábolas em nossos dias e em nossa própria realidade?

Exegese das parábolas-Descobrindo os pontos

de referência Voltemos à nossa analogia da piada. As duas coisas que prendem o ouvinte de uma piada e que conseguem tirar dele boas risadas são as mesmas duas coisas que cativaram os ouvintes das parábolas de Jesus: seu conhecimento dos pontos de referência, que, por sua vez, fizeram com que o ouvinte reconhecesse o rumo inesperado da história. As chaves para a compreensão são os pontos de referência — aquelas várias partes da história que as pessoas identificam enquanto é contada. Se alguém perde os pontos de referência numa piada, não pode haver nenhum rumo inesperado, porque são eles que criam as expectativas comuns. Se alguém os perde numa parábola, logo o impacto e a lição daquilo que Jesus disse também serão perdidos.

O que queremos dizer com “pontos de referência” pode ser melhor ilustrado a partir de uma parábola de Jesus (Lc 7.40-42), que é registrada em seu pleno contexto original (v. 36-50). No contexto, Jesus foi convidado para jantar com um fariseu chamado Simão. O convite, no entanto, não deve ser considerado uma “honraria para um rabino famoso que visitava o local”. Por certo, a falta de oferecer a Jesus até mesmo a hospitalidade comum daqueles dias era uma atitude que visava ser até certo ponto uma humilhação. Quando a prostituta da cidade consegue chegar à presença dos que jantavam e faz o papel ridículo de prostrar-se diante de Jesus, lavar seus pés com lágrimas e enxugá-los com os cabelos, o fato apenas reforça as suspeitas do fariseu. Jesus não poderia ser um profeta e deixar sem condenação esse tipo de vergonha pública.

Conhecendo os pensamentos dele, Jesus contou ao seu hospedeiro uma história singela. Dois homens deviam dinheiro a um prestamista. Um devia quinhentos denários (um denário era o salário de um dia); o outro devia

cinquenta. Nenhum deles podia pagar, de modo que o prestamista cancelou as dívidas dos dois. A lição: quem, você pensa, teria respondido ao prestamista com a maior demonstração de afeto?

Essa história não precisava de interpretação alguma, embora Jesus passasse a inculcar a moral da história com força total. Há três pontos de referência: o prestamista e os dois devedores. E as identificações são imediatas. Deus é como o prestamista; a prostituta da cidade e Simão são os dois devedores. A parábola é uma palavra de julgamento que exige uma resposta da parte de Simão. Dificilmente este poderia ter deixado de perceber a moral. No fim da parábola, ele já se encontrava totalmente envergonhado. Tal é o impacto de uma parábola.

Devemos notar, ainda mais, que a mulher também ouviu a parábola. Ela também se identificou com a história enquanto era contada. Mas o que compreendera não é o julgamento, mas que Jesus — e, portanto, Deus — a aceita.

Note bem: essa não é uma alegoria. Uma alegoria verdadeira é uma história em que cada elemento significa algo bem diferente da própria história. A alegoria daria um significado aos quinhentos denários, aos cinquenta denários, bem como a quaisquer outros pormenores que se possa descobrir. Além disso, e esse fato é especialmente importante, a moral da parábola não está nos pontos de referência, como estaria numa verdadeira alegoria. Os pontos de referência são apenas aquelas partes da história que trazem o ouvinte para dentro dela, partes com as quais ele deve identificar-se de alguma maneira à medida que a história prossegue. A lição da história encontra-se na resposta pretendida. Nessa parábola, é uma palavra de julgamento contra Simão e seus amigos, ou uma palavra de aceitação e perdão para a mulher.

Identificando o público-alvo

Na ilustração acima, indicamos também a relevância de identificar o público-alvo, uma vez que o significado da parábola tem a ver com o modo como foi originalmente ouvida. Naturalmente, no caso de muitas das parábolas, o público-alvo é descrito nos relatos dos evangelhos. Em tais casos, a tarefa da interpretação é uma combinação de três coisas: (1) ficar sentado e escutar a parábola uma vez após outra, (2) identificar os pontos de referência pretendidos por Jesus, que teriam captado os ouvintes originais, e (3) procurar determinar como os ouvintes originais teriam se identificado com a história, e, portanto, o que eles teriam ouvido.

Vamos experimentar esse sistema com duas parábolas bem conhecidas: a do bom samaritano (Lc 10.25-37) e a do filho pródigo (Lc 15.11-32). No caso do bom samaritano, a história é contada a um intérprete da lei, que, querendo justificar a si mesmo — como diz Lucas — perguntara: “Quem é o meu próximo?”. Ao ler a parábola várias vezes, você notará que não se responde à pergunta de um modo simples, como ela foi feita. Mas, de modo mais marcante, desmascara-se a presunçosa justiça própria do questionador. Este sabe o que a lei diz acerca de amar o próximo como a si mesmo, e está disposto a definir “próximo” em termos que demonstrarão que ele obedece à Lei de forma rigorosa.

Há, na realidade, apenas dois pontos de referência na história — o homem deixado na miséria e o samaritano —, embora outros pormenores da parábola ajudem a produzir o efeito. Duas coisas, em especial, precisam ser notadas: (1) Os dois que passam ao largo são tipos sacerdotais — a ordem religiosa que se coloca em contraste com os fariseus e os rabinos, que são os intérpretes da Lei. (2) Dar esmolas aos pobres era a grande ação dos fariseus. Era assim que amavam o próximo como a si mesmo.

Note, pois, como o mestre da lei vai ser capturado por essa parábola. Um homem cai nas mãos de salteadores no

caminho de Jerusalém para Jerico, um evento bastante comum. Dois tipos sacerdotais descem então pela estrada, e passam ao largo. A história é contada do ponto de vista do homem deixado na miséria, e o mestre da lei desde já tem sido “preparado”. Naturalmente, pensaria no seu íntimo: quem poderia esperar outra atitude da parte dos sacerdotes? A próxima pessoa que descerá será um fariseu, e ele será prestativo ao socorrer o pobre coitado. Mas não, quem o socorre é um samaritano! Você terá de entender quanto desprezo os fariseus tinham para com os samaritanos se quiser escutar aquilo que o intérprete da lei ouviu. Note que nem sequer consegue usar a palavra “samaritano” no fim.

Você percebe o que Jesus fez com esse homem? O segundo grande mandamento era amar o próximo como a si mesmo. O intérprete da lei tinha pequenos sistemas bem predeterminados, que lhe permitiam amar dentro de certos limites. O que Jesus faz é desmascarar o preconceito e o ódio do seu coração, e, portanto, sua falta de obediência a esse mandamento. O “próximo” já não pode ser definido em termos limitados. Sua falta de amor não está no fato de que ele não teria ajudado o homem deixado na miséria, mas sim no fato de que ele odeia os samaritanos (e despreza os sacerdotes). Com efeito, a parábola destrói a questão, mais do que a responde.

Assim também acontece com a parábola do filho pródigo. O contexto é a queixa dos fariseus de que Jesus aceita o tipo errado de pessoa, e toma refeições com elas (Lc 15.1-2). As três parábolas acerca de coisas perdidas que seguem esse episódio são a justificativa que Jesus apresenta para as suas ações. Na parábola do filho perdido, há apenas três pontos de referência — o pai e seus dois filhos. Aqui também a posição que a pessoa ocupava determinava aquilo que ouvia, mas, de qualquer maneira, a lição é a mesma: Deus não somente perdoa livremente os perdidos, como também os aceita, com grande alegria.

Aqueles que se consideram justos se revelam ímpios se não compartilharem da alegria do pai e do filho perdido.

Naturalmente, os que estavam à mesa com Jesus se identificaram com o filho perdido, como todos nós certamente devemos fazê-lo. Mas esse não é o verdadeiro impacto da parábola, que deve ser procurado na atitude do filho mais velho. Ele “sempre estava com o pai”, mas se colocara no lado de fora. Deixou de compartilhar do coração do pai, quando seu amor foi demonstrado pelo filho perdido. E como o que certo amigo disse recentemente: você pode imaginar alguma coisa pior do que voltar para casa e cair nas mãos do irmão mais velho?

Em cada um desses casos, e em outros também, as dificuldades exegéticas que você encontrará terão sua origem principalmente na distância cultural entre você e o público original de Jesus, que talvez leve você a não perceber alguns dos detalhes mais sutis que entram na composição de toda a história. É aqui que você provavelmente precisará de ajuda externa. Mas não negligencie essas questões, porque são os costumes culturais que ajudam a dar vida às histórias originais.

Parábolas "sem contexto" O que se diz, porém, das parábolas registradas nos evangelhos sem seu contexto histórico? Visto que já ilustramos essa preocupação no capítulo anterior, usando a parábola dos trabalhadores na vinha (Mt 20.1-16), faremos aqui apenas uma breve recapitulação. Mais uma vez, trata- se de uma questão de procurar determinar os pontos de referência e o público original. A chave encontra-se em ler várias vezes a parábola até que os pontos de referência apareçam com clareza. E comum que essa leitura também dê ao leitor uma indicação imediata do público original.

Assim, no caso da parábola dos trabalhadores na vinha, há somente três pontos de referência: o dono, os trabalhadores que trabalharam o dia inteiro, e os

trabalhadores que trabalharam uma só hora. Esse fato é facilmente determinado, porque eles são as únicas pessoas focalizadas quando a história chega à sua aplicação. O público original também é facilmente determinado. Quem teria sido “capturado” por uma história como essa? Obviamente, os ouvintes que se identificam com os trabalhadores que trabalharam o dia inteiro, visto serem eles os únicos que são focalizados no fim.

A lição é semelhante à do filho pródigo. Deus é gracioso, e os justos não devem sentir rancor com a generosidade de Deus. No entanto, o que aconteceu nesse presente contexto do evangelho de Mateus é que a mesma lição é agora ensinada a um público novo. No contexto do discipulado, serve como garantia da generosidade de Deus, a despeito da condenação ou do ódio dos outros.

Podemos ver esse mesmo fato na parábola da ovelha perdida em Mateus 18.12-14. No evangelho de Lucas, essa parábola funciona em conjunto com a da dracma perdida e a do filho pródigo como uma palavra aos fariseus. A ovelha perdida claramente representa o pecador, que traz alegria para o céu quando é achado. Mais uma vez, como uma palavra aos fariseus, ela justifica o fato de Jesus aceitar os marginalizados; entretanto, quando é ouvida pelos marginalizados, é uma garantia para eles de que são o objeto da busca promovida pelo pastor amoroso. Em Mateus, a parábola faz parte da coletânea de ditos acerca dos relacionamentos dentro do reino. Nesse novo contexto, a mesma lição é ensinada: o cuidado de Deus para com os perdidos. Mas aqui, os “perdidos” são ovelhas que se “desgarraram”. No contexto de Mateus, trata da questão do que temos feito em favor dos “pequeninos” que têm fé fraca, e que tendem a extraviar- se. Nos v. 6-9, a comunidade de Mateus é advertida no sentido de que nenhum dos seus membros deve ser culpado de fazer um “pequenino” extraviar-se. Por outro lado, nos v. 10-14, a parábola da ovelha perdida lhes conta que devem buscar o

extraviado e trazê-lo de volta, com amor, para o aprisco. A mesma parábola, a mesma lição, mas é contada a um público totalmente diferente.

Parábolas do reino Por enquanto, nossas ilustrações foram tiradas, todas elas, das parábolas de conflito entre Jesus e os fariseus. Há, porém, um grupo muito maior de parábolas — as parábolas do reino — que precisa ser mencionado de modo especial. E verdade que todas as parábolas que já verificamos são também parábolas do reino. Expressam o raiar do tempo da salvação com a vinda de Jesus. Mas as parábolas que aqui temos em mente são aquelas que expressamente dizem: “O reino dos céus é semelhante a...”.

Em primeiro lugar, deve-se observar que a introdução: “O reino dos céus é semelhante a...” não deve ser identificada com o primeiro elemento mencionado na parábola. Ou seja, o reino de Deus não é como um grão de mostarda, ou como um tesouro escondido num campo, ou como um negociante. A expressão literalmente significa: “É assim com o reino de Deus...”. Dessa forma, a parábola em sua totalidade, e não apenas em um dos pontos de referência, ou em um dos pormenores, conta-nos alguma coisa acerca da natureza do reino.

Em segundo lugar, é tentador tratar essas parábolas de um modo diferente do que acabamos de examinar, como se realmente fossem veículos de ensino em vez de histórias que exigem uma resposta. Mas essa seria uma postura abusiva em relação às parábolas. Reconhecemos que as coletâneas divinamente inspiradas em Marcos 4 e Mateus 13, na sua presente disposição, têm o objetivo de nos ensinar acerca do reino. No entanto, essas parábolas originalmente faziam parte da proclamação de Jesus acerca do próprio reino como o reino que raiou com sua própria vinda. Elas mesmas são veículos da mensagem, e requerem

do ouvinte uma resposta ao convite de Jesus e à sua chamada ao discipulado.

Consideremos, por exemplo, a interpretação da parábola do semeador feita por Jesus (Mc 4.3-20; Mt 13.3-23; Lc 8.5- 15), que Marcos corretamente vê como sendo a chave para as demais. Você notará que aquilo que Jesus interpretou são os pontos de referência: os quatro tipos de solo são como os quatro tipos de respostas à proclamação do reino. Mas a lição da parábola é a urgência da hora: “Tenham cuidado com o que vocês ouvem. A palavra tem sido semeada — a mensagem das boas-novas do reino, a alegria do perdão, a exigência e o dom do discipulado. Antes de tudo, escutem, tenham cuidado; sede solo frutífero”. Observa-se, portanto, que a maioria dessas parábolas são endereçadas às multidões como sendo discípulos em potencial.

Visto que essas parábolas realmente são parábolas do reino, vamos encontrá-las proclamando o reino como “já/ainda não”. Seu impacto principal, no entanto, é o “jd\ O reino já veio; a hora de Deus está próxima. Logo, o momento atual é de grande urgência. Semelhante urgência na proclamação de Jesus tem um impacto duplo: (1) O julgamento é iminente; a calamidade e a catástrofe estão às portas. (2) Há, porém, boas-novas: a salvação é oferecida gratuitamente a todos.

Examinemos algumas parábolas que ilustram esses dois aspectos da mensagem.

1. Em Lucas 12.16-20, a parábola do rico insensato foi colocada num contexto de atitudes relativo a posses, à luz da presença do reino. A parábola em si é bastante simples. Certo rico pensa que, por causa do seu muito trabalho, garantiu sua vida, e agora pode descansar e viver em pleno deleite. Mas como diz Jesus em outros trechos: “Quem quiser preservar (i.e., garantir) sua vida, irá perdê-la” (Mc 8.35 e paralelos). Assim, o homem é um insensato no

sentido bíblico — procura viver sem levar Deus em conta. Contudo, a calamidade repentina está prestes a alcançá-lo.

A lição da parábola, você observará, não é a qualidade inesperada da morte. E a urgência da hora. O reino está próximo. A pessoa é insensata quando vive para suas posses, para sua própria segurança, quando o fim está bem às portas. Note como essa interpretação é apoiada pelo contexto. Certo homem quer que seu irmão compartilhe a herança com ele. Jesus, no entanto, recusa-se a envolver-se como árbitro entre eles. Seu argumento é que o desejo de possuir bens é irrelevante à luz do momento atual.

É assim também que devemos entender a mais difícil das parábolas: a parábola do administrador infiel (Lc 16.1-8). Mais uma vez, a história em si é bastante simples. Um administrador de bens estava usurpando o dinheiro do seu senhor, ou esbanjando-o de alguma outra forma. Foi chamado para prestar contas e sabia que tudo para ele tinha se acabado; então conseguiu dar um último golpe num montante enorme. Ele deixou todas as contas dos devedores serem novamente ajustadas, provavelmente na esperança de garantir amizades lá fora. O impacto da parábola, e a parte que a maioria entre nós também tem dificuldade de lidar, é que os ouvintes originais esperam desaprovação. Em vez disso, essa negociata é louvada!

Qual poderia ser a razão de Jesus contar uma história desse tipo? É bem provável que ele esteja desafiando seus ouvintes com a urgência da hora. Se ficam devidamente indignados com semelhante história, mais ainda devem eles aplicar as lições a si mesmos. Seus ouvintes estavam na mesma posição do administrador que via a calamidade iminente, mas a crise que os ameaçava era incomparavelmente mais terrível. Aquele homem agiu (note que Jesus não desculpa sua ação); fez alguma coisa para solucionar sua situação. Para você, também, a urgência da hora exige ação; tudo está em jogo.

2. A hora urgente que exige ação, o arrependimento, também é o tempo da salvação. Assim, o reino que está presente é também boas-novas. Nas parábolas gêmeas de Mateus 13.44-46 (as parábolas do tesouro escondido e da pérola de grande valor), ressalta-se a alegria da descoberta. O reino sobrevém a uma pessoa; outra pessoa o procura. Na sua alegria, as duas liquidam suas posses em troca do tesouro e da pérola. O reino não é o tesouro; tampouco é a pérola. O reino é a dádiva de Deus. A “descoberta” do reino traz alegria indizível. Você notará como esse mesmo tema percorre também as três parábolas das coisas perdidas em Lucas 15.

E assim, pois, que se deve aprender a ler e estudar as parábolas. Não devem ser alegorizadas. Devem ser ouvidas — escutadas como chamadas à resposta a Jesus e à sua missão.

A questão hermenêutica

A tarefa hermenêutica exigida pelas parábolas é inigualável. Também tem a ver com o fato de que, quando foram originalmente contadas, raras vezes precisavam de interpretação. Tinham aplicação imediata para os ouvintes, na medida em que parte do efeito de muitas delas era sua capacidade de “capturar”. A nós, porém, chegam na forma escrita e com necessidade de interpretação, precisamente porque nos falta a compreensão imediata dos pontos de referência que os ouvintes originais tinham. O que faremos então? Sugerimos duas coisas.

1. Como sempre, preocupamo-nos basicamente com as parábolas nos seus contextos bíblicos atuais. As parábolas estão num contexto escrito, e, seguindo o processo exegético que acabamos de descrever, podemos descobrir seu significado, sua lição, com alto grau de exatidão. O que precisamos fazer agora é aquilo que Mateus fez (e.g.,

18.10-14; 20.1-16): traduzir essa mesma lição para nosso próprio contexto.

No caso das parábolas em forma de história, podemos até experimentar narrar de modo novo a história, com novos pontos de referência, de tal maneira que nossos próprios ouvintes possam sentir a ira, ou a alegria, que os ouvintes originais experimentaram. A versão que se segue da parábola do bom samaritano não é defendida como inspirada! Esperamos que ilustre uma possibilidade hermenêutica. Como público-alvo, pressupõe-se uma congregação protestante bem- vestida, da classe média.

Num domingo de manhã, uma família de indivíduos desgrenhados e desleixados estava desamparada ao lado de uma autoestrada. Eles estavam obviamente aflitos. A mãe estava sentada numa mala já muito gasta, os cabelos despenteados, as roupas mal arrumadas, com os olhos parecendo de vidro, segurando uma criancinha malcheirosa, com pouca roupa, que chorava em seus braços. O pai estava sem fazer a barba e usava um macacão. Ele mantinha um olhar de desespero enquanto procurava dar conta de mais duas crianças. Ao lado deles, havia um automóvel já surrado até as últimas, que obviamente acabara de entregar os pontos.

Pela estrada afora, veio um automóvel guiado pelo pastor local; estava a caminho da igreja. E embora o pai da família fizesse sinais frenéticos, o pastor não poderia deixar os membros de sua igreja esperando, de modo que fez de conta que não via a família.

Logo veio outro automóvel, e mais uma vez, o pai acenou freneticamente. Mas o motorista era presidente do clube dos negociantes do local, e estava atrasado para uma reunião estadual dos presidentes do clube, numa cidade próxima. Ele também agiu como se não os tivesse visto, e manteve os olhos fitos na estrada em frente.

O próximo carro que passou era guiado pelo ateu local, que não media palavras contra a religião, e nunca pusera o pé numa igreja, em toda a sua vida. Quando viu a aflição da família, levou-a para o hotel local e pagou uma semana de estadia enquanto o pai procurasse um emprego. Além disso, pagou ao pai as despesas de aluguel de um carro para que pudesse procurar serviço, e deu à mãe dinheiro para comprar alimentos e roupas novas.

Um dos autores experimentou fazer isso em certa ocasião. A reação de espanto e ira deixou claro que seus ouvintes realmente “escutaram” a parábola pela primeira vez na sua vida. Você notará quão leal ao contexto original se tornou esse modo de contar a parábola. O protestante evangélico, naturalmente, pensava no que tinha sido dito sobre o pastor e o presidente do clube. Por certo, alguém do seu próprio grupo viria em seguida. Afinal de contas, sempre falamos sobre o bom samaritano, como se os samaritanos fossem as pessoas mais respeitadas. Nada, porém, seria mais ofensivo para o bom frequentador da igreja do que louvar as ações de um ateu, que é, naturalmente, a situação em que estava o intérprete da lei quando a história foi contada pela primeira vez.

Essa aplicação talvez seja um pouco forte para alguns, e insistimos em que você se certifique de que fez sua exegese com muito cuidado antes de experimentá-la. Nossa experiência, no entanto, é que a maioria de nós tem uma visão super otimista de si mesmo, e recontar algumas das parábolas de Jesus ajudaria a revelar nossa própria falta de perdão (Mt 18.23-25), ou nossa própria ira contra a graça, quando queremos que Deus seja “equitativo” (Mt 20.1-6), ou nosso orgulho por causa da nossa posição em Cristo, em comparação com “a turma dos demais ‘homens maus’” (Lc 18.9-14). Não sabíamos se devíamos rir ou chorar quando ouvimos falar acerca de um professor de escola dominical

que, depois de uma hora de excelente instrução sobre essa última parábola, em que explicara eficientemente os abusos do farisaísmo, terminou com uma oração — de modo bem sério: “Graças a ti, Senhor, que não somos como os fariseus nessa história!”. E tínhamos de lembrar um ao outro que não deveríamos rir demais, a fim de que nossas risadas não dissessem: “Graças a Ti, Senhor, que não somos como aquele professor de escola dominical”.

2. Nossa outra sugestão hermenêutica tem relação com o fato de que todas as parábolas de Jesus são, de alguma maneira, veículos que proclamam o reino. Logo, é necessário que você se deixe imergir no significado do reino no ministério de Jesus. Quando a isso, recomendamos com insistência que você leia George E. Ladd: The Presence of the Future (Grand Rapids, Eerdmans, 1974).

A mensagem urgente do reino tão presente, mas ainda não consumado ainda é necessária em nossos próprios dias. Aqueles que têm procurado garantir sua vida por suas posses precisam escutar, com urgência, a mensagem do juízo iminente, e os perdidos precisam desesperadamente escutar as boas-novas. Como a expressão eloquente de Joachim Jeremias (Rediscovering the Parables [Nova Iorque, Scribners, 1966], p. 181):

Chegou a hora do cumprimento; essa é a nota mais forte entre todas as demais. O homem forte foi desarmado, os poderes do mal devem ceder, o médico chegou aos doentes, o fardo pesado da culpa é removido, a ovelha perdida é trazida para o redil, a porta da casa do Pai está aberta, os pobres e os mendigos são convidados com insistência ao banquete, um senhor cuja bondade é o salário não merecido pago integralmente, e grande alegria invade todos os corações. O ano aceitável de Deus chegou. Surgiu, pois, aquele cuja majestade velada brilha através de cada palavra e cada parábola: o Salvador.

Lei(s): as estipulações da aliança para Israel As narrativas patriarcais encontradas em Gênesis, somam- se outras três narrativas, que definem Israel como um povo. das estão registradas no livro de Êxodo (v. Gordon D. Fee; Douglas Stuart, How to Read the Bible Book by Book [2a ed.], p. 35-37). A primeira se refere à libertação miraculosa (o êxodo) da escravidão no Egito, o mais poderoso império do mundo antigo naquela época (Êx 1— 18); a segunda diz respeito ao retorno da presença de Deus, distinguindo seu povo dos demais povos da terra (Êx 33; 40); e a terceira se refere ao fato de Deus reconstituí- los como um povo dedicado ao seu nome, aos pés do monte Sinai (Êx 19—Nm 10.1Ô). Para nós, é até mesmo difícil imaginar a enormidade da dificuldade envolvida nesse terceiro caso. Aqui há um povo que apenas conheceu a escravidão e a cultura egípcia durante séculos, mas que estava agora sob o domínio de Deus, cuja finalidade era reconstituir totalmente um novo povo na face da terra. Esse povo não apenas devia ser formado como um exército de guerreiros para conquistar a terra prometida de seus ancestrais, como também precisava constituir-se como uma comunidade, que seria capaz de viver unida durante a estadia no deserto e, eventualmente, na terra prometida propriamente dita. Ao mesmo tempo, eles precisavam de direção a respeito de como tinham de ser o povo de Deus — cada um em sua relação com os demais e em sua relação com Deus —, de modo que abandonassem os costumes e a cultura do Egito, e não adotassem os costumes e a cultura dos cananeus, de quem possuiriam a terra.

E esse é o papel da Lei na história de Israel. Era uma dádiva de Deus para o povo o fato de estabelecer o modo como os israelitas tinham de viver em comunidade,

relacionando-se um com o outro, e garantir a relação com Javé, seu Deus, e o culto a ele. Ao mesmo tempo, a Lei estabelecia limites no que diz respeito à relação dos israelitas com as culturas ao redor. Realmente, uma tarefa formidável!

Se nós pretendemos ler e entender bem a Lei, precisamos começar compreendendo seu papel na própria história de Israel. Ao mesmo tempo, precisamos estar conscientes de sua natureza pactuai — porque nossa compreensão — não apenas da Lei, mas também dos Profetas e da própria história do Novo Testamento acerca da nova aliança — depende disso. Assim, o propósito deste capítulo é guiar você a um bom entendimento da natureza e do papel da Lei(s) em Israel, de modo que possamos também nos questionar sobre o papel dessas leis para aqueles, dentre nós, que vivem sob a nova aliança de Deus com seu povo.

O que é a Lei? Para apreciar o papel da lei do Antigo Testamento nas Escrituras, precisamos, em primeiro lugar, enfrentar três questões evocadas pela própria linguagem da “lei” na Bíblia. A primeira questão está na própria palavra “lei”, que tem mais de uma conotação quando usada em toda parte das Escrituras: é usada (1) no plural, para referir-se a leis — são os mais de 600 mandamentos específicos que, como era esperado, tinham de ser mantidos como prova de fidelidade a Deus (e.g., Ex 18.20); (2) no singular, para referir-se a todas as leis em sua coletividade (e.g., Mt 5.18); (3) no singular, para referir-se ao Pentateuco (Gênesis a Deuteronômio) como o “Livro da Lei” (e.g., Js 1.8); (4) no singular — por alguns escritores do Novo Testamento —, para referir-se, em termos teológicos, a todo o sistema religioso do Antigo Testamento (e.g., lCo 9.20); (5) no singular — por algumas pessoas do Novo Testamento —, para referir-se à lei do Antigo Testamento

(no sentido 2 acima) como foi interpretada pelos rabinos (e.g., Pedro em Atos 10.28). Neste capítulo, nosso interesse é, sobretudo, ajudar os cristãos a ler e entender os usos 1 e 2, a fim de que possam conseguir apreciar o que as muitas estipulações que Deus deu a Israel significaram para os israelitas e como podemos melhor entendê-las como cristãos.

A segunda questão tem a ver com o uso 3, o fato de o próprio Antigo Testamento ser muitas vezes referido como “a Lei” (e.g., “a Lei e os Profetas”, em Mt 5.17; Lc 16.16). Duas coisas precisam ser aqui observadas: (1) Os próprios mandamentos são encontrados, quase de forma exclusiva, em apenas quatro dos cinco livros conhecidos como “a Lei”: Êxodo, Levítico, Números e Deuteronômio. (2) Esses livros contêm muitos outros materiais além das listas de leis, e esse material é, sobretudo, narrativo (ver cap. 5). A razão para isso é que a lei da aliança entre Javé e Israel, que começa em Êxodo 20, não pode ser entendida à parte da narrativa em que está inserida — incluindo (especialmente) Gênesis, que, de fato, contém apenas um punhado de mandamentos “básicos”, tais como os de 1.28; 9.4-6; e 17.9, leis que não se limitam especificamente a Israel e à sua aliança especial com Javé. Isso ocorre porque não há uma correspondência exata entre o que poderíamos chamar de “leis” e o que poderíamos chamar de “livros da Lei” no Antigo Testamento.

A terceira questão tem a ver com o problema mais difícil para a maioria dos cristãos no que diz respeito a esses mandamentos: o problema hermenêutico. Como qualquer uma dessas formulações legais e específicas se aplicam a nós, ou a eles? Por ser essa uma questão crucial, começaremos este capítulo com algumas observações acerca dos cristãos e da Lei, que, por sua vez, nos ajudarão na discussão exegética que se segue.$c$
  where curso_id = v_curso_id and ordem = 8
    and position('[figura]' in conteudo) = 0;
end
$migration$;
