-- 304_perspectivas_aberturas_2.sql
-- Fecha a varredura de aberturas iniciada nas migrations 302 e 303: Beaver
-- cap. 35 e Carey cap. 39, as duas últimas das seis leituras cujo bloco de
-- título e caixa de biografia tinham saído do OCR como letra solta.
--
-- Capitular devolvida no Beaver ("OQ uinze séculos" -> "Quinze séculos") e
-- retirado o cabeçalho corrido que o OCR colava no meio do texto. No Carey,
-- separada a nota de procedência, que vinha grudada no primeiro parágrafo.
--
-- Com esta, as SEIS aberturas degradadas das 58 leituras estão corrigidas.
-- Todas transcritas à mão a partir da imagem: as páginas estão nítidas, o que
-- falha é o OCR no tipo pequeno da biografia e no título em itálico.

begin;

update aulas set conteudo = 'R. Pierce Beaver

R. PIERCE BEAVER foi professor emérito da Universidade de Chicago. Ele se especializou em história das missões nos Estados Unidos e, durante 15 anos, atuou como diretor formativo da Missionary Research Library, na cidade de Nova York. Beaver é autor de vários livros, entre eles All Loves Excelling [Todos os amores excede], um registro da iniciativa de mulheres americanas na evangelização mundial.

Extraído de Southwestern Journal of Theology, v. 13, n. 2, primavera 1970. Usado com permissão.

Quinze séculos de ação missionária precederam o aparecimendas missões mundiais protestantes. À ação missionária não começou, portanto, de novo e, de acordo com a teoria católica romana moderna, constitui apenas o último capítulo de uma longa história. Estas páginas apresentam um resumo histórico da estratégia missionária antes de surgirem os esforços protestantes e traçam rapidamente o curso da estratégia protestante. Infelizmente, por falta de espaço, omitiremos por completo as missões católicas romanas modernas. Bonifácio O primeiro exemplo de uma estratégia missionária bem desenvolvida, de acordo com a interpretação do termo no século XX, foi a empregada na missão inglesa ao continente europeu por Bonifácio, no século VIII. Bonifácio pregou aos pagãos germânicos numa língua parecida com a deles, de modo que puderam entendê-lo. Ele foi bastante agressivo: desafiou os deuses deles, destruiu seus santuários, cortou as árvores sagradas e edificou igrejas em locais sagrados. Contudo, teve seus convertidos e os educou e civilizou. Bonifácio fundou mosteiros que não só tinham instituições acadêmicas, como também programas para ensinar agricultura, pastoreio e economia doméstica ao povo.

Isso tornou possível a existência de uma sociedade estável, de UMa igreja bem fundamentada e de um bom sistema de formação cristã. Numa segunda linha de instituições educacionais e de ciências domésticas, Bonifácio trouxe freiras da Inglaterra. Esse foi o primeiro caso de mulheres formal e ativamente engajadas na obra missionária. O clero e os monges foram recrutados do meio do povo, Toda essa atividade foi apoiada pela igreja da Inglaterra. Bonifácio enviava relatórios e pedidos. Ele discutia estratégia com os que haviam ficado em sua pátria, Os bispos, os monges e as freiras enviavam, por sua vez, pessoal, dinheiro e suprimentos a Bonifácio. Também envolveram a missão em orações intercessórias.

Essa verdadeira obra missionária infelizmente deixou de existir Por causa da devastação que invasores causaram ao povo da Inglaterra, À missão no continente transformou-se num verdadeiro instrumento de expansão imperial, tanto política quanto eclesiástica,

pois foi empregada pelos reis francos, por seus sucessores germânicos, pelo imperador bizantino é pelo papa. Em razão disso, os reis escandinavos não permitiam que os missionários do continente entrassem em seus países. Preferiam confiar a evangelização aos missionários ingleses, que eram seus súditos ou não tinham conexões políticas. As Cruzadas À série de guerras europeias contra os muçulmanos, as Cruzadas, dificilmente pode ser considerada uma forma de verdadeira missão. Elas tornaram as missões junto aos muçulmanos quase impossíveis até o dia de hoje por causa da herança de ódio que deixaram em terras islâmicas. Mesmo assim, antes de as Cruzadas acabarem, Francisco de Assis falou com amor ao sultão e criou uma força missionária a fim de pregar em amor e paz. Raimundo Lúlio, o grande franciscano, desistiu de seu status na nobreza da corte de Aragão e dedicou sua vida à obra missionária entre os muçulmanos, conhecido como Louco de Amor. Ele convencia e convertia pela razão, usando o instrumento do debate. Para esse fim, escreveu o seu Magna, com a intenção de responder de maneira convincente a qualquer pergunta ou objeção que pudesse ser feita pelos muçulmanos ou pagãos. Idealizou uma espécie de computador intelectual, em que os diversos fatores podiam ser registrados, e a resposta certa aparecia. Lúlio implorou incessantemente, durante muitas décadas antes de seu martírio, a papas e reis que criassem colégios para o ensino da língua árabe e outras para treinamento de missionários erecomendou-lhes muitos esquemas para o envio deles ao estrangeiro. A expansão colonial O cristianismo só veio a ser uma religião mundial. por estar ligado à expansão dos impérios português, espanhol e francês no período do século XVI ao XVIII. Quando o papa dividiuas terras não cristãs, já descobertas ou a descobrir, entre as coroas de Portugal e Espanha, impôs

257 aos monarcas a evangelização dos povos daquelas terras, bem como a obrigação de estabelecer a Igreja e mantê-la. As missões transformaram-se, portanto, numa função governamental.

Os portugueses construíram um império comercial e, com exceção do Brasil, mantiveram sob seu domínio direto apenas pequenos territórios. Ali suprimiram as religiões étnicas, expulsaram a classe alta, que opunha resistência, e criaram uma comunidade cristã composta dos descendentes mestiços e convertidos das classes inferiores da sociedade.

A Espanha empenhou-se em transplantar o cristianismo e a civilização, ambos de acordo com o modelo espanhol. A exploração cruel acabou com os indígenas do Caribe e estimulou uma luta heroica pelos direitos dos indígenas remanescentes, por parte de Bartolomeu de las Casas e outros missionários. Desde então, a defesa do povo primitivo contra a exploração pelos brancos e pelos governos coloniais tem sido uma importante função das missões. Depois que aquele poderoso esforço aboliu a escravidão e o batismo forçado, os missionários foram transformados em civilizadores e protetores dos indígenas. À missão era estabelecida em regiões remotas, tendo um posto central ao redor do qual se formava uma cidade, para onde os indígenas se dirigiam a fim de fixar residência. Ali havia, quase sempre, uma pequena guarnição de soldados a fim de proteger os missionários e os indígenas cristãos. Postos avançados e cidades menores eram ligados ao posto central. Os indígenas recebiam instrução de catequistas e eram supervisionados por sacerdotes na vida cultual da igreja. Eram ativamente envolvidos na participação dos cultos, servindo como acólitos, cantores e músicos. As festas populares foram cristianizadas, e as festas e jejuns cristãos, introduzidos. Oficiais civis nativos ocupavam diversas funções de supervisão sob o controle cuidadoso dos missionários. Fazendas e sítios foram formados, e os indígenas recebiam as instruções necessárias sobre pastoreio e agricultura. Os indígenas, portanto, foram preservados, civilizados e cristiânizados, e não mortos ou desalojados, como aconteceu mais tarde nos Estados Unidos. Infelizmente, quando o governo percebeu que as missões haviam civilizado os indígenas, elas foram “secularizadas”. Os missionários foram substituídos pelo clero diocesano, geralmente de qualidade inferior e pequeno em número. As autoridades governamentais passaram a dirigir tudo, mas sem ter amor pelo povo. As terras foram distribuídas entre os colonizadores espanhóis, e os indígenas, aos poucos, foram relegados à condição de peões.

A política francesa no Canadá contrastou com a da Espanha. Apenas uma pequena colônia foi criada para servir de base para o comércio e como fortaleza contra os ingleses. Os franceses queriam as peles e outros produtos das florestas e, consequentemente, perturbaram o menos possível a civilização indígena. Os missionários tiveram de desenvolver uma estratégia consoante com essa política. Por isso, conviveram com os indígenas em suas vilas, adaptando-se às condições na medida do possível, pregando, ensinando, batizando, realizando os rituais da igreja, permitindo que os convertidos continuassem a ser índios. Algumas cidades permanentes foram fundadas, com igreja e escola, nas regiões fronteiras ao território francês, mas a maioria dos habitantes viviam ali temporariamente.

Do outro lado do globo, no que veio a ser a Indochina francesa, atual Vietnã, região que passou para o domínio francês bem mais tarde, uma estratégia evangelística radicalmente nova foi idealizada por Alexandre de Rhodes. A inovação foi necessária porque os missionários franceses foram perseguidos e expulsos da região por longos períodos. A evangelização só poderia ser realizada por agentes nativos. Rhodes criou uma ordem de evangelistas nativos leigos que viviam sob voto e conquistavam convertidos aos milhares, Animados com a experiência, Rhodes e seus companheiros fundaram a Sociedade de Missões Estrangeiras de Paris, dedicada à política de recrutar e treinar um clero diocesano, cujos membros constituiriam os agentes principais na evangelização do país e no cuidado pastoral das igrejas, em vez de se tornarem missionários TEssa política obteve enorme sucesso. As estratégias missionárias do século XVII Os primeiros teóricos das missões modernas surgiram no século XVII, associados áquela grande expansão da fé, entre eles José de Acosta, Brancati e Thomas a Jesu, Eles escreveram manuais de princípios e práticas missionárias, descreveram as qualificações dos missionários e os ensinaram a trabalhar com o povo. Em 1622, foi criada em Roma a Sagrada Congregação para a Propagação da Fé, Essa entidade passou então a dar orientação central às missões católicas romanas e criou colégios e institutos para treinamento missionário.

Os corajosos inovadores desse período foram os jesuítas, que seguiram para o Oriente através dos canais portugueses, mas desafiaram as restrições de Portugal. Eram homens de várias nacionalidades e foram os pioneiros modernos na acomodação, aculturação, adaptação ou autoctonia como queiram chamar esse processo. A primeira tentativa deu-se no Japão, onde os missionários adaptaram casas, trajes, a maioria dos costumes e a etiqueta do convívio social japonês. Eles não usaram, no entanto, os termos, conceitos, formas ou rituais xintoístas e budistas na apresentação do evangelho nem no estabelecimento de igrejas. Fizeram grande uso do modo de falar japonês na produção da literatura cristã, impressa na gráfica da missão pelos convertidos japoneses. À parte mais pesada da evangelização e do ensino foi assumida por diáconos e catequistas nativos. Alguns poucos foram admitidos no sacerdócio. Logo surgiu uma grande comunidade cristã. Quando oxógum,no século XVII, temendo agressão estrangeira, fechouo Japão a todos os estrangeiros e perseguiu o cristianismo, milhares de cristãos sofreram o martírio. O cristianismo ocultou-se e sofreu até que o Japão se abriu para o intercâmbio com o Ocidente, dois séculos mais tarde.

Em Madurai, no sul da Índia, uma segunda experiência foi muito além. Roberto de Nobi acreditava que a casta dos brâmanes tinha de ser conquistada Índia para que o cristianismo obtivesse sucesso na Ele se tornou então um cristão brâmance. Vestia-se como guru (mestre religioso), observava as leis e os costumes da casta e aprendeu o sânscrito, De Nobili estudou as principais escolas da filosofia hindu e apresentou a doutrina cristã tanto quanto possível em termos hindus. Ele é um dos pouquíssimos evangelistas a levar um grande número de brámanes à conversão.

À tentativa de acomodação mais notável foi na China, Matteo Ricci estabeleceu uma estratégia, e ela foi desenvolvida por Schalle Verbiest, seus sucessores como dirigentes da missão. Assim como no Japão, os missionários adotaram o estilo de vida do país e os fundamentos da civilização chinesa, mas foram muito além e aos poucos introduziram princípios c doutrina cristãos por meio de conceitos confucionistas. Eles permitiam que os convertidos se envolvessem em rituais relacionados com os ancestrais e com o Estado, considerando-os de caráter social e civil, em vez de religioso. Os missionários exerceram tremenda influência como matemáticos, astrônomos, cartógrafos e mestres em diversas ciências, apresentando assim o conhecimento ocidental aos chineses, fazendo amizade com pessoas influentes e descobrindo oportunidades de apresentar a fé. Eles serviram o imperador em muitos ofícios. Tudo isso tinha um único propósito: abrir o caminho para oevangelho. À estratégia foi coroada de êxito, e desenvolveu-se ali uma grande comunidade cristá,da qual faziam parte até mesmo pessoas influentes que ocupavam cargos importantes.

Outros missionários, entretanto, não conseguiam valorizar nada que não fosse europeu e eram totalmente apegados à terminologia e às práticas tradicionais católicas romanas. Motivados por ciúmes nacionalistas e partidários, atacaram os jesuítas e os acusaram em Roma, que finalmente se pronunciou contra os princípios Jesuítas, proibiu suas práticas e exigiu que todos os missionários que seguissem para o Oriente jurassem conformidade a essas determinações. “Os cristãos foram proibidos de praticar rituais familiares e cívicos. Tornou-se assim impossível que um cristão fosse ao mesmo tempo cristão genuíno e chinês verdadeiro. À profissão da fé cristã parecia atacar as raízes da piedade filial, que erao próprio fundamento da sociedade chinesa. Dois séculos depois, o juramento foi abolido, e os rituais modificados, permitidos. Os jesuítas perderam a batalha, mas venceram a guerra. Hoje, quase todos os missionários de todas as igrejas reconhecem a necessidade da acomodação. Os puritanos da Nova Inglaterra: missões aos índios americanos À participação dos protestantes em missões mundiais começou cedo no século XVII, simultancamente com a obra evangelística dos capelães da Companhia das índias Orientais Holandesas e as missões da Nova Inglaterra entre os indígenas americanos. Às missões eram uma atividade da companhia comercial, porém muitos de seus capelães foram autênticos missionários. Eles tiveram pouca influência na estratégia missionária posterior, mas foram as missões dos puritanos entre os índios que forneceram às missões posteriores inspiração e exemplos. O alvo dos missionários era pregar o evangelho de maneira tão efetiva que os indígenas se convertessem, aceitassem a salvação individualmente e se reunissem em igrejas onde pudessem ser alimentados na fé debaixo de uma disciplina estrita. À intenção era transformar o indígena num cristão do mesmo tipo e com o mesmo caráter do puritano inglês, membro de uma igreja congregacional. Isso implicava civilizar o indígena de acordo com o modelo britânico.

A evangelização foi o primeiro item na estratégia. À pregação constituía o “grande meio” e era suplementada pelo ensino. A maioria dos missionários seguia o exemplo de John Eliot e começava com a pregação pública, embora Thomas Mayhew Jr. obtivesse muito êxito em Martha''s Vineyard, começando com uma aproximação lenta e individual. Pesados sermões doutrinários sobre a ira de Deus e os sofrimentos do inferno, iguais aos que seriam apresentados a uma igreja inglesa, eram dirigidos aos indígenas.

David Brainerd, porém, à semelhança dos morávios, pregava o amor de Deus mais que sua ira. Seu ministério conduziu muitos homens e mulheres ao arrependimento,

O segundo ponto da estratégia consistiu em reunir os convertidos em igrejas, mas os novos cristãos tinham de passar por longos anos de experiência antes que as primeiras igrejas fossem organizadas, mas na segunda fase das missões indígenas, na década de 1730, essa demora já não era mais imposta, e as igrejas foram rapidamente reunidas e organizadas. Antes e depois da organização das igrejas, os convertidos recebiam instruções e eram disciplinados na fé.

A terceira ênfase estratégica foi o estabelecimento de cidades cristãs. John Eliot e seus colegas missionários acreditavam que a segregação e o isolamento eram necessários para que os convertidos crescessem na graça. Elestinham de ser removidos da influência perniciosa de seus irmãos pagãos e dos homens brancos ruins. Pensava-se que em “cidades puramente cristãs de índios fiéis” os novos membros poderiam conviver em harmonia sob a disciplina estrita e a educação cuidadosa dos missionários brancos e dos pastores e professores indígenas. Isso garantia o que Cotton Mather chamava “um modo de vida mais decente e inglês”.

A cristianização e a civilização seriam simultâneas e indistinguíveis. Eliot implantou em suas cidades uma forma bíblica de governo baseada em Exodo 18, mas a Corte Geral de Massachusetts, que deu a terra e construiu a igreja e a escola, em 1658 designou comissários para supervisionarem as cidades. Dentro delas, os indígenas viviam sob uma aliança firmada entre eles e o Senhor, e tanto a vida pessoal quanto a vida comunitária eram reguladas por leis influenciadas pelos ensinos bíblicos.

A maior parte das cidades dos índios cristãos não conseguiu sobreviver à devastação da Guerra do Rei Filipe, em 1674, mas a estratégia da cidade cristã especial ressurgiu quando John Sergeant fundou a missão de Stockbridge, em 1734, Stockbridge não era um lugar tão fechado quanto aquelas primeiras cidades. Havia

A iStÓrIA da estratégia MisSIONárIA constante movimento entre a cidade e à Noresta, até mesmo de grandes distâncias, Os cristãos de Stockbridge podiam ser, portanto, agentes evangelísticos em seus relacionamentos naturais.

Não importa o que tenha sido alcançado no desenvolvimento do caráter cristão nas primei. ras cidades, o fato é que nenhuma influência evangelística podia ser exercida por seus habitantes, pois estavam separados dos outros indígenas. Durante o século XIX e início do XX, os missionários entre os povos primitivos da África e das ilhas continuavam enamorados da ideia de garantir a pureza da fé e da conduta dos convertidos por meio da segregação em vilas e distritos cristãos. Essa prática teve como efeito alienar os cristãos de seu próprio povo, criando uma espécie de sociedade “mestiça”, nem nativa nem europeia, e impedindo qualquer impacto evangelístico sobre o restante da população. Um povo separado não pode contagiar os outros com sua fé.

No centro de cada cidade ou posto missionário havia uma igreja com uma escola ao lado. Os sermões aos domingos e as reuniões de oração, a catequização e a educação elementar em geral, tudo se inclinava a educar o convertido na fé e na civilização.

O Indian Catechism [Catecismo indígena], de John Eliot, foi o primeiro livro publicado numa língua indígena americana. Usava-se tanto o vernáculo quanto a língua inglesa. O inglês facilitava aos indígenas o ajustamento à sociedade dos brancos, enquanto o idioma nativo era mais eficiente para a compreensão das verdades cristãs. Eliot criou livros de texto em ambos os idiomas.

Os índios aprenderam a ler e escrever e a fazer as operações mais simples de aritmética, além de receberem instrução bíblica e religiosa. Técnicas agrícolas e artesanato doméstico também foram introduzidos para que os índios pudessem obter sustento num estilo de vida estabelecido e civilizado. No segundo século dessa missão, considerações estratégicas levaram John Sergeant a introduzir o colégio interno, a fim de que os jovens pudessem ser totalmente separados

R. Pierce Beaver da velha vida e criados dentro da nova. Essa instituição também víria a ser também um recurso estratégico importante para as missões do século XIX.

Os puritanos da Nova Inglaterra merecem o crédito de nunca ter duvidado do poder transformador do evangelho nem da capacidade em potencial dos indígenas. Eles esperavam que pelo menos alguns alcançassem o padrão dos ingleses. Por isso, foi preciso mais que a educação rudimentar das cidades. Alguns jovens promissores foram enviados à Boston Latin Grammar School e uns poucos foram matriculados na Faculdade Indígena da Universidade Harvard. O colégio interno de Sergeant, em Stockbridge, e a escola de Eleazer Wheelock, em Lebanon, Connecticut foram alguns dos esforços mais bem elaborados em prol de uma educação em alto nível.

O culto, a educação espiritual e a educação secular, tudo exigia uma literatura vernácula de dimensões mais ou menos extensas. Para isso, Eliot produziu uma Bíblia e criou uma biblioteca variada, para a qual alguns de seus colegas contribuíram.

O recrutamento e treinamento de pastores e professores nativos foram absolutamente fundamentais para a estratégia missionária da Nova Inglaterra. Tanto os missionários quanto seus patrocinadores perceberam que apenas os agentes nativos podiam evangelizar com eficiência e proporcionar cuidado pastoral ao seu povo. Em 1700, havia 37 pregadores indígenas em Massachusetts, Infelizmente, as antigas cidades indígenas cristãs entraram em decadência por causa da contínua pressão dos brancos. Com isso, diminuiu também a oferta de pastores e professores até a extinção. É Os efeitos mais duradouros das missões indígenas dos séculos XVII e XVI talvez fossem dois. Primeiro: inspiraram numerosas vocações missionárias, quando as histórias de Eliote de Brainerd foram lidas. Segundo: proporciona-ram ao grande empreendimento protestante no estrangeiro seu programa estratégico inicial, Constava desse programa evangelização por

261 (o meio da pregação, organização de igrejas, educação com vistas ao crescimento cristão, processo de civilização em termos europeus, tradução de Bíblias, produção de literatura, uso da língua vernácula e recrutamento e treinamento de pastores e professores nativos. A Missão Dinamarquesa de Halle Às missões americanas entre a população indígena foram sustentadas por sociedades missionárias organizadas na Inglaterra e na Escócia, mas os missionários não foram enviados a partir da Grã-Bretanha. À primeira missão a enviar missionários da Europa foi a Missão Dinamarquesa de Halle. Em 1705, o rei da Dinamarca começou a enviar missionários luteranos alemães à colônia de Tranquebar, no litoral do sudeste da Índia. O líder pioneiro Bartolomeu Ziegenbalg desenvolveu uma estratégia que se tornou um legado para as futuras gerações de missionários. Contudo, ele estava muito à frente de seu tempo, sob muitos aspectos. Ele destacavao culto, a pregação, a catequese, a educação, o trabalho de tradução e a produção de literatura vernácula. Ziegenbalg foi pioneiro no estudo da filosofia e da religião hindu, percebendo a grande importância desse conhecimento para a evangelização e para o crescimento da igreja, mas as autoridades na Alemanha negaram o valor dessa atividade. Essa missão logo acrescentou o trabalho médico ao programa. Também foi a primeira a usar a poesia tâmil no culto.

O mais famoso dentre os missionários de Halle, depois de Ziegenbalg, foi um dos últimos: Christian Frederick Schwartz, que dedicou sua vida ao ministério na parte sul da Índia controlada pelos ingleses. Ele exerceu enorme influência sobre os indianos de todas as religiões e europeus de diversas nacionalidades, militares e civis, Sua estratégia era singular e não planejada. Embora fosse um europeu na aparência, Schwartz realmente se transformou num guru amado e respeitado por todos. Pessoas de todas as religiões e castas reuniam-se à sua volta como discípulos, sem levar em conta. as diferenças sociais que havia entre elas.

am A NitÓIA dá estrAtógIa MNISSTONAFIA

Qu As missões morávias A estratégia mais notável aplicada no século XVII foi a da Igreja Morávia, desenvolvida sob a direção do conde Zinzendorfe do bispo Spangenberg. Em 1734, começou-se a enviar missionários aos povos mais desprezados e negligenciados. Esses missionários deviam sustentar-se por conta própria. À proposta levou à criação de indústrias e negócios que não só mantinham a obra, mas também colocavam os missionários em íntimo contato com o povo. Esse sistema de automanutenção, porém, não podia ser aplicado aos índios americanos, por isso as colônias comunais, como as de Bethlehem, na Pensilvânia, e Salém, na Carolina do Norte, foram fundadas com base numa grande variedade de atividades artesanais, cujo lucro sustentava a missão.

Os missionários morávios foram instruídos a não aplicar a “medida de Herrnhut” (isto é,os padrões dos morávios alemães) aos outros povos ea ficar alertas para reconhecer as principais qualidades e características concedidas por Deusa esses povos. Além disso, os missionários deviam atuar como cooperadores do Espírito Santo. Deviam ser principalmente mensageiros, evangelistas e pregadores. Em vez de destacar as pesadas doutrinas teológicas, estavam incumbidos de contar a história simples do evangelho do amor de Deus e agir para conciliar os nativos em Cristo, nosso Salvador, que viveu e morreu por toda a humanidade. Na providência de Deus, chegaria a época em que o Espírito Santo introduziria convertidos na Igreja em grande quantidade. Enquanto isso, os mensageiros missionários iriam colher os primeiros frutos. Se não fossem ouvidos, deveriam partir para outro lugar. Na verdade, os missionários só iam embora quando perseguidos ou expulsos. Eram notavelmente pacientes e não desistiam com facilidade. O Grande Século das missões protestantes Dessas iniciativas pioneiras, surgiu o grande empreendimento missionário protestante no estrangeiro do século XIX, Ele tomou forma inicial na Inglaterra com a fundação da Sociedade Missionária Batista por William Carey, em 1792. À organização havia começado nos Estados Unidos em 1787, e agora havia cerca de duas dezenas, todas tendo por objetivo a evangelização mundial, Contudo, os assentamentos nas regiões recém-desbravadas do território americano e os índios absorviam todos os seus recursos. Um movimento estudantil, em 1810, resolveu finalmente o problema e se lançou às missões estrangeiras com a formação da Junta Americana de Comissionados para Missões Estrangeiras. À Convenção Trienal da Denominação Batista para Missões Estrangeiras foi organizada a seguir, em 1814, e depois, em 1816, a Sociedade Unida de Missões Estrangeiras.

Às novas sociedades e juntas começaram seu trabalho com pressuposições e métodos estratégicos herdados das missões entre os indígenas americanos e da Missão Dinamarquesa de Halle. Durante muitos anos, os diretores nacionais pensaram saber tudo sobre o trabalho a ser executado, e instruções detalhadas eram passadas às mãos de cada missionário que embarcava para o campo. Cerca de meio século depois, descobriu-se que os experimentados missionários no campo podiam formular melhor a estratégia e a política, que podiam ser então ratificadas pela junta no país de origem. Em 1795, houve um choque de estratégias entre dois homens de forte personalidade na Sociedade Missionária de Londres. Um deles queria enviar missionários ordenados e de elevado nível cultural a países de civilização e religiões desenvolvidas. O outro queria enviar missionários artesãos, submissos a um superintendente ordenado, aos povos dos mares do Sul, para cristianizá-los e civilizá-los. Os dois objetivos acabaram sendo aceitos.

Mesmo em países de cultura elevada, como a Índia e a China, os missionários acentuaram o objetivo “civilizador”, como seus colegas em regiões primitivas, por considerarem a cultura local degenerada e supersticiosa uma barreira à cristianização, Durante as primeiras décadas não houve qualquer debate sobre a legitimidade da ênfase na função civilizadora das missões. Houve debate apenas acerca das prioridadesso que vem primeiro, cristianização ou civilização? Alguns argumentavam que um certo grau de civilização era necessário para ajudar o povo a entender e aceitar a fé. Outros argumentavam que se podia começar com a civilização, uma vez que o evangelho inevitavelmente produzia um desejo de civilização. Muitos acreditavam que os dois itens interagiam mutuamente e podiam ser igual e simultaneamente destacados.

A Índia logo recebeu o maior grau de atenção das juntas e sociedades missionárias, ca estratégia e táticas ali desenvolvidas foram copiadas e aplicadas em outras regiões. O trio batista “Serampore” de Carey, Marshman e Ward, teve grande influência no período inicial. Embora procurasse conversões individuais, Carey desejava também promover o crescimento deuma igreja independente, bem sustentada por leigos alfabetizados que lessem a Bíblia e administrada e pastoreada por um ministério nativo culto. Esse gênio autodidata não se contentouem criar escolas elementares, mas fundou uma faculdade. O rei da Dinamarca (Serampore era uma colônia dinamarquesa) deu-lhe licença para a criação de uma faculdade, que permitia o funcionamento de cursos superiores de teologia, cujos diplomas seriam reconhecidos. Em Serampore, havia escolas para os indianos cas crianças estrangeiras. O vasto programa detradução e impressão da Bíblia não apenas nas línguas vernáculas indianas, mas até em chinês ressaltava a alta prioridade dessa obra entre todos os protestantes. Outras publicações foram produzidas para as igrejas. O trio também demonstrou a importância da pesquisa acadêmica para ação e a estratégia missionárias, produzindo materiais linguísticos necessários a todos cassumindo a liderança no estudo do hinduísmo,

Além disso, os três homens trabalharam pela transformação da sociedade com o impacto do evangelho e criaram um poderoso método de reforma social, que pressionava o governo colonialista e conduzia os hindus a considerações esclarecedoras sobre velhos erros e sua eliminação.

Esses homens foram influentes na abolição do entree (ato em que a viúva éra queimada viva na pira crematória de seu marido), da prostituição nos templos e outros costumes desumanos, Carey também introduziu o jornalismo moderno, publicando jornais e revistas em bengali e inglês. Ele estimulou o renascimento da literatura bengali. Sem dúvida, a tarefa da missão com base em Serampore foi bastante abrangente.

À semelhança de Roberto de Nobili antes dele, o escocês Alexander Duff acreditava que o povo indiano em geral só poderia ser ganho para Cristo se a casta brâmane fosse a primeira a ser levada a nosso Senhor. Ele tentou ganhar os jovens brâmanes por meio de um programa de educação superior na língua inglesa. Onde ele obteve amplo sucesso, outros falharam, porém sua iniciativa resultou numa forte tendência de se criar escolas e faculdades em língua inglesa. Elas produziram poucos convertidos, mas deram aos cristãos das classes inferiores uma oportunidade de progresso social e econômico que contribuiu para o bem-estar das igrejas. Para satisfação do governo colonial, produziram também funcionários que falavam inglês, utilizados no serviço civil e nas casas comerciais. Essa educação logo consumiu grande parte dos recursos das missões.

Ao mesmo tempo, sem qualquer planejamento estratégico, desenvolveram-se imensos postos missionários centrais bem povoados, onde os convertidos se aglomeravam na dependência econômica e social dos missionários. Se alguém aceitasse o cristianismo sem que houvesse a conversão de todo o seu grupo social, ele era expulso da família e perdia seus meios de sobrevivência. Para manter tais pessoas vivas, elas eram empregadas como funcionários, professores e evangelistas do centro. À igreja tomou um aspecto de superprofissionalização, e os leigos eram pagos para desempenhar tarefas que cabiam a voluntários. Essa prática defeituosa foi repassada a missões de outras localidades. No posto principal, ficavam a igreja-mãe, as escolas, o hospital e geralmente a gráfica. Um missionário era o pastor e dirigente da comunidade.

e En Esse sistema tinha pouco espaço para um pastor nativo, como queria William Carey,e não havia igrejas organizadas nas vilas situadas a mais de 80 quilômetros interior adentro, apenas pontos de pregação. Em 1854-1855, Rufus Anderson realizou uma viagem de verificação à Índia e ao Ceilão (atual Sri Lanka). Ele levou os mis= sionários da Junta Americana com a tarefa de acabar com os imensos postos centrais, organizar igrejas nas vilas e ordenar pastores nativos para essas igrejas. Determinou também que a educação na língua vernácula fosse a regra geral, e a educação em inglês, a exceção. Os estrategistas missionários do século XIX Os dois maiores teóricos e estrategistas de missões do século XIX também foram os diretores executivos das maiores agências missionárias. Henry Venn ocupou o cargo de secretário geral da Sociedade Missionária Londrina, e Rufus Anderson, o de secretário para o estrangeiro da Junta Americana de Comissionados para Missões Estrangeiras. À estratégia missionária de Anderson dominou a obra missionária americana por mais de um século, enquanto à de Venn se destacou no cenário britânico. Os dois homens chegaram, cada um por sua vez, praticamente aos mesmos princípios básicos e nos anos posteriores acabaram influenciando um ao outro. Juntos, eles estabeleceram como objetivo estratégico reconhecido da missão protestante a famosa “tríplice fórmula da autonomia”, com a qual as missões britânicas e americanas consentiram desde meados do século XIX até a Segunda Guerra Mundial. O alvo das missões era fundar igrejas e patrocinar seu desenvolvimento, a fim de que viessem a ser autogovernadas, autossuficientes e autônomas na propagação do evangelho.

Rufus Anderson era congregacionalista, e Venn, episcopal anglicano, mas ambos edificaram a igreja regional de baixo para cima, Venn queria que a nomeação de um bispo fosse o remate do processo do desenvolvimento, pois assim haveria um clero nativo adequado euma igreja sustentada pelo povo. Anderson protes-

A história da estratágia missionária tava contra o destaque dado à “civilização” é contra a tentativa de reformar a sociedade da noite parao dia, Para ele, essa mudança deveria ser resultado da ação do fermento do evangelho na vida da nação, Ele fundamentou sua estratégia nos métodos de Paulo, conforme registra o Novo Testamento.

De acordo com Anderson, a tarefa do missionário era pregar o evangelho e reunir os convertidos em igrejas. Ele seria sempre um evangelista, e nunca um pastor ou dirigente. As igrejas tinham de ser organizadas imediatamente com os convertidos que demonstrassem mudança de vida em relação a Cristo, sem aguardar que atingissem o padrão esperado dos cristãos americanos com 2 mil anos de passado cristão. Essas igrejas tinham de ser dirigidas por pastores nativos e desenvolver uma política própria, local e regional. Os missionários seriam os conselheiros, irmãos mais velhos na fé para os pastores e o povo.

Anderson e Venn ensinavam que, quando as igrejas estivessem funcionando bem, os missionários deveriam partir para “regiões mais remotas” e recomeçar o processo evangelístico. À questão principal da fundação de igrejas deveria ser evangelização e missões. Às igrejas se engajariam espontaneamente na evangelização local e na missão de enviar missionários a outros povos. Uma missão deveria produzir outra missão. No conceito de Anderson, a educação na língua vernácula teria apenas o propósito de servir a igreja ou desenvolver um grupo de leigos de alta qualidade e um ministério adequadamente treinado. Todas as formas auxiliares de trabalho deveriam ser apenas para a evangelização e para a edificação da igreja.

As missões britânicas resistiram à opinião de Anderson sobre a educação no idioma vernáculo. Todavia, de modo oficial ou não, as missões americanas adotaram a estratégia dele ena teoria se apegaram ao seu sistema por mais de um século, Contudo, depois de sua morte passou-se a enfatizar a educação secundária e superior em língua inglesa num grau ainda maior. Isso se deu em parte por causa do darwinismo ii social, que converteu os americanos à doutrina do progresso inevitável e levou à substituição da antiga escatologia pela ideia de que o Reino de Deus chegaria por influência de institui ções cristãs, como as escolas. Também no fim do século XIX, um segundo grande objetivo estratégico foi acrescentado, de maneira mais ou menos explícita, à tríplice fórmula da autonomia, a saber, a fermentação e transformação da sociedade por efeito dos princípios cristãos e do espírito cristão do serviço, infundidos na vida comum. Os colégios e faculdades seriam essenciais para se atingir esse objetivo.

John L. Nevius, missionário presbiteriano em Shantung, idealizou uma estratégia que modificou um pouco a de Anderson, dando mais responsabilidade aos leigos. Ele defendia a ideia de deixar o leigo em sua profissão ou negócio e em seu lugar costumeiro na sociedade. Ele devia ser encorajado a participar como voluntário, um evangelista não remunerado. Nevius também defendia um estudo bíblico constante e uma mordomia rigorosa em combinação com o trabalho voluntário e propôs um governo eclesiástico simples e flexível. Seus irmãos na China não adotaram seu sistema, porém os missionários na Coreia fizeram uso dele com espantoso sucesso. Uma mentalidade colonialista Apesar da adesão permanente declarada à fórmula de Anderson-Venn, houve uma grande mudança na mentalidade missionária e, consequentemente, na estratégia do último quarto do século XIX. Sob a influência de Venn, as missões britânicas na África Ocidental buscaram: 1) a criação de uma igreja independente, com clero próprio, que evangelizasse o interior do continente; 2) a criação de uma elite africana, isto é, uma intelectualidade e uma classe média que formasse uma sociedade e uma economia que sustentassem essa igreja e sua missão, Quase imediatamente após o fim da liderança de Venn, os missionários executivos e de campo adotaram o ponto de vista de que os africanos eram inferiores e não conseguiriam fornecer uma a liderança ministerial, tendo esta de ser então indefinidamente mantida pelos europeus. O intelectual é o homem de negócios da classe média africana foram desprezados. Essa opinião imperialista constituiu uma variante eclesiástica do apego crescente à teoria da “responsabilidade do homem branco” e reduziu a igreja nativa a uma colônia da igreja estrangeira que a implantara.

Algo muito semelhante ocorreu na Índia, na década de 1880. Os americanos e outros foram contagiados pela mentalidade colonialista dos britânicos. Às missões germânicas, sob a orientação de seu principal estrategista, o professor Gustav Warneck, desejavam simultaneamente a criação das Volkskirchen, as igrejas nacionais, mas até que seu desenvolvimento pleno fosse atingido, as igrejas seriam mantidas sob a autoridade dos missionários. O paternalismo deformou o desenvolvimento. Desse modo, todas as missões, na passagem do século, eram paternalistas e colonialistas. Essa infeliz situação durou até que alguns estudos e pesquisas realizados para a Conferência Missionária Mundial de Edimburgo, em 1910, subitamente destruíram a complacência e a inércia. Eles revelaram que a igreja nativa era um fato e se mostrava indócil sob o domínio paternalista. Em razão disso, depois da conferência houve um tremendo impulso no sentido de a organização missionária devolver a autoridade para a igreja, e praticamente todas as juntas e sociedades pelo menos se comprometeram com esse ideal. Evangelismo, educação e medicina Em resumo, a estratégia missionária do século XIX (até a Conferência de Edimburgo, em 1910), tinha por alvo as conversões individuais, a fundação de igrejas e a transformação social com base em três tipos principais de ação, que vieram a ser conhecidos como evangelização, educação e medicina. À evangelização incluía a pregação em todas as suas formas, a organização de igrejas e o apoio a estas, tradução de Bíblias, produção de literatura e distribuição de Bíblias e literatura.

Na área da educação, as escolas industriais destacaram-se no começo, mas acabaram abandonadas por causa do desejo de uma educação acadêmica. Por volta do final do século, um vasto sistema educacional existia nos países asiáticos, indo do jardim de infância à faculdade até mesmo de medicina e de teologia. A África, no entanto, foi negligenciada no que se refere à educação secundária e superior.

Os primeiros médicos que seguiram parao estrangeiro foram enviados a missão principal de cuidar das famílias dos outros missionários, mas logo se descobriu que o serviço médico junto ao povo em geral despertava boa vontade e abria as portas para a evangelização. Porisso, ele veio a tornar-se um ramo importante da obra missionária. Só em meados do século XX é que os serviços de saúde prestados em nome e no espírito do Médico dos médicos passaram a ser considerados em si mesmos uma forma dramática de pregar o evangelho. Muito antes disso, porém, até mesmo o missionário evangelístico rural já levava consigo uma maleta de médico em suas andanças.

Com esse mesmo espírito de ajuda geral e cultivo da boa vontade, além de querer melhorar a base econômica da igreja, os missionários introduziram aves domésticas, gado de melhor qualidade e sementes selecionadas em novos tipos de plantação. A grande indústria da fruticultura foi introduzida em Shantung desse modo.

Quanto às outras religiões, a estratégia missionária mostrou-se agressiva, procurando sua substituição pela conversão total das pessoas. Esse espírito agressivo diminuiu no finaldo século, e uma espécie de apreciação pela obra de Deus nas outras religiões desenvolveu-se lentamente até que, em 1910, muitos passaram a considerá-las “luzes defeituosas”, que precisavam ser consertadas em Cristo e usadas como pontes para o evangelho.

Os costumes dos povos do Oriente tornavam quase impossível aos missionários do sexo masculino falar às mulheres e por isso também era difícil chegar às crianças. As esposas dos

PA NIRÓA A EStPARÉgIA INISSTONATIA missionários esforçaram-se por criar escolas para meninas e penetrar nos lares, aposentos de mulheres e haréns, mas não tinham liberdade suficiente por causa dos próprios afazeres domésticos e filhos e não podiam viajar. Uma estratégia realista exigia que se cuidasse adequadamente das mulheres e crianças, porém as juntas e sociedades resistiam tenazmente ao envio de mulheres solteiras ao estrangeiro. Finalmente, em desespero de causa, na década de 1860 as mulheres começaram a organizar suas sociedades e a enviar mulheres solteiras. Uma dimensão totalmente nova foi assim acrescentada à estratégia missionária: o vasto empreendimento de alcançar mulheres e crianças com o evangelho, educar meninas e proporcionar cuidados médicos adequados às mulheres.

As mulheres então começaram a frequentar as reuniões da igreja, e seus filhos menores as acompanhavam. À educação feminina provou sera força mais eficaz para a libertação e elevação social da mulher. A dedicação das missionárias aos serviços médicos obrigou as juntas que mantinham diferentes trabalhos a elevar o nível de qualidade do serviço médico e a destacar mais ainda o conhecimento de medicina. Em vista desses dois grandes empreendimentos das mulheres americanas, no que foram seguidas pelas britânicas e europeias, abriu-se para as mulheres do Oriente o campo que constitui hoje suas profissões de maior prestígio: o serviço na área de saúde (médicas e enfermeiras) eo magistério. Boa vizinhança E preciso citar outro aspecto da estratégia missionária do século XIX: a prática da cortesia. Os missionários enviados pelos batistas do sul dos Estados Unidos foram alguns dos que estabeleceram e praticaram a política de boa vizinhança, À boa mordomia de homens e de recursos financeiros era objeto de alta prioridade entre as juntas e sociedades missionárias. O desperdício era detestado, e havia um forte desejo de aproveitar ao máximo os recursos. À prática da boa vizinhança tinha o objetivo de

R. Pierce Beaver fazer com que alguma agência se responsabilizasse pela evangelização de cada pedaço de território ainda não explorado e de cada pessoa. Era igualmente intenção deles evitar a ocupação duplicada de uma região (exceto nas grandes cidades), sobrepondo programas missionários, de modo que a competição fosse eliminada com as diferenças denominacionais, que confundiriam os habitantes c atrapalhariam a evangelização. Respeitavam-se os territórios ocupados, cas missões recém-chegadas procuravam uma área não explorada. Esse costume produziu o “denominacionalismo geográfico”, mas a expectativa geral era que, no momento em que os missionários partissem para as “regiões mais remotas”,os nacionais juntassem os diferentes pedaços numa igreja nacional diferente de qualquer uma das igrejas fundadoras.

As missões concordavam que todas se reconhecessem como ramos válidos da Igreja única de Cristo, no batismo, na transferência de membros, na disciplina, nos salários ena mudança de obreiros nacionais. Esses acordos levaram a uma cooperação maior no estabelecimento de juntas regionais e nacionais que atuariam no arbitramento de conflitos entreas missões e para a união de projetos de tradução da Bíblia, casas publicadoras, escolas secundárias, faculdades, escolas normais e escolas de medicina. Uma estratégia eficiente exigia cada vez cooperação em tarefas que seriam realizadas com mais eficácia por meio de esforço conjunto. Conferências missionárias urbanas, regionais e nacionais em quase todos os países proporcionavam ocasiões para a discussão eo planejamento das parcerias. Consultas e conferências A colaboração nos campos missionários deu origema consultas e planejamento em escala cada vez maior nos países que enviavam missionários. A Conferência Missionária Mundial de Edimburgo, em 1910, inaugurou uma série de grandes conferências: Jerusalém (1928), Madras (1938), Whitby (1947), Willingen (1952) e Gana (1957-1958). Nessas conferências, foram

267 (4 estabelecidos, em parte, os rumos da estratégia que foi então aplicada a nível local, por meio de estudos e discussões mais aprofundados nas organizações nacionais e regionais, O Concílio Missionário Internacional foi organizado em 1921 e englobava as conferências missionárias nacionais (como à Conferência de Missões Estrangeiras da América do Norte, em 1892) os concílios cristãos nacionais (como o Concílio Nacional de Igrejas, da China), Assim, estabeleceu-se um sistema universal em diversos níveis para o estudo voluntário de problemas e planejamento de estratégia em comum, realizado por um exército de juntas missionárias soberanas. Em 1961, o Concílio Missionário Internacional veio a se transformar na Divisão de Missão Mundial e Evangelização, do Concílio Mundial das Igrejas.

De 1910 até a Segunda Guerra Mundial, o mais notável desenvolvimento de estratégia foi colocar cada vez mais a igreja nacional numa posição-chave, dando-lhe total independência e autoridade e desenvolvendo a colaboração entre as igrejas ocidentais e as mais novas. “A igreja autóctone” e a “cooperação na obediência” foram lemas que expressaram o impulso da estratégia predominante. Os participantes da Conferência de Jerusalém, em 1928, definiram a igreja autóctone, destacando a acomodação cultural, A Conferência de Madras, em 1938, reafirmou a definição e enfatizou o testemunho de Cristo num “relacionamento direto, claro e íntimo com a herança cultural e religiosa do país”. Whitby, em 1947, apresentou o ideal da “cooperação na obediência”. Da Segunda Guerra Mundial em diante Uma estratégia missionária radicalmente diversa, baseada no apóstolo Paulo, foi apresentada por Roland Allen em seus livros Missionary Methods: St. Pauls or Qurs? [Métodos missionários: o de Paulo ou os nossos?] e The Spontancous Expansion of''the Church [A expansão espontânea da Igreja], mas ele não conquistou seguidores, a não ser depois da Segunda Guerra Mundial, quando os missionários das missões para 1. Desde que este artigo foi escrito, cristãos evangélicos têm realizado consultas, reconhecendo que “chegou uma nova era de missões mundiais”, Dentre esses encontros, os mais notáveis fomeios, caminhos e métodos” você espera que esses encontros ofereçam? Dados apresentados 2. Descreva com suas próprias palavras as estratégias missionárias empregadas por três indivi3. Beaver descreve detalhes missões puritanas índios da Nova Inglaterra, Estados Unidos. Que efeitos esses esforços tiveram sobre as iniciativas missionárias posteriores?

268 de fé passaram a adotar de modo especial o padrão de Allen. Esta é, em resumo, sua estratégia: o missionário comunica o evangelho e transmite à nova comunidade de convertidosos ensinos mais simples acerca da fé, da Bíblia, dos sacramentos e do princípio do ministério. Em seguida, ele se coloca de lado, como um irmão mais velho, um conselheiro, enquanto o Espírito Santo orienta a nova igreja autogovernada eautossubsistente para desenvolver formas próprias de política, ministério, culto e vida. Uma igreja assim é espontaneamente missionária. À teoria de Allen era aplicável a trabalhos pioneiros. As antigas juntas e sociedades ocupavam de igrejas antigas e acomodadas, raramente buscando campos novos e não alcançados.

Às organizações missionárias nos campos foram sendo dissolvidas uma após outra. Os recursos foram colocados à disposição de igrejas e do pessoal missionário designado para dirigi-las.

Às juntas e sociedades ocidentais quase não produziram algo novo em termos de estratégia, porém muito fizeram para desenvolver novos métodos: missões agrícolas ou de desenvolvimento rural, algumas indústrias urbanas, meios de comunicação de massa, literatura mais efe discutidos nas três consultas mencionadas duos e três organizações.

A história da estratégia missionária ciente, Essa foi a etapa final de uma missão que estivera em progresso por 300 anos, Agora, o mundo já não se achava mais dividido entre cristianismo e paganismo. Já não podia mais haver uma missão unilateral do Ocidente para o resto do mundo. À base para uma missão já foi estabelecida em quase todos os países, pois neles existe uma igreja e comunidade cristãs com a obrigação de levar o evangelho a todo o mundo. Chegou a hora de uma nova missão mundial com uma estratégia radicalmente nova. À revolução que varreu as regiões não ocidentais do mundo durante e depois da Segunda Guerra Mundial inequivocamente acabou com o antigo regime das missões protestantes.

Chegou uma nova era de missões mundiais, uma era na qual as outras religiões também estão ocupadas em missões mundiais, Uma nova compreensão de missão, uma nova estratégia, uma nova organização, novos meios, caminhos e métodos são as necessidades desta hora na tarefa central da Igreja, tarefa que jamais terminará até que o Reino de Deus se manifeste em toda a sua glória. Enquanto oramos, estudamos, planejamos e experimentamos, será de grande ajuda conhecer a história passada da estratégia missionária.

Perguntas para estudo

1. Desde que este artigo foi escrito, cristãos evangélicos têm realizado consultas, reconhecendo que “chegou uma nova era de missões mundiais”, Dentre esses encontros, os mais notáveis fo- ram os de Berlim (1966), Lausanne (1974), Pattaya (1980) e Edimburgo (1980). Que “novos meios, caminhos e métodos” você espera que esses encontros ofereçam? Dados apresentados e discutidos nas três consultas mencionadas estão registrados em outro parte desta obra.

2. Descreva com suas próprias palavras as estratégias missionárias empregadas por três indivíduos e três organizações.

3. Beaver descreve com detalhes as missões puritanas entre os índios da Nova Inglaterra, nos Estados Unidos. Que efeitos esses esforços tiveram sobre as iniciativas missionárias posteriores?'
where curso_id = (select id from cursos where slug = 'perspectivas') and ordem = 45;
update aulas set conteudo = 'William Carey

Extraído de William Carey, An Enquiry Into the Obligations of Christians to Use Means for the Conversion of the Heathens [Uma investigação sobre o dever dos cristãos de empregarem meios para a conversão dos pagãos] (1792), fac-símile de 1962.

Em 1792, um jovem e empobrecido pastor inglês, professor de tempo parcial e sapateiro, tomou para si a tarefa de escrever suas convicções e publicá-las num panfleto, reagindo assim à ideia predominante em sua época de que a Grande Comissão já não mais se aplicava aos cristãos. Ele quase não tinha pendor literário e evitava chamar a atenção sobre si. Aliás, pertencia a uma denominação que era um dos menores grupos dissidentes de seus dias. No entanto, a Investigação, de William Carey, e seu exemplo pessoal a partir de então e por mais de 40 anos, provocaram uma importantíssima revolução na maneira de pensar e de agir da Igreja, basicamente à medida que sua proposta confirmou para os protestantes a validade e a necessidade de estruturas de “ordens” missionárias.

Carey e um amigo, enviados pela recém-organizada Sociedade Missionária Batista, partiram para a Índia em 1793, vindo a se estabelecer em Serampore, enclave dinamarquês próximo de Calcutá. Carey, Joshua Marshman e William Ward, o “trio de Serampore”, traduziram e imprimiram porções da Bíblia em diversas línguas asiáticas e fundaram uma escola para cristãos indianos. Quase sem qualquer educação formal, mas de uma perseverança e convicção extraordinárias, Carey superou crises financeiras, catástrofes naturais, enfermidades na família e críticas dos ingleses, de modo que conseguiu fazer progressos na evangelização, na filologia, nas ciências naturais e na educação. Ele desafiou a Igreja e a si mesmo a “esperar grandes coisas de Deus e realizar grandes coisas para Deus”,

Hoje, Carey é reconhecido como o pai das missões protestantes”, visto que os historiadores datam o período moderno das missões protestantes a partir da data de publicação de sua Investigação. O dr. Ernest À. Payne comenta:

Hoje em dia, quem lê a Investigação fica surpreso, primeiramente por sua factualidade serena e por sua atualidade. Mais de um quarto das páginas são gráficos minuciosos acerca de vários países do mundo, sua extensão territorial, número de habitantes e religiões ali representadas. Em toda a obra, há uma clara divisão em secções, e os itens são numerados. O conteúdo é breve, lógico, preciso, mais parecido com um relatório governamental ob-

Jetivo ou com o parecer de uma comissão que com um apelo profético à Igreja de Cristo. Não se apela à eloquência ou ao sentimento nem se procura reunir criteriosamente textos de prova extraídos da Bíblia, tampouco há uma discussão teológica intrincada: trata-se de uma cuidadosa apresentação de fatos. O próprio título é característico do autor...

Escrevendo em 1885, George Smith chamou-o “o primeiro e ainda o maior tratado missionário em língua inglesa”. Ainda não fot ultrapassado em sua simplicidade ou irrefutabilidade.

O que segue é uma composição de parágrafos selecionados da Investigação de Carey, com suas 87 páginas originais.

E Pes RAS Oie pon es Y

De É fire: nosso bendito Senhor determinado

que orússemos para que seu Reino viessee para que sua vontade fosse feita na terra assim como o é no céu, é nosso dever expressar não apenas com palavras o desejo de que isso ocorra, mas também empregar todo método legítimo para espalharmos o conhecimento de seu nome. A fim de realizá-lo, é necessário que nos familiarizemos um pouco com a situação religiosado mundo, e como esse é um objetivo que devemos estar prontos a atingir, não apenas por causa do evangelho de nosso Redentor, mas também por sentimentos de solidariedade humana, uma tendência a uma atividade conscienciosa nesse particular será uma das evidências mais fortes de que somos os recipientes da graça e participantes daquele espírito de benevolência universale filantropia genuína, que parecem tão eminentes no caráter do próprio Deus.

O pecado introduziu-se entre os filhos dos homens com a queda de Adão e desde então vem espalhando sua influência destruidora. Ao mudar sua aparência para se adaptar às circunstâncias, o pecado tem se manifestado em milhares de aspectos diferentes e, constantemente, agido contra a vontade e os desígnios de Deus. Seria de esperar que a lembrança do dilúvio se transmitisse de pai para filho e evitasse definitivamente que a humanidade transgredisse a vontade do Criador. Todavia, estavam tão cegos que, à época de Abraão, uma profunda iniquidade dominava todos os lugares em que os seres humanos se estabeleciam, ea iniquidade dos amorreus foi grande, embora ainda não atingisse o grau máximo. Depois disso, a idolatria se espalhou cada vez mais, até que as sete nações profundamente religiosas foram eliminadas numa grande demonstração do desagrado divino. Contudo, isso não foi suficiente para que o avanço do mal se interrompesse: os próprios israelitas, com demasiada frequência, uniam-se ao restante da humanidade contra o Deus de Israel.

Deus, todavia, repetidas vezes, tornou conhecida sua intenção de prevalecer, de por fim sobre o poder do Diabo, destruir todas as suas mimo dor dorernio obras, estabelecer seu Reino entre 0s homens, ter direito sobre cles e ampliar seu Reírio de modo tão universal quanto o de Satanás, Foi com esse propósito que o Messias veio e morreu, para que Deus pudesse ser justo o justificados de todo aquele que vier a crer nele, Depois que deua própria vida e a retomou, Cristo enviou os discípulos a pregar as boas novas a cada criaturaca procurar, por todos os métodos possíveis, trazer o mundo perdido para Deus, Eles partiram em obediência à ordem recebida da parte de Deus, e um êxito maravilhoso acompanhou seus labores. Tanto os gregos civilizados quanto os bárbaros incultos se renderam à cruz de Cristo cabraçaram-na como o único meio de salvação, Desde o período apostólico têm sido feitas muitas outras tentativas de espalhar o cvangelho, as quais têm alcançado considerável sucesso, embora uma grande parcela da humanidade ainda esteja vivendo nas trevas do paganismo. Algumas tentativas ainda estão sendo feitas, mas elas são ínfimas, em comparação com o que se poderá fazer caso todo o corpo de cristãos entre de coração no espírito da ordem divina sobre o assunto. Alguns quase não pensam a respeito, outros desconhecem a situação do mundo, outros ainda amam mais as riquezas que as almas dos que são criaturas iguais a eles.

À fim de que o assunto possa receber uma análise mais séria, pretendo investigar se a ordem dada por nosso Senhor aos seus discípulos ainda diz respeito a nós, ver rapidamente como essa ordem foi obedecida no passado, oferecer algumas informações sobre a atual situação do mundo, analisar a viabilidade de fazer algo mais que o que está sendo feito e o dever dos cristãos em geral quanto a esse assunto. Investigação para saber se a ordem dada por nosso Senhor ainda diz respeito a nós Pouco antes de sua partida, nosso Senhor Jesus Cristo comissionou seus discípulos dizendo: “Ide, fazei discípulos de todas as nações”. Ou, como outro evangelista registrou: “Ide por todo o mundo e pregai o evangelho a toda criatura”. Essa comissão era a mais ampla

William Carey possível e impôs aos discípulos o dever de se dispersarem por todos os países do mundo habitado a fim de pregar o evangelho a todos os habitantes da terra, sem exceção ou restrição. Em vista disso, eles partiram em obediênciaa essa ordem, e o poder de Deus evidentementeos acompanhou. Desde então, foram feitas muitas tentativas semelhantes, as quais têm alcançado maior ou menor sucesso. Entretanto, em períodos mais recentes não se tem assumido ou realizado a tarefa (embora haja algumas poucas exceções) com aquele zelo e perseverança que caracterizaram os primeiros cristãos. É como se muitos pensassem que a comissão já estivesse realizada a contento por aquilo que os apóstolos e outros fizeram. Parece já termos muito que fazer para levar a salvação aos nossos compatriotas e que, caso Deus deseje a salvação dos pagãos, de uma maneira ou de outra, ele os levará ao evangelho ou o evangelho a eles. Dessa forma, um grupo enorme de pessoas se sente à vontade e não se interessa pelo número ainda maior de pecadores que até hoje está perdido na ignorância enaidolatria. Também parece existir na mente dealguns a convicção de que, pelo fato de os apóstolos terem sido líderes extraordinários e não terem deixado sucessores e também por que muitas das coisas que eles fizeram serem injustificáveis para nós, é bem provável que não tenhamos uma obrigação direta de realizar a comissão, embora os apóstolos tivessem esse dever. Desejo apresentar os seguintes argumentos à consideração de pessoas que assim pensam.

PRIMEIRO: caso a ordem de Cristo, de fazer discípulos de todas as nações, se limiteaos apóstolos ou àqueles sob a inspiração direta do Espírito Santo, então a ordem de batizar também deve ser igualmente limitada àqueles, etodasas denominações cristãs, com exceção dos quacres, incorrem em erro ao batizar, qualquer que seja a forma de batismo.

SEGUNDO: caso a ordem de Cristo, de fazer discípulos de todas as nações, se restrinja aos apóstolos, então todos esses pastores comuns que têm se lançado a levar o evangelho aos pagãos estão agindo sem a devida au-

293 É torização e se precipitaram em ir, em vez de serem enviados. Além disso, embora Deus tenha prometido as coisas mais gloriosas ao mundo pagão por meio de seu evangelho, de qualquer forma quem for primeiro, ou melhor, quem quer que vá com essa mensagem, a menos que tenha uma ordem nova e especial recebida do céu, está agindo sem autorização.

TERCEIRO: caso a ordem de Cristo, de fazer discípulos de todas as nações, se restrinja aos apóstolos, então, sem dúvida alguma, a promessa da presença divina nessa tarefa também deve estar limitada aos apóstolos. Todavia, a ordem está expressa de tal maneira que claramente rejeita tal ideia: “Eis que estou convosco todos os dias até à consumação do século”.

Tem-se objetado que em nosso próprio país há multidões que estão ao nosso alcance direto e são tão ignorantes acerca do evangelho quanto os selvagens que habitam as ilhas dos mares do Sul e, portanto, temos suficiente trabalho a realizar aqui, sem termos de ir a outros lugares. Sem qualquer hesitação, reconheço que em nosso país há milhares de pessoas muitíssimo distantes de Deus e é indubitável que esse fato deve nos desafiar a um esforço redobrado em realizar nossa tarefa e espalhar o conhecimento de Deus entre eles. Todavia, parece insustentável a afirmação de que tal fato deva se sobrepor à tarefa de levar o evangelho a outros lugares. Nossos compatriotas possuem os meios de graça e poderão aceitar a palavra pregada caso desejem fazê-lo. Eles têm os meios de conhecer a verdade, e pastores fiéis existem em quase todas as regiões de país, ministros cujo raio de ação poderia ser bem ampliado, se suas igrejas fossem apenas um pouco mais sensíveis e ativas na causa. Com os pagãos, o caso é diferente, pois eles não têm a Bíblia, não têm uma língua escrita (muitos deles), não têm pastores, não têm um bom governo civil nem aquelas vantagens que possuímos. Portanto, a piedade, o espírito de humanidade e muito mais, o cristianismo, conclamam em alta voz que se empreendam todos os esforços possíveis para a introdução de evangelho entre eles,

Apresentamos aqui apenas 4 dos 24 gráficos que Carey inseriu na Investigação [N. do. E.). EEE EEE De DE E EE E EE SIS RES RENTA Ade 870 210 1600000|Cristãosepaçãos Negrolândia [3520/1350] 18000000/Pagãos Longo] 480 15c0000)Pagãos

294 Resumo de empreendimentos para a conversão dos pagãos feitos no passado A história sobre os atos dos apóstolos revela-nos o sucesso da pregação da Palavra logo no início, e à história da Igreja informa que ela foi anunciada em muitos outros lugares na época. Pedro faz menção de uma igreja na Babilônia, Paulo planejou uma viagem à Espanha e é geralmente aceito que ele realizou tal viagem e chegou à França e à Grã-Bretanha. André pregou aos citas, ao norte do mar Negro. Acredita-se que João tenha pregado na Índia e sabemos que ele esteve na ilha de Patmos, no mar Egeu. Diz-se que Filipe pregou no norte da Ásia, na região dos citas e na Frígia. Bartolomeu pregou na Índia (do lado ocidental do rio Ganges), na Frígia e na Armênia. Mateus pregou na Arábia (a região da Etiópia asiática) e na Pártia. Tomé pregou na Índia, chegando a alcançar o litoral de Coromandel, e, como alguns creem, na ilha do Ceilão. Simão Cananeu pregou no Egito, em Cirene, na Mauritânia, na Líbia e em outras regiões da África, daí partindo para a Grã-Bretanha. Afirma-se que Judas esteve principalmente envolvido com a pregação na EE Biledulgerid 560 Saara [5450/1060] Abissínia [1450 [1280] [eongo a JA.) o360.] EPE [Benguela Matamon 600 [to 200 (Man Jamo] 480 Zonibar [2200] 560

Uma Investigação sobre o dever dos cristãos Ásia Menor e na Grécia, Evidentemente, seus esforços foram bem amplos e obtiveram grande êxito, de modo que Plínio, o Jovem, que viveu logo depois da morte dos apóstolos, numa carta ao imperador Trajano, comentou que o cristianismo havia se espalhado não apenas pelas cidades, chegando às mais importantes, mas também por vastas regiões rurais, Aliás, antes disso, à época de Nero, o crescimento do cristianismo estava se tornando tão ameaçador que se chegou à conclusão de que seria necessário um édito imperial para enfrentá-lo. De acordo com esse édito, os procônsules e outros governantes receberam a incumbência de destruí-lo. Uma pesquisa sobre a situação atual do mundo Nessa pesquisa irei considerar o mundo conforme geralmente é dividido, a saber, em quatro partes: África, América, Ásia e Europa. Farei ainda observações sobre a extensão geográfica dos diversos países, sua população, civilização e religião. Os gráficos a seguir apresentarão uma visão mais abrangente do que proponho que qualquer outra coisa que eu possa apresentar sobre o assunto.!

Cristôosarménios 2000000] Pagd0s o]

[figura] /figuras/perspectivas/carey-tabelas-paises.png | Levantamento de Carey: América, Ásia e Europa — países, extensão, número de habitantes e religião

Essa é, com as informações que consigo obter, a situação do mundo, embora de muitos países, como a Turquia, a Arábia, a Grande Tartária, a África e a América, com exceção dos Estados Unidos, e a maioria das ilhas da Ásia, não tenhamos registros confiáveis sobre o número de habitantes. Por essa razão, apenas calculei a extensão geográfica e chegueiaum determinado número de habitantes com base na média de habitantes por quilômetro quadrado. Em alguns países essa média foi maior, cem outros, menor, de acordo com as circunstâncias. Todos esses dados representam clamores aos cristãos, especialmente aos pastores, a que se dediquem ao máximo em suas diversas áreas de ação e tentem ampliá-las o máximo possível. A viabilidade de se fazer algo mais que o que está sendo feito com vistas à conversão dos pagãos Os obstáculos para se levar o evangelho aos pagãos deverão surgir, creio, a partir de uma ou outra das seguintes coisas: sua distância de nós, sua maneira bárbara e selvagem de viver, o perigo de sermos mortos por eles, a dificuldade de atender às necessidades mais básicas da vida e a ininteligibilidade dos idiomas.

PRIMEIRO: em relação à distância, quaisquer objeções que se pudessem fazer com base nessa questão antes da invenção da bússola, com sua grande utilidade na navegação, hoje em dia não fazem sentido. Atualmente é possível navegar com tanta certeza pelo imenso Pacífico Sul como se pode fazê-lo pelo Mediterrâneo ou por outro mar menor, e a Providência parece estar nos convidando a realizar o trabalho, pois, como é de nosso conhecimento, existem empresas de importação e exportação cujo comércio se localiza em muitos dos lugares onde esses bárbaros habitam.

SEGUNDO: em relação à sua maneira bárbara e incivilizada de viver, isso não deve ser objeção para ninguém, exceto aqueles cujo apego ao conforto apaga o desejo de se expor a dificuldades com vistas ao bem de nossos semelhantes.

Não foi objeção para os apóstolos e seus sucessores, que alcançaram as tribos bárbaras dos germanos e gauleses e os ainda mais bárbaros bretões! Eles não esperaram até que os habitantes desses países se tornassem civilizados paraentão cristianizá-los, mas foram avante apenascoma doutrina da cruz, e Tertuliano pôde se ufanar de que “aquelas regiões da Grã-Bretanha que eram invencíveis diante dos exércitos romanos foram conquistadas pelo evangelho do Cristo”, Muitos anos mais tarde, não existiuessaobjeção paraum Eliot ou para um Brainerd. Elesforam avante e enfrentaram toda espécie de dificuldade e descobriram que uma aceitação sincera do evangelho produzia resultados positivos que o mais prolongado contato com europeus, que não conheciam o evangelho, jamais alcançaria. Essa não é uma objeção para os comerciantes. Só exige que tenhamos tanto amor pelas almas de pecadores semelhantes a nós como oscomerciantes têm pelo lucro de umas poucas peles de lontra. Caso tenhamos esse amor todas essas dificuldades serão facilmente vencidas.

TERCEIRO: em relação ao perigo de sermos mortos por eles, sem dúvida alguma quem for deverá entregar a vida nas mãos de Deus, em vez de buscar o conselho de carne e sangue. Será que abondade da causa, os deveres que recaem sobre nós como criaturas de Deus e como cristãos, e a condição perdida de nossos semelhantes, não clamam em voz alta para que nos arrisquemos e empreguemos todos os meios justificáveis para benefício deles? Paulo e Barnabé, que expuseram a vida ao perigo por amor do nome de nosso Senhor Jesus Cristo, não foram repreendidos, mas elogiados por seu arrojo, ao passo que João Marcos, que por timidez os abandonou no meio de um empreendimento perigoso, foi censurado por tal comportamento. Além do mais, como já tem sido comentado, questiono bastante se a maioria das barbaridades praticadas pelos selvagens contra aqueles que os têm visitado não se originaram de alguma afronta real ou imaginária e, portanto, não foram, melhor dizendo,atosde autodefesa, em vez de demonstrações de atitude feroz. Não é de admirar que a imprudência dos

Willlam Carey marinheiros facilmente os leve aofenderosimples selvagem e que este sinta algum ressentimento contra a ofensa. Todavia, Elliot, Brainerd cos missionários morávios raramente foram molestados. Ao contrário, em geral os pagãos têm demonstrado disposição para ouvir a palavrae se manifestam ódio contra o cristianismo quase sempre isso se deve ao mau comportamento de cristãos nominais.

QUARTO: em relação à dificuldade de atender às necessidades básicas da vida, isso não é tão difícil quanto poderá parecer à primeira vista, pois embora não consigamos obter comida europeia, ainda assim poderemos obter a comida da qual os nativos dos países que visitamos se alimentam.

Talvez seja necessário que se enviem sempre pelo menos duas pessoas, e creio que será melhor que essas duas pessoas sejam homens casados. Para evitar que percam tempo atendendo às necessidades básicas, dois ou mais outros homens, com esposa e filhos, também poderão acompanhá-los, os quais deverão dedicar-se inteiramente a obter os meios de subsistência. Na maioria dos países, será necessário que cultivem um pequeno pedaço de terra, apenas para seu sustento, o que poderá ser uma fonte de recursos caso deixem de receber suprimentos. Aliás, pode-se pensar numa grande variedade de métodos, e, uma vez que se assuma a tarefa, muitas outras ideias virão à mente, nas quais hoje nem sequer pensamos.

QUINTO: em relação a aprender os idiomas, descobre-se que a mesma habilidade é necessária tanto aqui quanto no comércio entre as diferentes nações. Em alguns casos, pode-se ter a ajuda de intérpretes contratados por algum tempo. Nos lugares em que não há intérpretes, os missionários deverão ter paciência e se misturar ao povo até que tenham aprendido dalíngua o suficiente para comunicar suas ideias ao povo. É fato bem conhecido que não se requer talentos extraordinários para aprender em um ano,ouno máximo em dois, o suficiente de um idioma de qualquer povo da terra para expressar quaisquer pensamentos que queiramos a eles.

297 (o Uma investigação sobre o dever dos cristãos em geral e sobre os meios que se devem usar para cumprir essa tarefa Caso as profecias acerca do crescimento do Reino de Cristo sejam verdadeiras, e o que se tem mencionado a respeito da comissão dada por ele aos seus discípulos como obrigatória para nós esteja correto, podemos concluir que todo cristão deve, de coração, cooperar com Deus na consecução de seus gloriosos desígnios, pois aquele que se une ao Senhor é um espírito com ele.

Um dos primeiros e mais importantes deveres que recaem sobre nós é o da oração fervorosa cem espírito de unidade, Creio que as reuniões mensais de oração, em que intercedemos pelo avanço do evangelho, não têm sido em vão. É certo que uma falta de insistência tem caracterizado nossas orações, e; embora nossas orações tenham sido débeis e pouco insistentes, deve-se crer que Deus tem ouvido e, em grande parte, respondido a elas, Se uma santa ansiedade houvesse dominado todas as reuniões de cristãos, aquelas realizadas no interesse do Reino de seu Redentor, provavelmente já teríamos visto não apenas uma porta aberta para o evangelho, mas muitas pessoas correndo de um lado para outro e o conhecimento do evangelho se espalhando; ou então teríamos visto um emprego cuidadoso dos meios que a providência colocou à nossa disposição, seguido por uma bênção incomum vinda do céu.

Há muitos que nada podem fazer além de orar, porém a oração é talvez a única coisa pela qual os cristãos de todas as denominações podem de coração e sem qualquer reserva se unir. Nisso, todos podemos ser um só, e a mais estrita unanimidade deve prevalecer.

Não devemos, todavia, nos contentar com a oração, sem nos esforçarmos no uso de meios que ajudem a obter aquilo pelo qual oramos. Se os filhos da lux fossem tão sábios em sua geraão quanto os filhos deste mundo, eles se esforçariam ao máximo para conquistar um prêmio tão glorioso, não mais ficariam imaginando como obtê-lo de outra maneira.

Quando uma companhia de importação e exportação obtém sua licença de funcionamento, geralmente ela explora o máximo que lhe é permitido fazer. Suas mercadorias, seus navios e sua tripulação são escolhidos e controlados de modo que alcancem o objetivo da companhia. Contudo, ela não se limita a isso, pois, incentivada pela perspectiva de sucesso, emprega todo esforço, lança seu pão sobre as águas e cultiva amizade com qualquer um que lhe possa transmitir informações úteis.

Imagine um grupo de cristãos sérios, formado por pastores e leigos, se organizasse numa sociedade e estabelecesse várias regras acercados planos, das pessoas a serem empregadas como missionários, dos meios de suprir os gastos, e assim por diante. Tal sociedade deve consistir de pessoas cujo coração esteja na obra, homens de religião séria e possuidores de um espírito de perseverança. Deve haver a determinação de não admitir na sociedade pessoas que não se enquadrem nessa descrição e só manter na sociedade os que continuarem a satisfazer essas exigências.

Em tal sociedade, pode-se nomear uma comissão cuja responsabilidade seja obter, mesmo com dificuldade, todas as informações possíveis relativas à sua atividade, receber contribuições, investigar o caráter, temperamento, habilidades e convicções religiosas dos missionários, e também fornecer-lhes os recursos mínimos necessários para o trabalho que irão assumir.

Se há qualquer razão para que eu creia que terei qualquer influência sobre qualquer de meus irmãos em Cristo, provavelmente essa influência se dará especialmente entre aqueles de minha própria denominação. Proponho, portanto, que uma tal sociedade e comissão se organizem na denominação batista particular.

Uma das moedas de menor valor na Inglaterra [N. do E.).

Uma Investigação sobre o dever dos cristãos

Não quero com isso dizer que se deva, de alguma maneira, restringir essa tarefa a uma única denominação, De todo o coração, desejo que todo aquele que sinceramenteamaao Senhor Jesus Cristo se envolva nessaobra,deum modo ou de outro, mas, em face da divisão que hoje existe na cristandade, é mais provável o êxito se cada denominação se dedicar separadamente ao trabalho, em vez de fazê-lo em parceria.

Com relação às contribuições para cobrir as despesas, sem dúvida haverá necessidade de dinheiro. Se as igrejas derem oportunidade para contribuições semanais de um péni” ou mais por pessoa, de acordo com as possibilidades, e depositarem tal recurso num fundo financeiro para a propagação do evangelho, muito poderá ser arrecadado para o sustento da obra.

Somos exortados a ajuntar “tesouros no céu, onde traça nem ferrugem corrói, e onde ladrões não escavam, nem roubam”. Também está escrito que “aquilo que o homem semear, isso também ceifará” Essas passagens bíblicas nos ensinam que as alegrias da vida vindoura têm profunda relação com nossa atividade aqui na terra, uma relação semelhante à que existe entre a semente e a ceifa. É certo que toda recompensa é resultado da pura graça de Deus, mas de qualquer maneira é animador que um tesouro, uma colheita esteja à espera de pessoas como Paulo, Eliot, Brainerd e outros, os quais se deram inteiramente à obra do Senhor. Que maravilha será ver as muitas miríades de pobres pagãos, entre eles bretões, que pelotrabalho daqueles chegaram ao conhecimento de Deus! Vale a pena almejar uma coroa de júbilo como essa. Com certeza, vale a pena nos consagrarmos inteiramente, com todos os recursos de que dispomos, para a promoção da causae do Reino de Cristo.

Wiilam Carey 299 (O PETS PET TE DO er

Perguntas para estudo À. Observe o destaque das estatísticas de Carey: clamores aos cristãos, especialmente aos pastores, a que se dediquem ao máximo em suas diversas áreas de ação...”. Será que essas estatísticas levam os cristãos de hoje à ação? Por quê? 2. Carey conclui o livreto com uma rápida descrição dos “meios” que ele advoga. Apresente um resumo da definição de Carey para “meios”.'
where curso_id = (select id from cursos where slug = 'perspectivas') and ordem = 52;

commit;
